// ── Confessional seed stories ───────────────────────────────────────────────
// Hand-written sample stories so the feed has texture on first visit. Author
// IDs are sentinel strings ("seed:*") that won't collide with any real user
// id. These all start with status='published' (and one as 'featured') so
// they appear immediately.

import type { ConfessionalPost, ConfessionalReply } from "@/types/confessional";

const SEED_AUTHOR_PREFIX = "seed:";

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function currentMonth(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}

export const SEED_CONFESSIONAL_POSTS: ConfessionalPost[] = [
  {
    id: "conf-seed-1",
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
    author_id: `${SEED_AUTHOR_PREFIX}1`,
    display_name: "The Reluctant Bridesmaid",
    title: "My MOH made my engagement party about her breakup. Twice.",
    body: "I've known her since we were 9. I asked her to be my maid of honor the day after I got engaged because there was never a question. Two weeks later her boyfriend of three years dumped her — fine, I held her while she cried for a month, I get it.\n\nAt my engagement party — at MY parents' house, with MY in-laws meeting them for the first time — she gave a 12-minute toast about how love isn't real and how she hopes \"this one works out for at least one of us.\" My fiancé's mother actually gasped. I laughed it off because what else do you do.\n\nThree months later she did it AGAIN at my bridal shower. Different speech, same energy. I uninvited her from the bachelorette and she sent me a 4-page text about how I was abandoning her in her darkest hour.\n\nThe wedding is in 6 weeks. I haven't told her she's been demoted to \"regular bridesmaid.\" I will. I'm just trying to find the right moment, which I'm starting to suspect doesn't exist.",
    category: "bridal-party-meltdown",
    tags: ["maid-of-honor", "toast-disaster", "long-friendship"],
    status: "featured",
    is_featured: true,
    featured_month: currentMonth(),
    save_count: 247,
    vote_up_count: 312,
    vote_down_count: 8,
    view_count: 2840,
    report_count: 0,
    is_seed: true,
  },
  {
    id: "conf-seed-2",
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
    author_id: `${SEED_AUTHOR_PREFIX}2`,
    display_name: "Chaos Florist",
    title: "I'm the florist. The bride didn't pay. Now she's leaving 1-star reviews.",
    body: "Switching sides for a sec — I'm a vendor, not a bride.\n\nDid a $14k floral install for a wedding last October. Contract signed, deposit paid, balance due 30 days before the date. Day of the wedding rolls around, balance still unpaid. I install everything anyway because what am I going to do, rip down the mandap an hour before the ceremony?\n\nIt has now been six months. Three lawyers' letters. She finally paid 60% of the balance and is now leaving 1-star reviews on every platform she can find calling me \"unprofessional and overpriced.\"\n\nMy question for the brides reading this: would it be insane to publish the actual contract and the receipts? My lawyer says yes. My therapist says yes. My partner says yes. But I'm losing bookings.",
    category: "vendor-nightmare",
    tags: ["unpaid-vendor", "fake-reviews", "florist-pov"],
    status: "published",
    is_featured: false,
    save_count: 189,
    vote_up_count: 224,
    vote_down_count: 3,
    view_count: 1920,
    report_count: 0,
    is_seed: true,
  },
  {
    id: "conf-seed-3",
    created_at: daysAgo(8),
    updated_at: daysAgo(8),
    author_id: `${SEED_AUTHOR_PREFIX}3`,
    display_name: "Undercover Mother-in-Law",
    title: "I told my future DIL her dress was unflattering. Was I wrong?",
    body: "She asked. She literally asked. We were at the second fitting and she turned to me — me, her future mother-in-law, who she barely knows — and said \"be honest, does this make me look wider?\"\n\nI said \"a little, in the bodice — the other one was more flattering.\"\n\nShe burst into tears, walked out, and hasn't spoken to me in 11 days. My son says I crossed a line. The seamstress (who is now apparently her best friend) says I crossed a line.\n\nBut she ASKED. What was I supposed to say? \"You look great\" when she clearly wanted a real answer? I would never have volunteered the opinion. I waited until she invited it.\n\nVote me wrong if you must but I think honesty was the gift she asked for.",
    category: "was-i-wrong",
    tags: ["dress-fitting", "mother-in-law", "honesty"],
    status: "published",
    is_featured: false,
    save_count: 412,
    vote_up_count: 89,
    vote_down_count: 287,
    view_count: 3200,
    report_count: 0,
    is_seed: true,
  },
  {
    id: "conf-seed-4",
    created_at: daysAgo(12),
    updated_at: daysAgo(12),
    author_id: `${SEED_AUTHOR_PREFIX}4`,
    display_name: "The Exhausted Planner",
    title: "Hire the planner. That's it. That's the post.",
    body: "I tried to DIY a 280-person three-day wedding because I have a spreadsheet brain and I thought I could.\n\nI could not.\n\nThe one thing nobody tells you is that the work doesn't scale linearly — it scales exponentially. Each vendor adds a thread. Each thread crosses every other thread. By month four I had 47 active email threads, 12 group chats, and a whiteboard the size of my dining room wall. I was working a full-time job. My partner barely saw me.\n\nWe finally hired a coordinator at month seven, six weeks before the wedding. She charged us $4,200. It was the single best money we spent in the entire budget — including the venue.\n\nWhatever you think you're saving by going without one, double it. That's what you're actually paying in stress, sleep, and time you'll never get back.",
    category: "the-one-thing",
    tags: ["planner", "diy-wedding", "lessons"],
    status: "published",
    is_featured: false,
    save_count: 538,
    vote_up_count: 491,
    vote_down_count: 12,
    view_count: 4100,
    report_count: 0,
    is_seed: true,
  },
  {
    id: "conf-seed-5",
    created_at: daysAgo(15),
    updated_at: daysAgo(15),
    author_id: `${SEED_AUTHOR_PREFIX}5`,
    display_name: "Runaway Bride",
    title: "The DJ played the wrong first-dance song. I cried real tears.",
    body: "Six months of correspondence. A signed playlist. Three confirmation emails the week of. A literal printed timeline in his hands.\n\nThe moment came. The lights dimmed. We walked onto the floor. And out came… a song that was on a different couple's playlist. Same DJ, different wedding the night before. Wrong song, wrong key, wrong everything.\n\nMy partner whispered \"just dance to it\" and we did. We slow-danced to a song neither of us had ever heard while 200 people watched and I cried not-pretty tears. Photos exist.\n\nThe DJ refunded 30%. I'm still mad. We replayed our actual song three days later in our living room and danced in pajamas. Honestly that one was better.",
    category: "day-of-disaster",
    tags: ["dj", "first-dance", "wrong-song"],
    status: "published",
    is_featured: false,
    save_count: 156,
    vote_up_count: 198,
    vote_down_count: 5,
    view_count: 1670,
    report_count: 0,
    is_seed: true,
  },
  {
    id: "conf-seed-6",
    created_at: daysAgo(20),
    updated_at: daysAgo(20),
    author_id: `${SEED_AUTHOR_PREFIX}6`,
    display_name: "The Petty Bride",
    title: "My aunt RSVP'd no, then showed up with three uninvited cousins.",
    body: "She RSVP'd no. In writing. By mail. Twice (we sent a follow-up).\n\nDay of: she walks in during cocktail hour with her husband AND her three adult sons (who were not on the guest list because we'd never met two of them). My venue coordinator finds me mid-photos to ask if we have five extra place cards. Reader, we did not.\n\nWe scrambled. We made it work. They sat at the leftover-vendor-meal table with my photographer and a plus-one. My aunt left without saying goodbye and has been telling the family I \"didn't make her feel welcome.\"\n\nShe RSVP'd. NO.",
    category: "family-drama",
    tags: ["rsvp", "uninvited", "aunt"],
    status: "published",
    is_featured: false,
    save_count: 203,
    vote_up_count: 267,
    vote_down_count: 4,
    view_count: 2200,
    report_count: 0,
    is_seed: true,
  },
  {
    id: "conf-seed-7",
    created_at: daysAgo(25),
    updated_at: daysAgo(25),
    author_id: `${SEED_AUTHOR_PREFIX}7`,
    display_name: "The Over-It Bride",
    title: "Spreadsheets gave me a panic attack at 2am. Multiple times.",
    body: "I want to talk about the part nobody photographs — the 2am panic attacks over the seating chart.\n\nMy version of planning hell wasn't any one big disaster. It was the slow, grinding accumulation of decisions. Eight thousand decisions. Linen color, fork weight, font on the menu, font on the place cards, are the fonts the SAME font, why are they different, do guests notice, does it matter.\n\nBy month five I had three spreadsheets, four shared docs, and a mood board with 412 pins. I was waking up at 2am to tweak a column width. My partner found me one night literally crying because I couldn't decide between two shades of cream.\n\nWhat helped: I deleted two of the spreadsheets. I told my mother she could pick the linens. I let go of three things every Sunday.\n\nThe wedding was beautiful. Nobody noticed the linens.",
    category: "planning-hell",
    tags: ["overwhelm", "panic", "letting-go"],
    status: "published",
    is_featured: false,
    save_count: 389,
    vote_up_count: 421,
    vote_down_count: 6,
    view_count: 3450,
    report_count: 0,
    is_seed: true,
  },
];

export const SEED_CONFESSIONAL_REPLIES: ConfessionalReply[] = [
  {
    id: "conf-reply-seed-1",
    post_id: "conf-seed-1",
    author_id: `${SEED_AUTHOR_PREFIX}r1`,
    display_name: "Anonymous Bride",
    body: "Demote her by text. Today. The right moment doesn't exist and waiting just makes it worse — I learned that the hard way.",
    created_at: daysAgo(1),
    status: "published",
    report_count: 0,
  },
  {
    id: "conf-reply-seed-2",
    post_id: "conf-seed-1",
    author_id: `${SEED_AUTHOR_PREFIX}r2`,
    display_name: "The Forgotten Bridesmaid",
    body: "I was the one who got demoted. It hurt. It was also the right call. We're still friends.",
    created_at: daysAgo(1),
    status: "published",
    report_count: 0,
  },
  {
    id: "conf-reply-seed-3",
    post_id: "conf-seed-3",
    author_id: `${SEED_AUTHOR_PREFIX}r3`,
    display_name: "The Petty Plus-One",
    body: "She didn't actually want honesty, she wanted reassurance dressed up as a question. Most people do.",
    created_at: daysAgo(11),
    status: "published",
    report_count: 0,
  },
  {
    id: "conf-reply-seed-4",
    post_id: "conf-seed-4",
    author_id: `${SEED_AUTHOR_PREFIX}r4`,
    display_name: "Drama-Free Groom",
    body: "Saving this and sending it to my partner who is currently mid-spreadsheet on a Sunday night.",
    created_at: daysAgo(10),
    status: "published",
    report_count: 0,
  },
];
