import type {
  MarketplaceCategory,
  MarketplaceListing,
} from "@/types/marketplace";

// ── Categories ──────────────────────────────────────────────────────────────

export const SEED_CATEGORIES: MarketplaceCategory[] = [
  { slug: "bridal_wear", label: "Bridal Wear", emoji: "👰", description: "Lehengas, sarees, gowns, dupattas", sort_order: 1 },
  { slug: "groom_wear", label: "Groom Wear", emoji: "🤵", description: "Sherwanis, suits, kurtas, dupattas", sort_order: 2 },
  { slug: "jewelry", label: "Jewelry & Accessories", emoji: "💎", description: "Bridal sets, bangles, maang tikka, kalire", sort_order: 3 },
  { slug: "decor", label: "Décor & Props", emoji: "🎨", description: "Centerpieces, mandap décor, signage, backdrops", sort_order: 4 },
  { slug: "signage", label: "Signs & Boards", emoji: "🪧", description: "Welcome signs, seating charts, table numbers", sort_order: 5 },
  { slug: "florals", label: "Floral & Greenery", emoji: "🌿", description: "Artificial flowers, garlands, dried arrangements", sort_order: 6 },
  { slug: "tableware", label: "Tableware & Linens", emoji: "🍽️", description: "Charger plates, napkins, table runners, linens", sort_order: 7 },
  { slug: "lighting", label: "Lighting & Candles", emoji: "🕯️", description: "String lights, candle holders, lanterns, LED", sort_order: 8 },
  { slug: "stationery", label: "Stationery & Paper", emoji: "✉️", description: "Unused invitations, programs, menus, escort cards", sort_order: 9 },
  { slug: "favors", label: "Favors & Gifts", emoji: "🎁", description: "Unused favors, gift bags, boxes", sort_order: 10 },
  { slug: "ceremony", label: "Ceremony Items", emoji: "🙏", description: "Kalash, coconuts, ceremony supplies, wedding arch", sort_order: 11 },
  { slug: "photo_props", label: "Photo Props & Booth", emoji: "📸", description: "Photo booth props, frames, backdrop items", sort_order: 12 },
  { slug: "shoes", label: "Shoes", emoji: "👠", description: "Bridal and groom footwear", sort_order: 13 },
  { slug: "veils_dupattas", label: "Veils & Dupattas", emoji: "🧣", description: "Bridal veils, dupattas, drapes", sort_order: 14 },
  { slug: "miscellaneous", label: "Other", emoji: "✨", description: "Everything else wedding-related", sort_order: 15 },
];

// ── Helper to build listings without excessive boilerplate ─────────────────

const now = new Date("2026-04-22T12:00:00Z");
const iso = (daysAgo: number) =>
  new Date(now.getTime() - daysAgo * 86_400_000).toISOString();
const expiresFrom = (createdIso: string) =>
  new Date(new Date(createdIso).getTime() + 90 * 86_400_000).toISOString();

interface ListingDraft extends Omit<MarketplaceListing, "expires_at" | "updated_at" | "created_at" | "view_count" | "save_count" | "inquiry_count"> {
  days_ago: number;
  views?: number;
  saves?: number;
  inquiries?: number;
}

function build(d: ListingDraft): MarketplaceListing {
  const created = iso(d.days_ago);
  const { days_ago: _days, views, saves, inquiries, ...rest } = d;
  return {
    ...rest,
    view_count: views ?? 0,
    save_count: saves ?? 0,
    inquiry_count: inquiries ?? 0,
    created_at: created,
    updated_at: created,
    expires_at: expiresFrom(created),
  };
}

// ── Gradient palette for image placeholders ─────────────────────────────────

const GRADIENTS = {
  red: "linear-gradient(135deg, #8B2635 0%, #C83E4D 40%, #E8A598 100%)",
  gold: "linear-gradient(135deg, #B8860B 0%, #D4A843 50%, #F0E4C8 100%)",
  rose: "linear-gradient(135deg, #C97B63 0%, #E8A598 50%, #F5E0D3 100%)",
  teal: "linear-gradient(135deg, #2C5F5D 0%, #4A8D89 50%, #A8CFCC 100%)",
  ivory: "linear-gradient(135deg, #E8DCC4 0%, #F0E4C8 50%, #F8F3E8 100%)",
  mauve: "linear-gradient(135deg, #6B4C6E 0%, #A188A8 50%, #D9C8DC 100%)",
  sage: "linear-gradient(135deg, #5B7553 0%, #8DA886 50%, #CDD9C5 100%)",
  sunset: "linear-gradient(135deg, #C9452E 0%, #D4A843 50%, #F0E4C8 100%)",
  pink: "linear-gradient(135deg, #D2789C 0%, #E8B0C7 50%, #F6DCE8 100%)",
  green: "linear-gradient(135deg, #3B5D4E 0%, #7BA289 50%, #C7D9CD 100%)",
};

const g = (k: keyof typeof GRADIENTS, count = 3) =>
  Array.from({ length: count }, () => GRADIENTS[k]);

// ── Seller profiles (reused across listings) ────────────────────────────────

const SELLERS = {
  priya: {
    seller_id: "seller-priya",
    seller_display_name: "Priya",
    seller_avatar_gradient: GRADIENTS.rose,
    seller_city: "Mumbai",
    seller_state: "Maharashtra",
    seller_bio: "Married November 2026 — now helping other brides find beautiful pieces at real prices.",
    seller_member_since: "2025-10-15",
    seller_items_listed: 4,
    seller_items_sold: 2,
    seller_typical_response: "within a few hours",
    seller_is_verified: true,
  },
  ananya: {
    seller_id: "seller-ananya",
    seller_display_name: "Ananya",
    seller_avatar_gradient: GRADIENTS.gold,
    seller_city: "Delhi",
    seller_state: "Delhi",
    seller_bio: "My wedding was magical — hoping these pieces can be part of someone else's magic too.",
    seller_member_since: "2025-08-02",
    seller_items_listed: 5,
    seller_items_sold: 3,
    seller_typical_response: "same day",
    seller_is_verified: true,
  },
  riya: {
    seller_id: "seller-riya",
    seller_display_name: "Riya",
    seller_avatar_gradient: GRADIENTS.mauve,
    seller_city: "Dallas",
    seller_state: "TX",
    seller_bio: "Diaspora bride · planned a destination wedding in Udaipur. Lots of gorgeous pieces looking for new homes.",
    seller_member_since: "2026-01-20",
    seller_items_listed: 6,
    seller_items_sold: 1,
    seller_typical_response: "within a day",
    seller_is_verified: true,
  },
  meera: {
    seller_id: "seller-meera",
    seller_display_name: "Meera",
    seller_avatar_gradient: GRADIENTS.teal,
    seller_city: "Bangalore",
    seller_state: "Karnataka",
    seller_bio: "South Indian wedding, March 2026. Happy to answer any questions before you buy.",
    seller_member_since: "2025-11-05",
    seller_items_listed: 3,
    seller_is_verified: true,
    seller_items_sold: 1,
    seller_typical_response: "within a few hours",
  },
  tanvi: {
    seller_id: "seller-tanvi",
    seller_display_name: "Tanvi",
    seller_avatar_gradient: GRADIENTS.sage,
    seller_city: "Houston",
    seller_state: "TX",
    seller_bio: "Small backyard wedding, Feb 2026. Everything is in great condition — just don't need two of everything.",
    seller_member_since: "2025-09-12",
    seller_items_listed: 8,
    seller_items_sold: 4,
    seller_typical_response: "within a day",
    seller_is_verified: true,
  },
  nikita: {
    seller_id: "seller-nikita",
    seller_display_name: "Nikita",
    seller_avatar_gradient: GRADIENTS.pink,
    seller_city: "Pune",
    seller_state: "Maharashtra",
    seller_bio: "Rented out my sangeet outfit twice and it's still beautiful — happy to keep it going.",
    seller_member_since: "2025-07-20",
    seller_items_listed: 2,
    seller_items_sold: 0,
    seller_typical_response: "within a few hours",
    seller_is_verified: false,
  },
  kavya: {
    seller_id: "seller-kavya",
    seller_display_name: "Kavya",
    seller_avatar_gradient: GRADIENTS.sunset,
    seller_city: "Chennai",
    seller_state: "Tamil Nadu",
    seller_bio: "Selling curated pieces from my wedding. All items are in excellent condition.",
    seller_member_since: "2025-12-01",
    seller_items_listed: 7,
    seller_items_sold: 2,
    seller_typical_response: "same day",
    seller_is_verified: true,
  },
};

// ── Listings ────────────────────────────────────────────────────────────────

export const SEED_LISTINGS: MarketplaceListing[] = [
  build({
    id: "lst-red-lehenga-sabya",
    ...SELLERS.priya,
    title: "Sabyasachi-inspired red bridal lehenga",
    description:
      "This is a custom-made bridal lehenga in Sabyasachi's signature style — deep red raw silk with hand-embroidered zardozi work. It was made by a master craftsman in Jaipur and took 6 weeks to create.\n\nIncludes: lehenga skirt, unstitched blouse fabric (enough for two blouses), and matching dupatta with gold border.\n\nMeasurements: Waist 28\", Length 42\" (can be altered), Dupatta 2.5m. Weight: approximately 5kg.\n\nI had it dry cleaned professionally after the wedding and it's been in a garment bag since. No stains, no damage. Happy to send more photos or do a video call to show it.",
    category: "bridal_wear",
    subcategory: "lehenga",
    tags: ["bridal", "lehenga", "red", "zardozi", "raw silk", "custom"],
    listing_type: "sell",
    price_cents: 45_000_00,
    original_price_cents: 2_80_000_00,
    price_is_negotiable: true,
    condition: "like_new",
    times_used: 1,
    size: "M",
    color: "Red / Gold",
    brand: "Custom (Sabyasachi inspired)",
    purchase_year: 2026,
    seller_location_city: "Mumbai",
    seller_location_state: "Maharashtra",
    seller_location_country: "India",
    shipping_available: true,
    local_pickup: true,
    shipping_notes: "Buyer pays shipping. I'll use a tracked courier.",
    images: [],
    image_gradients: g("red", 5),
    status: "active",
    days_ago: 5,
    views: 142,
    saves: 8,
    inquiries: 3,
  }),
  build({
    id: "lst-gold-kundan-set",
    ...SELLERS.ananya,
    title: "Bridal gold kundan necklace set with earrings & maang tikka",
    description:
      "Complete bridal set — heavy kundan work with pearl drops. Gold plating over brass, not real gold.\n\nIncludes: long necklace (32\" drop), matching earrings, and maang tikka. Comes in original presentation box.\n\nWorn only at my reception. Some minor oxidation on the back of the necklace which is completely hidden when worn. Open to both sale and rental.",
    category: "jewelry",
    subcategory: "bridal_set",
    tags: ["jewelry", "kundan", "bridal set", "maang tikka", "earrings"],
    listing_type: "sell_or_rent",
    price_cents: 12_000_00,
    original_price_cents: 28_500_00,
    price_is_negotiable: true,
    rental_deposit_cents: 10_000_00,
    rental_duration_days: 5,
    condition: "like_new",
    times_used: 1,
    color: "Gold / Pearl",
    brand: "Tanishq",
    purchase_year: 2025,
    seller_location_city: "Delhi",
    seller_location_state: "Delhi",
    seller_location_country: "India",
    shipping_available: true,
    local_pickup: true,
    shipping_notes: "Insured shipping only for jewelry — buyer pays.",
    images: [],
    image_gradients: g("gold", 4),
    status: "active",
    days_ago: 3,
    views: 89,
    saves: 4,
    inquiries: 1,
  }),
  build({
    id: "lst-acrylic-welcome-sign",
    ...SELLERS.riya,
    title: "Custom acrylic welcome sign — no names, reusable",
    description:
      "Beautiful clear acrylic welcome sign with gold vinyl lettering — design is generic (\"welcome to our wedding\") so it's fully reusable for any couple.\n\n24\" x 36\". Includes wooden easel stand. I hand-scored a little scratch on the back corner that nobody will ever see.",
    category: "signage",
    tags: ["signage", "welcome sign", "acrylic", "easel"],
    listing_type: "sell",
    price_cents: 2500_00,
    original_price_cents: 12_000_00,
    price_is_negotiable: false,
    condition: "like_new",
    times_used: 1,
    color: "Clear / Gold",
    purchase_year: 2026,
    seller_location_city: "Dallas",
    seller_location_state: "TX",
    seller_location_country: "USA",
    shipping_available: true,
    local_pickup: true,
    shipping_notes: "Ships in a padded box. $25 flat within the US.",
    images: [],
    image_gradients: g("ivory", 3),
    status: "active",
    days_ago: 7,
    views: 56,
    saves: 6,
    inquiries: 2,
  }),
  build({
    id: "lst-centerpiece-vases",
    ...SELLERS.tanvi,
    title: "Centerpiece vases (set of 12) — FREE",
    description:
      "Giving these away — 12 matching ceramic vases, used at our reception for low centerpieces. They're in good shape, a couple have small nicks along the rim but nothing visible when flowers are in them.\n\nLocal pickup only (Houston area). First-come-first-served.",
    category: "decor",
    subcategory: "centerpieces",
    tags: ["centerpieces", "vases", "ceramic", "free"],
    listing_type: "free",
    price_is_negotiable: false,
    condition: "good",
    times_used: 1,
    color: "Ivory",
    purchase_year: 2025,
    seller_location_city: "Houston",
    seller_location_state: "TX",
    seller_location_country: "USA",
    shipping_available: false,
    local_pickup: true,
    shipping_notes: "Local pickup only, please.",
    images: [],
    image_gradients: g("ivory", 2),
    status: "active",
    days_ago: 2,
    views: 78,
    saves: 12,
    inquiries: 5,
  }),
  build({
    id: "lst-sherwani-ivory",
    ...SELLERS.meera,
    title: "Ivory silk sherwani with gold embroidery",
    description:
      "Hand-embroidered ivory silk sherwani, custom-made in Bangalore. Worn once for the wedding reception. Includes matching churidar pants and a gold silk dupatta.\n\nChest 42\", comfortable fit. Can be altered. Dry cleaned and stored in garment bag.",
    category: "groom_wear",
    subcategory: "sherwani",
    tags: ["groom", "sherwani", "ivory", "silk", "embroidery"],
    listing_type: "rent",
    price_cents: 8_000_00,
    rental_deposit_cents: 20_000_00,
    rental_duration_days: 7,
    price_is_negotiable: true,
    condition: "like_new",
    times_used: 1,
    size: "L (42\" chest)",
    color: "Ivory / Gold",
    brand: "Custom — Manyavar inspired",
    purchase_year: 2026,
    seller_location_city: "Bangalore",
    seller_location_state: "Karnataka",
    seller_location_country: "India",
    shipping_available: true,
    local_pickup: true,
    shipping_notes: "Rental only. Security deposit refundable on return.",
    images: [],
    image_gradients: g("ivory", 4),
    status: "active",
    days_ago: 10,
    views: 112,
    saves: 9,
    inquiries: 4,
  }),
  build({
    id: "lst-mandap-drape-set",
    ...SELLERS.ananya,
    title: "Mandap drape set — deep pink & gold (4 panels)",
    description:
      "4 large fabric panels used to drape our mandap. Rich deep pink silk with metallic gold border. Each panel is approximately 15ft x 5ft.\n\nNo visible wear. Can be steamed and re-used easily. Selling as a set of 4.\n\nWould work beautifully for a pheras mandap or as photo booth backdrop.",
    category: "decor",
    subcategory: "mandap_decor",
    tags: ["mandap", "drape", "pink", "gold", "fabric", "décor"],
    listing_type: "sell_or_rent",
    price_cents: 18_000_00,
    original_price_cents: 65_000_00,
    rental_deposit_cents: 15_000_00,
    rental_duration_days: 5,
    price_is_negotiable: true,
    condition: "like_new",
    times_used: 1,
    color: "Deep pink / Gold",
    purchase_year: 2025,
    seller_location_city: "Delhi",
    seller_location_state: "Delhi",
    seller_location_country: "India",
    shipping_available: false,
    local_pickup: true,
    shipping_notes: "Local pickup or short-distance delivery within Delhi NCR.",
    images: [],
    image_gradients: g("pink", 4),
    status: "active",
    days_ago: 12,
    views: 94,
    saves: 7,
    inquiries: 2,
  }),
  build({
    id: "lst-kalire-silver",
    ...SELLERS.priya,
    title: "Silver & pearl kalire — custom, never worn",
    description:
      "Custom-made kalire (the traditional hanging ornaments for a bride's chura). Ordered two sets for my wedding and only used one. These are brand new, still with tags.\n\nSilver-plated with pearl drops and tiny bells. Very detailed work.",
    category: "jewelry",
    tags: ["kalire", "bridal", "silver", "pearl", "new with tags"],
    listing_type: "sell",
    price_cents: 3500_00,
    original_price_cents: 7_500_00,
    price_is_negotiable: true,
    condition: "new_with_tags",
    times_used: 0,
    color: "Silver / Pearl",
    purchase_year: 2026,
    seller_location_city: "Mumbai",
    seller_location_state: "Maharashtra",
    seller_location_country: "India",
    shipping_available: true,
    local_pickup: true,
    images: [],
    image_gradients: g("ivory", 3),
    status: "active",
    days_ago: 1,
    views: 22,
    saves: 2,
    inquiries: 0,
  }),
  build({
    id: "lst-sangeet-lehenga",
    ...SELLERS.nikita,
    title: "Sangeet lehenga — mint green & silver, available to rent",
    description:
      "Stunning mint green georgette lehenga with silver mirror work and thread embroidery. I've rented it out twice already and it's still in beautiful condition — happy to keep it going for other brides' sangeets.\n\nSize M, waist 28-30\" (has adjustable drawstring). Includes blouse and dupatta.",
    category: "bridal_wear",
    subcategory: "sangeet_outfit",
    tags: ["sangeet", "lehenga", "mint", "silver", "mirror work"],
    listing_type: "rent",
    price_cents: 6_500_00,
    rental_deposit_cents: 18_000_00,
    rental_duration_days: 5,
    price_is_negotiable: true,
    condition: "good",
    times_used: 3,
    size: "M (28-30\" waist, adjustable)",
    color: "Mint green / Silver",
    brand: "Anita Dongre",
    purchase_year: 2025,
    seller_location_city: "Pune",
    seller_location_state: "Maharashtra",
    seller_location_country: "India",
    shipping_available: true,
    local_pickup: true,
    shipping_notes: "Rental fee includes dry cleaning after return.",
    images: [],
    image_gradients: g("sage", 4),
    status: "active",
    days_ago: 15,
    views: 203,
    saves: 18,
    inquiries: 7,
  }),
  build({
    id: "lst-photo-booth-props",
    ...SELLERS.tanvi,
    title: "Photo booth props + printed backdrop — 30+ pieces",
    description:
      "Everything from our photo booth — Indian-themed mustaches, sunglasses, signs (\"bride squad\", \"groom squad\", \"just married\"), flower crowns, and a 8x8ft printed backdrop with gold paisleys on ivory.\n\nAll in good shape. Comes in a plastic tote for easy transport.",
    category: "photo_props",
    tags: ["photo booth", "props", "backdrop", "bundle"],
    listing_type: "sell",
    price_cents: 4500_00,
    original_price_cents: 15_000_00,
    price_is_negotiable: true,
    condition: "good",
    times_used: 1,
    purchase_year: 2025,
    seller_location_city: "Houston",
    seller_location_state: "TX",
    seller_location_country: "USA",
    shipping_available: true,
    local_pickup: true,
    shipping_notes: "Backdrop ships separately — heavy. Flat $40 US shipping for the whole bundle.",
    images: [],
    image_gradients: g("sunset", 3),
    status: "active",
    days_ago: 20,
    views: 134,
    saves: 11,
    inquiries: 3,
  }),
  build({
    id: "lst-string-lights-bulk",
    ...SELLERS.kavya,
    title: "Warm white string lights — 500 ft bulk (10 strands)",
    description:
      "10 strands of 50ft commercial-grade warm white string lights. We used these for our outdoor reception — still working perfectly. Plug-in, not battery.\n\nSelling all 10 together. Bulbs are replaceable (I have 20 spare bulbs I'll throw in).",
    category: "lighting",
    tags: ["string lights", "warm white", "bulk", "outdoor"],
    listing_type: "sell",
    price_cents: 3200_00,
    original_price_cents: 8_500_00,
    price_is_negotiable: true,
    condition: "like_new",
    times_used: 1,
    color: "Warm white",
    purchase_year: 2025,
    seller_location_city: "Chennai",
    seller_location_state: "Tamil Nadu",
    seller_location_country: "India",
    shipping_available: false,
    local_pickup: true,
    shipping_notes: "Local pickup only — too heavy/bulky to ship economically.",
    images: [],
    image_gradients: g("gold", 3),
    status: "active",
    days_ago: 8,
    views: 67,
    saves: 5,
    inquiries: 1,
  }),
  build({
    id: "lst-bridal-veil-ivory",
    ...SELLERS.riya,
    title: "Cathedral-length ivory bridal veil with lace edge",
    description:
      "120\" cathedral length ivory veil with intricate French lace edging. Worn once. No stains, no tears.\n\nIncludes a small ornate comb for attachment. Perfect condition.",
    category: "veils_dupattas",
    tags: ["veil", "ivory", "lace", "cathedral length"],
    listing_type: "sell",
    price_cents: 8500_00,
    original_price_cents: 32_000_00,
    price_is_negotiable: true,
    condition: "like_new",
    times_used: 1,
    color: "Ivory",
    purchase_year: 2026,
    seller_location_city: "Dallas",
    seller_location_state: "TX",
    seller_location_country: "USA",
    shipping_available: true,
    local_pickup: true,
    shipping_notes: "Ships carefully folded with tissue. $20 within US.",
    images: [],
    image_gradients: g("ivory", 3),
    status: "active",
    days_ago: 4,
    views: 88,
    saves: 14,
    inquiries: 3,
  }),
  build({
    id: "lst-kurta-set-groom",
    ...SELLERS.meera,
    title: "Groom kurta set — mehendi ceremony outfit",
    description:
      "Yellow cotton silk kurta set with green embroidery — worn at the mehendi ceremony. Includes matching churidar and dupatta.\n\nSize L. Very comfortable, breathable cotton silk blend.",
    category: "groom_wear",
    subcategory: "kurta_set",
    tags: ["groom", "kurta", "mehendi", "yellow"],
    listing_type: "sell",
    price_cents: 3200_00,
    original_price_cents: 9_500_00,
    price_is_negotiable: true,
    condition: "like_new",
    times_used: 1,
    size: "L",
    color: "Yellow / Green",
    brand: "FabIndia",
    purchase_year: 2026,
    seller_location_city: "Bangalore",
    seller_location_state: "Karnataka",
    seller_location_country: "India",
    shipping_available: true,
    local_pickup: true,
    images: [],
    image_gradients: g("sunset", 3),
    status: "active",
    days_ago: 6,
    views: 45,
    saves: 3,
    inquiries: 1,
  }),
  build({
    id: "lst-charger-plates",
    ...SELLERS.tanvi,
    title: "Gold rim charger plates — set of 150",
    description:
      "150 gold-rimmed clear acrylic charger plates. Beautiful on any tablescape. A few have minor scratches from stacking but nothing visible once plated.\n\nLocal pickup only due to weight. Priced to move.",
    category: "tableware",
    tags: ["charger plates", "gold rim", "tableware", "bulk"],
    listing_type: "sell",
    price_cents: 15_000_00,
    original_price_cents: 45_000_00,
    price_is_negotiable: true,
    condition: "good",
    times_used: 1,
    color: "Clear / Gold",
    purchase_year: 2025,
    seller_location_city: "Houston",
    seller_location_state: "TX",
    seller_location_country: "USA",
    shipping_available: false,
    local_pickup: true,
    shipping_notes: "150 plates — local pickup essential.",
    images: [],
    image_gradients: g("gold", 2),
    status: "active",
    days_ago: 18,
    views: 102,
    saves: 9,
    inquiries: 4,
  }),
  build({
    id: "lst-reception-gown",
    ...SELLERS.kavya,
    title: "Champagne reception gown — floor length, custom",
    description:
      "Floor-length champagne gown custom-made for my reception. Thousands of tiny bugle beads hand-sewn onto the bodice, chiffon skirt with gold underlay.\n\nSize S/M, fits 32-34 bust, 26-28 waist. Has a small train. Worn for a 4-hour reception.",
    category: "bridal_wear",
    subcategory: "reception_outfit",
    tags: ["reception", "gown", "champagne", "beaded", "custom"],
    listing_type: "sell",
    price_cents: 28_000_00,
    original_price_cents: 1_20_000_00,
    price_is_negotiable: true,
    condition: "like_new",
    times_used: 1,
    size: "S/M (32-34 bust)",
    color: "Champagne / Gold",
    brand: "Custom — Shantanu & Nikhil inspired",
    purchase_year: 2026,
    seller_location_city: "Chennai",
    seller_location_state: "Tamil Nadu",
    seller_location_country: "India",
    shipping_available: true,
    local_pickup: true,
    shipping_notes: "International shipping available — DHL, buyer pays.",
    images: [],
    image_gradients: g("gold", 4),
    status: "active",
    days_ago: 9,
    views: 167,
    saves: 22,
    inquiries: 6,
  }),
  build({
    id: "lst-heels-bridal",
    ...SELLERS.ananya,
    title: "Bridal heels — embellished, worn once",
    description:
      "Ivory satin heels with crystal embellishment. 3.5\" heel. Only worn during the ceremony (about 2 hours total).\n\nSize 7 US / 37.5 EU. Comes with original box and dust bag.",
    category: "shoes",
    tags: ["shoes", "heels", "bridal", "ivory", "crystal"],
    listing_type: "sell",
    price_cents: 4500_00,
    original_price_cents: 14_000_00,
    price_is_negotiable: true,
    condition: "like_new",
    times_used: 1,
    size: "US 7 / EU 37.5",
    color: "Ivory / Crystal",
    brand: "Badgley Mischka",
    purchase_year: 2025,
    seller_location_city: "Delhi",
    seller_location_state: "Delhi",
    seller_location_country: "India",
    shipping_available: true,
    local_pickup: true,
    images: [],
    image_gradients: g("ivory", 3),
    status: "active",
    days_ago: 11,
    views: 76,
    saves: 5,
    inquiries: 2,
  }),
];
