// Seed data for The Legacy Castle's venue vendor network — vendors and planners
// who have worked at this property, their frequency, and preferred-vendor
// designations. Mirrors the tone of lib/venue/seed.ts.

export type VenueVendorCategoryId =
  | "photography"
  | "decor"
  | "catering"
  | "hmua"
  | "dj"
  | "entertainment"
  | "mehndi"
  | "lighting"
  | "stationery"
  | "transportation"
  | "photo-booth"
  | "priest";

export type VenueVendorCategory = {
  id: VenueVendorCategoryId;
  label: string;
  icon: string;
  total: number; // total vendors in category (some may not be listed below)
  maxPreferred?: number; // cap for preferred designations per category
};

export type VenueVendor = {
  id: string;
  categoryId: VenueVendorCategoryId;
  name: string;
  initials: string;
  tint: string; // background tint for avatar
  rating: number;
  weddingsHere: number;
  lastWeddingLabel: string;
  lastWeddingSort: string; // ISO-ish for sort
  priceRange: string;
  preferred: boolean;
  venueNote?: string;
  ananyaSelect?: boolean;
  verified?: boolean;
  destination?: boolean;
};

export type VenuePlanner = {
  id: string;
  name: string;
  lead?: string;
  initials: string;
  tint: string;
  weddingsHere: number;
  rating: number;
  city: string;
  services: string;
};

// ---- Categories -------------------------------------------------------------

export const VENDOR_CATEGORIES: VenueVendorCategory[] = [
  { id: "photography", label: "Photography", icon: "📷", total: 12, maxPreferred: 2 },
  { id: "decor", label: "Decor & Florals", icon: "🎨", total: 8, maxPreferred: 2 },
  { id: "catering", label: "Catering", icon: "🍽", total: 6, maxPreferred: 2 },
  { id: "hmua", label: "HMUA", icon: "💄", total: 9, maxPreferred: 2 },
  { id: "dj", label: "DJ", icon: "🎧", total: 5, maxPreferred: 1 },
  { id: "entertainment", label: "Entertainment", icon: "🎤", total: 4, maxPreferred: 1 },
  { id: "mehndi", label: "Mehndi", icon: "✋", total: 6, maxPreferred: 1 },
  { id: "lighting", label: "Lighting", icon: "✨", total: 4, maxPreferred: 1 },
  { id: "stationery", label: "Stationery", icon: "✉", total: 3, maxPreferred: 1 },
  { id: "transportation", label: "Transportation", icon: "🚗", total: 4, maxPreferred: 1 },
  { id: "photo-booth", label: "Photo Booth", icon: "📸", total: 3, maxPreferred: 1 },
  { id: "priest", label: "Priest", icon: "🕉", total: 3, maxPreferred: 1 },
];

// Palette of tints for vendor avatars, rotated deterministically.
const TINTS = [
  "#F5E6D0",
  "#E8D5D0",
  "#EADBC4",
  "#F2E3D7",
  "#E3D5E8",
  "#DCE5D8",
  "#F4E4C1",
  "#EEDAD0",
];

function tintFor(i: number) {
  return TINTS[i % TINTS.length];
}

// ---- Vendors ----------------------------------------------------------------

export const VENUE_VENDORS: VenueVendor[] = [
  // Photography (12) — 2 preferred
  {
    id: "joseph-radhik",
    categoryId: "photography",
    name: "Stories by Joseph Radhik",
    initials: "JR",
    tint: tintFor(0),
    rating: 4.9,
    weddingsHere: 8,
    lastWeddingLabel: "Oct 2025",
    lastWeddingSort: "2025-10-01",
    priceRange: "$12K–$25K",
    preferred: true,
    venueNote:
      "Our top choice for large Hindu weddings — knows every angle of the Grand Ballroom.",
    ananyaSelect: true,
    verified: true,
  },
  {
    id: "wedding-salad",
    categoryId: "photography",
    name: "The Wedding Salad",
    initials: "WS",
    tint: tintFor(1),
    rating: 4.8,
    weddingsHere: 5,
    lastWeddingLabel: "Sep 2025",
    lastWeddingSort: "2025-09-01",
    priceRange: "$6K–$14K",
    preferred: true,
    venueNote: "Warm editorial style that reads beautifully in our Garden Terrace light.",
    verified: true,
  },
  {
    id: "dot-dusk",
    categoryId: "photography",
    name: "Dot Dusk",
    initials: "DD",
    tint: tintFor(2),
    rating: 4.7,
    weddingsHere: 3,
    lastWeddingLabel: "Aug 2025",
    lastWeddingSort: "2025-08-01",
    priceRange: "$3K–$8K",
    preferred: false,
  },
  {
    id: "knotting-bells",
    categoryId: "photography",
    name: "Knotting Bells",
    initials: "KB",
    tint: tintFor(3),
    rating: 4.7,
    weddingsHere: 3,
    lastWeddingLabel: "Jul 2025",
    lastWeddingSort: "2025-07-01",
    priceRange: "$4K–$10K",
    preferred: false,
  },
  {
    id: "into-candid",
    categoryId: "photography",
    name: "Into Candid",
    initials: "IC",
    tint: tintFor(4),
    rating: 4.6,
    weddingsHere: 2,
    lastWeddingLabel: "Jun 2025",
    lastWeddingSort: "2025-06-01",
    priceRange: "$5K–$12K",
    preferred: false,
    verified: true,
  },
  {
    id: "happy-frog",
    categoryId: "photography",
    name: "Happy Frog Studios",
    initials: "HF",
    tint: tintFor(5),
    rating: 4.6,
    weddingsHere: 2,
    lastWeddingLabel: "May 2025",
    lastWeddingSort: "2025-05-01",
    priceRange: "$3K–$7K",
    preferred: false,
  },
  {
    id: "mahatta-films",
    categoryId: "photography",
    name: "Mahatta Films",
    initials: "MF",
    tint: tintFor(6),
    rating: 4.8,
    weddingsHere: 2,
    lastWeddingLabel: "Apr 2025",
    lastWeddingSort: "2025-04-01",
    priceRange: "$8K–$18K",
    preferred: false,
  },
  {
    id: "photo-tantra",
    categoryId: "photography",
    name: "Photo Tantra",
    initials: "PT",
    tint: tintFor(7),
    rating: 4.5,
    weddingsHere: 2,
    lastWeddingLabel: "Mar 2025",
    lastWeddingSort: "2025-03-01",
    priceRange: "$4K–$9K",
    preferred: false,
  },
  {
    id: "weva-photography",
    categoryId: "photography",
    name: "Weva Photography",
    initials: "WP",
    tint: tintFor(0),
    rating: 4.7,
    weddingsHere: 2,
    lastWeddingLabel: "Feb 2025",
    lastWeddingSort: "2025-02-01",
    priceRange: "$6K–$14K",
    preferred: false,
    destination: true,
  },
  {
    id: "golden-hour",
    categoryId: "photography",
    name: "Golden Hour Co",
    initials: "GH",
    tint: tintFor(1),
    rating: 4.5,
    weddingsHere: 1,
    lastWeddingLabel: "Jan 2025",
    lastWeddingSort: "2025-01-01",
    priceRange: "$3K–$6K",
    preferred: false,
  },
  {
    id: "inkuba-films",
    categoryId: "photography",
    name: "Inkuba Films",
    initials: "IF",
    tint: tintFor(2),
    rating: 4.6,
    weddingsHere: 1,
    lastWeddingLabel: "Nov 2024",
    lastWeddingSort: "2024-11-01",
    priceRange: "$4K–$8K",
    preferred: false,
    verified: true,
  },
  {
    id: "candid-shutters",
    categoryId: "photography",
    name: "Candid Shutters",
    initials: "CS",
    tint: tintFor(3),
    rating: 4.4,
    weddingsHere: 1,
    lastWeddingLabel: "Oct 2024",
    lastWeddingSort: "2024-10-01",
    priceRange: "$2K–$5K",
    preferred: false,
  },

  // Decor & Florals (8) — 2 preferred
  {
    id: "elan-events",
    categoryId: "decor",
    name: "Elan Events",
    initials: "EE",
    tint: tintFor(0),
    rating: 4.9,
    weddingsHere: 6,
    lastWeddingLabel: "Oct 2025",
    lastWeddingSort: "2025-10-02",
    priceRange: "$25K–$60K",
    preferred: true,
    venueNote: "Scale-sensitive designs that fill the Grand Ballroom without overwhelming it.",
    ananyaSelect: true,
    verified: true,
  },
  {
    id: "floral-artistry",
    categoryId: "decor",
    name: "Floral Artistry NJ",
    initials: "FA",
    tint: tintFor(1),
    rating: 4.8,
    weddingsHere: 4,
    lastWeddingLabel: "Sep 2025",
    lastWeddingSort: "2025-09-02",
    priceRange: "$15K–$40K",
    preferred: true,
    venueNote: "Consistently on-time load-ins; our ops team loves working with them.",
    verified: true,
  },
  {
    id: "the-wedding-designers",
    categoryId: "decor",
    name: "The Wedding Designers",
    initials: "TD",
    tint: tintFor(2),
    rating: 4.7,
    weddingsHere: 3,
    lastWeddingLabel: "Aug 2025",
    lastWeddingSort: "2025-08-02",
    priceRange: "$10K–$28K",
    preferred: false,
  },
  {
    id: "bluebell-events",
    categoryId: "decor",
    name: "Bluebell Events",
    initials: "BE",
    tint: tintFor(3),
    rating: 4.7,
    weddingsHere: 2,
    lastWeddingLabel: "Jul 2025",
    lastWeddingSort: "2025-07-02",
    priceRange: "$8K–$22K",
    preferred: false,
  },
  {
    id: "marigold-studio",
    categoryId: "decor",
    name: "Marigold Studio",
    initials: "MS",
    tint: tintFor(4),
    rating: 4.6,
    weddingsHere: 2,
    lastWeddingLabel: "May 2025",
    lastWeddingSort: "2025-05-02",
    priceRange: "$9K–$25K",
    preferred: false,
    verified: true,
  },
  {
    id: "petals-silk",
    categoryId: "decor",
    name: "Petals & Silk",
    initials: "PS",
    tint: tintFor(5),
    rating: 4.5,
    weddingsHere: 1,
    lastWeddingLabel: "Apr 2025",
    lastWeddingSort: "2025-04-02",
    priceRange: "$6K–$15K",
    preferred: false,
  },
  {
    id: "saffron-decor",
    categoryId: "decor",
    name: "Saffron Decor",
    initials: "SD",
    tint: tintFor(6),
    rating: 4.5,
    weddingsHere: 1,
    lastWeddingLabel: "Mar 2025",
    lastWeddingSort: "2025-03-02",
    priceRange: "$7K–$18K",
    preferred: false,
  },
  {
    id: "orchid-atelier",
    categoryId: "decor",
    name: "Orchid Atelier",
    initials: "OA",
    tint: tintFor(7),
    rating: 4.6,
    weddingsHere: 1,
    lastWeddingLabel: "Feb 2025",
    lastWeddingSort: "2025-02-02",
    priceRange: "$10K–$24K",
    preferred: false,
  },

  // Catering (6) — 2 preferred
  {
    id: "royal-india-catering",
    categoryId: "catering",
    name: "Royal India Catering",
    initials: "RI",
    tint: tintFor(0),
    rating: 4.8,
    weddingsHere: 7,
    lastWeddingLabel: "Oct 2025",
    lastWeddingSort: "2025-10-03",
    priceRange: "$85–$165 / pp",
    preferred: true,
    venueNote: "Handles 400+ guest menus without missing a service window in our kitchen.",
    verified: true,
  },
  {
    id: "saffron-sons",
    categoryId: "catering",
    name: "Saffron & Sons",
    initials: "SS",
    tint: tintFor(1),
    rating: 4.8,
    weddingsHere: 5,
    lastWeddingLabel: "Sep 2025",
    lastWeddingSort: "2025-09-03",
    priceRange: "$95–$180 / pp",
    preferred: true,
    venueNote: "Best regional menus in the NJ/NY market; strong Jain/vegetarian depth.",
  },
  {
    id: "tandoor-nj",
    categoryId: "catering",
    name: "Tandoor NJ",
    initials: "TN",
    tint: tintFor(2),
    rating: 4.6,
    weddingsHere: 3,
    lastWeddingLabel: "Aug 2025",
    lastWeddingSort: "2025-08-03",
    priceRange: "$70–$140 / pp",
    preferred: false,
  },
  {
    id: "biryani-house",
    categoryId: "catering",
    name: "Biryani House Events",
    initials: "BH",
    tint: tintFor(3),
    rating: 4.5,
    weddingsHere: 2,
    lastWeddingLabel: "Jun 2025",
    lastWeddingSort: "2025-06-03",
    priceRange: "$65–$130 / pp",
    preferred: false,
  },
  {
    id: "spice-route",
    categoryId: "catering",
    name: "Spice Route Catering",
    initials: "SR",
    tint: tintFor(4),
    rating: 4.7,
    weddingsHere: 2,
    lastWeddingLabel: "May 2025",
    lastWeddingSort: "2025-05-03",
    priceRange: "$110–$200 / pp",
    preferred: false,
    destination: true,
  },
  {
    id: "bombay-kitchen",
    categoryId: "catering",
    name: "The Bombay Kitchen",
    initials: "BK",
    tint: tintFor(5),
    rating: 4.4,
    weddingsHere: 1,
    lastWeddingLabel: "Mar 2025",
    lastWeddingSort: "2025-03-03",
    priceRange: "$55–$115 / pp",
    preferred: false,
  },

  // HMUA (9) — 2 preferred
  {
    id: "namrata-soni",
    categoryId: "hmua",
    name: "Namrata Soni Studio",
    initials: "NS",
    tint: tintFor(0),
    rating: 4.9,
    weddingsHere: 6,
    lastWeddingLabel: "Oct 2025",
    lastWeddingSort: "2025-10-04",
    priceRange: "$2.5K–$6K",
    preferred: true,
    venueNote: "Knows our bridal suite lighting cold. Never runs over.",
    ananyaSelect: true,
    verified: true,
  },
  {
    id: "beauty-by-payal",
    categoryId: "hmua",
    name: "Beauty by Payal",
    initials: "BP",
    tint: tintFor(1),
    rating: 4.8,
    weddingsHere: 4,
    lastWeddingLabel: "Sep 2025",
    lastWeddingSort: "2025-09-04",
    priceRange: "$1.8K–$4K",
    preferred: true,
    venueNote: "Excellent for larger bridal parties with tight morning timelines.",
    verified: true,
  },
  {
    id: "glow-bridal",
    categoryId: "hmua",
    name: "Glow Bridal NJ",
    initials: "GB",
    tint: tintFor(2),
    rating: 4.7,
    weddingsHere: 3,
    lastWeddingLabel: "Aug 2025",
    lastWeddingSort: "2025-08-04",
    priceRange: "$1.2K–$3K",
    preferred: false,
  },
  {
    id: "arti-nayar",
    categoryId: "hmua",
    name: "Arti Nayar Makeup",
    initials: "AN",
    tint: tintFor(3),
    rating: 4.7,
    weddingsHere: 2,
    lastWeddingLabel: "Jul 2025",
    lastWeddingSort: "2025-07-04",
    priceRange: "$2K–$5K",
    preferred: false,
  },
  {
    id: "kiran-artistry",
    categoryId: "hmua",
    name: "Kiran Artistry",
    initials: "KA",
    tint: tintFor(4),
    rating: 4.6,
    weddingsHere: 2,
    lastWeddingLabel: "Jun 2025",
    lastWeddingSort: "2025-06-04",
    priceRange: "$1.5K–$3.5K",
    preferred: false,
    verified: true,
  },
  {
    id: "soft-glow",
    categoryId: "hmua",
    name: "Soft Glow Studio",
    initials: "SG",
    tint: tintFor(5),
    rating: 4.5,
    weddingsHere: 2,
    lastWeddingLabel: "May 2025",
    lastWeddingSort: "2025-05-04",
    priceRange: "$1K–$2.8K",
    preferred: false,
  },
  {
    id: "henna-hue",
    categoryId: "hmua",
    name: "Henna & Hue",
    initials: "HH",
    tint: tintFor(6),
    rating: 4.5,
    weddingsHere: 1,
    lastWeddingLabel: "Apr 2025",
    lastWeddingSort: "2025-04-04",
    priceRange: "$900–$2.2K",
    preferred: false,
  },
  {
    id: "dewy-face",
    categoryId: "hmua",
    name: "The Dewy Face",
    initials: "DF",
    tint: tintFor(7),
    rating: 4.6,
    weddingsHere: 1,
    lastWeddingLabel: "Mar 2025",
    lastWeddingSort: "2025-03-04",
    priceRange: "$1.4K–$3.2K",
    preferred: false,
  },
  {
    id: "luxe-looks",
    categoryId: "hmua",
    name: "Luxe Looks by Sanaa",
    initials: "LL",
    tint: tintFor(0),
    rating: 4.4,
    weddingsHere: 1,
    lastWeddingLabel: "Feb 2025",
    lastWeddingSort: "2025-02-04",
    priceRange: "$1.1K–$2.5K",
    preferred: false,
  },

  // DJ (5) — 1 preferred
  {
    id: "dj-rekha",
    categoryId: "dj",
    name: "DJ Rekha Collective",
    initials: "DR",
    tint: tintFor(0),
    rating: 4.9,
    weddingsHere: 5,
    lastWeddingLabel: "Oct 2025",
    lastWeddingSort: "2025-10-05",
    priceRange: "$3K–$7K",
    preferred: true,
    venueNote: "Our sound team's first call. Reads the room flawlessly.",
    verified: true,
  },
  {
    id: "dj-raina",
    categoryId: "dj",
    name: "DJ Raina",
    initials: "RA",
    tint: tintFor(1),
    rating: 4.8,
    weddingsHere: 3,
    lastWeddingLabel: "Sep 2025",
    lastWeddingSort: "2025-09-05",
    priceRange: "$2.5K–$5.5K",
    preferred: false,
  },
  {
    id: "bollywood-beats",
    categoryId: "dj",
    name: "Bollywood Beats NJ",
    initials: "BB",
    tint: tintFor(2),
    rating: 4.7,
    weddingsHere: 2,
    lastWeddingLabel: "Jul 2025",
    lastWeddingSort: "2025-07-05",
    priceRange: "$2K–$4.5K",
    preferred: false,
  },
  {
    id: "dj-amar",
    categoryId: "dj",
    name: "DJ Amar",
    initials: "AM",
    tint: tintFor(3),
    rating: 4.6,
    weddingsHere: 1,
    lastWeddingLabel: "May 2025",
    lastWeddingSort: "2025-05-05",
    priceRange: "$1.8K–$4K",
    preferred: false,
  },
  {
    id: "soundwave",
    categoryId: "dj",
    name: "Soundwave Collective",
    initials: "SW",
    tint: tintFor(4),
    rating: 4.5,
    weddingsHere: 1,
    lastWeddingLabel: "Mar 2025",
    lastWeddingSort: "2025-03-05",
    priceRange: "$1.5K–$3.5K",
    preferred: false,
  },

  // Entertainment (4) — 0 preferred
  {
    id: "dhol-dhruv",
    categoryId: "entertainment",
    name: "Dhol by Dhruv",
    initials: "DH",
    tint: tintFor(0),
    rating: 4.8,
    weddingsHere: 5,
    lastWeddingLabel: "Oct 2025",
    lastWeddingSort: "2025-10-06",
    priceRange: "$800–$2K",
    preferred: false,
    verified: true,
  },
  {
    id: "bollywood-dance",
    categoryId: "entertainment",
    name: "Bollywood Dance Troupe",
    initials: "BD",
    tint: tintFor(1),
    rating: 4.7,
    weddingsHere: 3,
    lastWeddingLabel: "Sep 2025",
    lastWeddingSort: "2025-09-06",
    priceRange: "$1.5K–$4K",
    preferred: false,
  },
  {
    id: "sax-anoop",
    categoryId: "entertainment",
    name: "Saxophone by Anoop",
    initials: "SA",
    tint: tintFor(2),
    rating: 4.6,
    weddingsHere: 1,
    lastWeddingLabel: "Jun 2025",
    lastWeddingSort: "2025-06-06",
    priceRange: "$500–$1.2K",
    preferred: false,
  },
  {
    id: "sitar-sangeet",
    categoryId: "entertainment",
    name: "Sitar Sangeet Ensemble",
    initials: "SS",
    tint: tintFor(3),
    rating: 4.5,
    weddingsHere: 1,
    lastWeddingLabel: "Mar 2025",
    lastWeddingSort: "2025-03-06",
    priceRange: "$700–$1.6K",
    preferred: false,
  },

  // Mehndi (6) — 1 preferred
  {
    id: "henna-aroosa",
    categoryId: "mehndi",
    name: "Henna by Aroosa",
    initials: "HA",
    tint: tintFor(0),
    rating: 4.9,
    weddingsHere: 5,
    lastWeddingLabel: "Oct 2025",
    lastWeddingSort: "2025-10-07",
    priceRange: "$1K–$2.5K",
    preferred: true,
    venueNote: "Efficient with large bridal parties; never delays the evening's sangeet.",
    verified: true,
  },
  {
    id: "divya-patel",
    categoryId: "mehndi",
    name: "Divya Patel Henna",
    initials: "DP",
    tint: tintFor(1),
    rating: 4.8,
    weddingsHere: 3,
    lastWeddingLabel: "Sep 2025",
    lastWeddingSort: "2025-09-07",
    priceRange: "$800–$2K",
    preferred: false,
  },
  {
    id: "mehndi-magic",
    categoryId: "mehndi",
    name: "Mehndi Magic NJ",
    initials: "MM",
    tint: tintFor(2),
    rating: 4.7,
    weddingsHere: 2,
    lastWeddingLabel: "Aug 2025",
    lastWeddingSort: "2025-08-07",
    priceRange: "$600–$1.5K",
    preferred: false,
  },
  {
    id: "henna-studio",
    categoryId: "mehndi",
    name: "The Henna Studio",
    initials: "TH",
    tint: tintFor(3),
    rating: 4.6,
    weddingsHere: 2,
    lastWeddingLabel: "Jun 2025",
    lastWeddingSort: "2025-06-07",
    priceRange: "$500–$1.3K",
    preferred: false,
  },
  {
    id: "nehas-mehndi",
    categoryId: "mehndi",
    name: "Neha's Mehndi Art",
    initials: "NM",
    tint: tintFor(4),
    rating: 4.5,
    weddingsHere: 1,
    lastWeddingLabel: "Apr 2025",
    lastWeddingSort: "2025-04-07",
    priceRange: "$450–$1.1K",
    preferred: false,
  },
  {
    id: "bridal-henna-co",
    categoryId: "mehndi",
    name: "Bridal Henna Co",
    initials: "BH",
    tint: tintFor(5),
    rating: 4.5,
    weddingsHere: 1,
    lastWeddingLabel: "Feb 2025",
    lastWeddingSort: "2025-02-07",
    priceRange: "$550–$1.2K",
    preferred: false,
  },

  // Lighting (4) — 0 preferred
  {
    id: "luminos-design",
    categoryId: "lighting",
    name: "Luminos Design",
    initials: "LD",
    tint: tintFor(0),
    rating: 4.8,
    weddingsHere: 4,
    lastWeddingLabel: "Oct 2025",
    lastWeddingSort: "2025-10-08",
    priceRange: "$4K–$12K",
    preferred: false,
  },
  {
    id: "shimmer-nj",
    categoryId: "lighting",
    name: "Shimmer NJ",
    initials: "SH",
    tint: tintFor(1),
    rating: 4.7,
    weddingsHere: 2,
    lastWeddingLabel: "Aug 2025",
    lastWeddingSort: "2025-08-08",
    priceRange: "$3K–$8K",
    preferred: false,
  },
  {
    id: "radiant-lighting",
    categoryId: "lighting",
    name: "Radiant Events Lighting",
    initials: "RL",
    tint: tintFor(2),
    rating: 4.6,
    weddingsHere: 2,
    lastWeddingLabel: "Jun 2025",
    lastWeddingSort: "2025-06-08",
    priceRange: "$2.5K–$7K",
    preferred: false,
  },
  {
    id: "glow-gleam",
    categoryId: "lighting",
    name: "Glow & Gleam",
    initials: "GG",
    tint: tintFor(3),
    rating: 4.5,
    weddingsHere: 1,
    lastWeddingLabel: "Mar 2025",
    lastWeddingSort: "2025-03-08",
    priceRange: "$2K–$5.5K",
    preferred: false,
  },

  // Stationery (3) — 1 preferred
  {
    id: "paper-henna",
    categoryId: "stationery",
    name: "Paper & Henna",
    initials: "PH",
    tint: tintFor(0),
    rating: 4.9,
    weddingsHere: 4,
    lastWeddingLabel: "Oct 2025",
    lastWeddingSort: "2025-10-09",
    priceRange: "$1.5K–$4K",
    preferred: true,
    venueNote: "Our in-house stationery partner — ships proofs reliably for our couples.",
    verified: true,
  },
  {
    id: "invitation-atelier",
    categoryId: "stationery",
    name: "Invitation Atelier",
    initials: "IA",
    tint: tintFor(1),
    rating: 4.7,
    weddingsHere: 2,
    lastWeddingLabel: "Jul 2025",
    lastWeddingSort: "2025-07-09",
    priceRange: "$1K–$3K",
    preferred: false,
  },
  {
    id: "letterpress-love",
    categoryId: "stationery",
    name: "Letterpress Love",
    initials: "LP",
    tint: tintFor(2),
    rating: 4.6,
    weddingsHere: 1,
    lastWeddingLabel: "Apr 2025",
    lastWeddingSort: "2025-04-09",
    priceRange: "$800–$2.5K",
    preferred: false,
  },

  // Transportation (4) — 0 preferred
  {
    id: "platinum-limos",
    categoryId: "transportation",
    name: "Platinum Limos NJ",
    initials: "PL",
    tint: tintFor(0),
    rating: 4.8,
    weddingsHere: 5,
    lastWeddingLabel: "Oct 2025",
    lastWeddingSort: "2025-10-10",
    priceRange: "$1.5K–$4K",
    preferred: false,
  },
  {
    id: "royal-coach",
    categoryId: "transportation",
    name: "Royal Coach Services",
    initials: "RC",
    tint: tintFor(1),
    rating: 4.7,
    weddingsHere: 2,
    lastWeddingLabel: "Aug 2025",
    lastWeddingSort: "2025-08-10",
    priceRange: "$1.2K–$3.2K",
    preferred: false,
  },
  {
    id: "baraat-horses",
    categoryId: "transportation",
    name: "Baraat Horses",
    initials: "BR",
    tint: tintFor(2),
    rating: 4.6,
    weddingsHere: 2,
    lastWeddingLabel: "Jul 2025",
    lastWeddingSort: "2025-07-10",
    priceRange: "$800–$2K",
    preferred: false,
  },
  {
    id: "executive-fleet",
    categoryId: "transportation",
    name: "Executive Fleet",
    initials: "EF",
    tint: tintFor(3),
    rating: 4.5,
    weddingsHere: 1,
    lastWeddingLabel: "Mar 2025",
    lastWeddingSort: "2025-03-10",
    priceRange: "$900–$2.5K",
    preferred: false,
  },

  // Photo Booth (3) — 0 preferred
  {
    id: "smile-box",
    categoryId: "photo-booth",
    name: "Smile Box NJ",
    initials: "SB",
    tint: tintFor(0),
    rating: 4.7,
    weddingsHere: 3,
    lastWeddingLabel: "Oct 2025",
    lastWeddingSort: "2025-10-11",
    priceRange: "$800–$2K",
    preferred: false,
  },
  {
    id: "vintage-booth",
    categoryId: "photo-booth",
    name: "Vintage Booth Co",
    initials: "VB",
    tint: tintFor(1),
    rating: 4.6,
    weddingsHere: 2,
    lastWeddingLabel: "Aug 2025",
    lastWeddingSort: "2025-08-11",
    priceRange: "$700–$1.8K",
    preferred: false,
  },
  {
    id: "flash-frame",
    categoryId: "photo-booth",
    name: "Flash & Frame",
    initials: "FF",
    tint: tintFor(2),
    rating: 4.5,
    weddingsHere: 1,
    lastWeddingLabel: "May 2025",
    lastWeddingSort: "2025-05-11",
    priceRange: "$600–$1.5K",
    preferred: false,
  },

  // Priest (3) — 1 preferred
  {
    id: "pandit-sharma",
    categoryId: "priest",
    name: "Pandit Sharma Ji",
    initials: "PS",
    tint: tintFor(0),
    rating: 4.9,
    weddingsHere: 6,
    lastWeddingLabel: "Oct 2025",
    lastWeddingSort: "2025-10-12",
    priceRange: "$800–$1.8K",
    preferred: true,
    venueNote: "Fluent in both traditional and bilingual Hindu ceremonies. Our couples adore him.",
    verified: true,
  },
  {
    id: "acharya-mehra",
    categoryId: "priest",
    name: "Acharya Mehra",
    initials: "AM",
    tint: tintFor(1),
    rating: 4.8,
    weddingsHere: 3,
    lastWeddingLabel: "Aug 2025",
    lastWeddingSort: "2025-08-12",
    priceRange: "$700–$1.5K",
    preferred: false,
  },
  {
    id: "pandit-ravi",
    categoryId: "priest",
    name: "Pandit Ravi",
    initials: "PR",
    tint: tintFor(2),
    rating: 4.6,
    weddingsHere: 1,
    lastWeddingLabel: "Apr 2025",
    lastWeddingSort: "2025-04-12",
    priceRange: "$600–$1.3K",
    preferred: false,
  },
];

// ---- Planners ---------------------------------------------------------------

export const VENUE_PLANNERS: VenuePlanner[] = [
  {
    id: "radz-events",
    name: "Radz Events",
    lead: "Urvashi Menon",
    initials: "RE",
    tint: tintFor(0),
    weddingsHere: 12,
    rating: 4.9,
    city: "NJ",
    services: "Full-service + Destination",
  },
  {
    id: "cg-co",
    name: "CG & Co Events",
    lead: "Christine Gupta",
    initials: "CG",
    tint: tintFor(1),
    weddingsHere: 7,
    rating: 4.8,
    city: "DC",
    services: "Full-service",
  },
  {
    id: "detailed-affairs",
    name: "Detailed Affairs",
    initials: "DA",
    tint: tintFor(2),
    weddingsHere: 4,
    rating: 4.7,
    city: "NJ",
    services: "Full + Partial",
  },
  {
    id: "ever-after",
    name: "Ever After Events",
    lead: "Meera Kapoor",
    initials: "EA",
    tint: tintFor(3),
    weddingsHere: 3,
    rating: 4.7,
    city: "NY",
    services: "Full-service",
  },
  {
    id: "bloom-planners",
    name: "Bloom Planners",
    lead: "Rajiv Anand",
    initials: "BP",
    tint: tintFor(4),
    weddingsHere: 3,
    rating: 4.6,
    city: "NJ",
    services: "Partial + Day-of",
  },
  {
    id: "saffron-curate",
    name: "Saffron Curate",
    lead: "Anika Shah",
    initials: "SC",
    tint: tintFor(5),
    weddingsHere: 2,
    rating: 4.8,
    city: "PA",
    services: "Full-service + Destination",
  },
];

// ---- Active couples at this venue (for "Recommend to Couple" dropdown) ------

export const ACTIVE_COUPLES_AT_VENUE = [
  { id: "priya-arjun", label: "Priya & Arjun — Oct 15" },
  { id: "sarah-mike", label: "Sarah & Mike — Oct 22" },
  { id: "neha-vikram", label: "Neha & Vikram — Nov 8" },
];

// ---- Summary stats ----------------------------------------------------------

export const VENDOR_NETWORK_STATS = {
  totalVendors: 89,
  totalWeddings: 47,
  preferredCount: 12,
  plannerCount: VENUE_PLANNERS.length,
};
