// ── Weekly Digests store ────────────────────────────────────────────────
// "This week in your wedding" — a warm, personalized narrative summary
// of last week's activity and the week ahead. One entry per week,
// keyed by the ISO date of that week's Monday (week_start).
//
// The narrative itself is generated by /api/dashboard/weekly-digest
// (Claude when available, heuristic fallback otherwise). The store is
// just a cache: open the dashboard once a week, the digest appears,
// the same week's digest is reused on every subsequent visit.

import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";

export interface WeeklyDigest {
  id: string;
  /** ISO date (YYYY-MM-DD) of the Monday this digest covers. */
  weekStart: string;
  content: string;
  /** Snapshot of the structured activity passed to the model — kept so
   * we can inspect what the digest was actually generated against. */
  activityData: Record<string, unknown>;
  dismissed: boolean;
  createdAt: string;
}

interface SaveInput {
  weekStart: string;
  content: string;
  activityData: Record<string, unknown>;
}

interface WeeklyDigestsState {
  digests: WeeklyDigest[];
  saveDigest: (input: SaveInput) => WeeklyDigest;
  dismiss: (id: string) => void;
  remove: (id: string) => void;
  getForWeek: (weekStart: string) => WeeklyDigest | null;
}

const uid = (): string =>
  typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `wd_${Math.random().toString(36).slice(2, 10)}_${Date.now().toString(36)}`;

export const useWeeklyDigestsStore = create<WeeklyDigestsState>()(
  persist(
    (set, get) => ({
      digests: [],

      saveDigest: (input) => {
        const existing = get().digests.find(
          (d) => d.weekStart === input.weekStart,
        );
        const now = new Date().toISOString();
        if (existing) {
          const updated: WeeklyDigest = {
            ...existing,
            content: input.content,
            activityData: input.activityData,
          };
          set((s) => ({
            digests: s.digests.map((d) =>
              d.id === existing.id ? updated : d,
            ),
          }));
          return updated;
        }
        const digest: WeeklyDigest = {
          id: uid(),
          weekStart: input.weekStart,
          content: input.content,
          activityData: input.activityData,
          dismissed: false,
          createdAt: now,
        };
        set((s) => ({ digests: [digest, ...s.digests] }));
        return digest;
      },

      dismiss: (id) =>
        set((s) => ({
          digests: s.digests.map((d) =>
            d.id === id ? { ...d, dismissed: true } : d,
          ),
        })),

      remove: (id) =>
        set((s) => ({
          digests: s.digests.filter((d) => d.id !== id),
        })),

      getForWeek: (weekStart) =>
        get().digests.find((d) => d.weekStart === weekStart) ?? null,
    }),
    {
      name: "ananya:weekly-digests",
      storage: createJSONStorage(() => {
        if (typeof window === "undefined") {
          return {
            getItem: () => null,
            setItem: () => undefined,
            removeItem: () => undefined,
          };
        }
        return window.localStorage;
      }),
      partialize: (s) => ({ digests: s.digests }),
    },
  ),
);

// ── Week-start helpers ────────────────────────────────────────────────
// Monday-anchored week. Sunday counts as the prior week so "this week"
// covers Mon–Sun consistent with US wedding-week convention.
export function mondayOf(date: Date): Date {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  const dow = d.getDay(); // Sun = 0, Mon = 1, ...
  const offset = dow === 0 ? -6 : 1 - dow;
  d.setDate(d.getDate() + offset);
  return d;
}

export function weekStartIso(date: Date = new Date()): string {
  return mondayOf(date).toISOString().slice(0, 10);
}
