// ── Bachelor destination playbooks ────────────────────────────────────────
// Hand-curated deep-dive content for flagship destinations. Writing voice
// follows the spec: buddy-in-the-group-chat, opinionated, specific, honest
// about money and logistics. Destinations without a playbook show a
// "coming soon" state in the detail view.
//
// Adding a new playbook: fill every field of DestinationPlaybook. Real
// place names only. Avoid corporate travel-brochure tone.

import type { DestinationPlaybook } from "@/types/bachelor";

export const PLAYBOOKS: Record<string, DestinationPlaybook> = {
  // ── Scottsdale ─────────────────────────────────────────────────────────
  scottsdale: {
    overview:
      "Scottsdale is the default for a reason — and if you lean into it (golf, Old Town, pool time, steak), it earns the hype. The play is a house in Old Town, 1 big round, 1 anchor dinner, 1 real night out, and slow mornings. Spring and fall are prime. Summer is a different sport.",
    sampleItinerary: [
      {
        label: "Day 1",
        title: "Touch Down, Set Up, Go",
        body: "Everyone lands by 3pm, Ubers to the house. 6-bedroom spot in Old Town with a pool and a grill — don't overthink it, this is home base. Drop bags, crack beers, get the grill going. First night is low-key on purpose: steaks at the house, poker table set up in the living room, and a cigar on the patio. Nobody needs to go out tonight. Save your energy.",
        highlights: [
          { time: "3:00 PM", activity: "Land + Uber to the Old Town Airbnb" },
          { time: "4:30 PM", activity: "Costco run — steaks, beers, ice" },
          { time: "7:00 PM", activity: "Grill + poker at the house" },
          { time: "11:00 PM", activity: "Cigars on the patio, then crash" },
        ],
      },
      {
        label: "Day 2",
        title: "The Main Event",
        body: "7:30am tee time at TPC Scottsdale's Stadium Course (book this 60 days out — it fills up). The groom plays free, everyone else splits his green fee. After 18, lunch at The Vig and then everyone back to the house for pool time. 7pm dinner at Steak 44 — this is the one reservation that matters, make it 6 weeks early and request the main room. After dinner, hit Old Town: start at Bottled Blonde for the energy, move to Casa Amigos if you want to dance, end at Coach House for a dive bar nightcap.",
        highlights: [
          { time: "7:30 AM", activity: "Tee time — TPC Stadium Course" },
          { time: "1:00 PM", activity: "Lunch at The Vig (back patio)" },
          { time: "3:00 PM", activity: "Pool time at the house" },
          { time: "7:00 PM", activity: "Steak 44 — main room, reservation for 10" },
          { time: "10:00 PM", activity: "Old Town: Bottled Blonde → Casa Amigos" },
          { time: "12:30 AM", activity: "Coach House for a dive nightcap" },
        ],
      },
      {
        label: "Day 3",
        title: "Recovery & Send-Off",
        body: "Sleep in. Someone makes a coffee run. 11am brunch at Hash Kitchen — go with the build-your-own bloody mary bar, it's a move. If the crew has gas left in the tank, book a side-by-side ATV tour in the desert (2 hours, ~$150/person). Otherwise, pool, beers, and a 4pm flight home. That's a bachelor party.",
        highlights: [
          { time: "10:00 AM", activity: "Coffee run — someone do this" },
          { time: "11:00 AM", activity: "Brunch at Hash Kitchen" },
          { time: "1:30 PM", activity: "Desert ATV (optional) or pool" },
          { time: "4:00 PM", activity: "Airport runs" },
        ],
      },
    ],
    foodAndDrink: [
      {
        category: "anchor_dinner",
        name: "Steak 44",
        neighborhood: "Paradise Valley",
        priceRange: "$$$$",
        perPerson: "$150–200 with drinks",
        vibe: "Dark wood, leather booths, steaks you'll talk about for a month",
        reservationNote: "Book 6 weeks out. Request the main dining room.",
        groupNote: "Handles 10+ in the main room without issue",
        insiderTip:
          "Order the tomahawk for the table. Tell them it's a bachelor party when you book — they take care of you.",
      },
      {
        category: "group_lunch",
        name: "The Vig (Old Town)",
        neighborhood: "Old Town Scottsdale",
        priceRange: "$$",
        perPerson: "$40 with a couple drinks",
        vibe: "Back patio, cold beer, gastropub food, zero pretense",
        reservationNote: "Walk-in fine except Sunday brunch",
        groupNote: "Grab the back patio — fits 10 easily",
        insiderTip: "Get the Vig burger. Yes it's a burger. It's great.",
      },
      {
        category: "morning_after",
        name: "Hash Kitchen",
        neighborhood: "Old Town Scottsdale",
        priceRange: "$$",
        perPerson: "$35 with the bloody mary bar",
        vibe: "Brunch that hits different — build-your-own bloody mary bar is the gimmick and it works",
        reservationNote: "Reserve — Sunday gets slammed",
        insiderTip: "Bloody mary bar. Don't be cute about it, just go.",
      },
      {
        category: "dive_bar",
        name: "Coach House",
        neighborhood: "Old Town Scottsdale",
        priceRange: "$",
        perPerson: "$20",
        vibe: "Cash-only Christmas lights year-round, pool table, zero attitude",
        reservationNote: "Walk-in, no reservations ever",
        insiderTip: "This is the end-of-night move, not the start. Go after midnight.",
      },
      {
        category: "steakhouse",
        name: "Mastro's Ocean Club",
        neighborhood: "Scottsdale Quarter",
        priceRange: "$$$$",
        perPerson: "$180–220",
        vibe: "If Steak 44 is booked, this is the move. Live piano, big steaks, butter cake.",
        reservationNote: "Book 4 weeks out",
        groupNote: "Large party section on request",
        insiderTip: "The butter cake is not optional. Order two for the table.",
      },
      {
        category: "sports_bar",
        name: "The Montauk",
        neighborhood: "Old Town Scottsdale",
        priceRange: "$$",
        perPerson: "$40",
        vibe: "Rooftop + downstairs, tons of TVs, game-day energy",
        reservationNote: "Walk-in fine — reserve rooftop for 10+",
        insiderTip: "Sunday football is prime. Get there 30 minutes before kickoff.",
      },
      {
        category: "late_night",
        name: "Diego Pops",
        neighborhood: "Old Town Scottsdale",
        priceRange: "$",
        perPerson: "$20",
        vibe: "Tacos + margs at 1 AM, no line",
        reservationNote: "Walk-in",
        insiderTip: "Brisket tacos. Order double.",
      },
    ],
    activities: [
      {
        category: "competitive",
        name: "TPC Scottsdale — Stadium Course",
        costPerPerson: "$280–400",
        groupSize: "Max 2 foursomes (8)",
        bookingLead: "60 days out, 6 AM sharp",
        duration: "5 hours including drinks",
        intensity: "easy",
        weatherDependent: true,
        interestTags: ["golf"],
        note: "The 16th hole is the one you've seen on TV. Play it.",
      },
      {
        category: "competitive",
        name: "Top Golf Riverwalk",
        costPerPerson: "$45",
        groupSize: "Up to 8 per bay, book 2 bays",
        bookingLead: "2 weeks out",
        duration: "2 hours",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["golf"],
        note: "Good Plan B if the real round falls through",
      },
      {
        category: "adrenaline",
        name: "Desert Wolf ATV / UTV Tour",
        costPerPerson: "$150",
        groupSize: "Up to 16",
        bookingLead: "2 weeks out",
        duration: "2.5 hours",
        intensity: "moderate",
        weatherDependent: false,
        note: "Sunset tour is the move — golden hour in the desert",
      },
      {
        category: "chill",
        name: "Cabana day at Maya Day + Nightclub",
        costPerPerson: "$100–200 including bottle",
        groupSize: "Cabana fits 10",
        bookingLead: "3 weeks out",
        duration: "4 hours",
        intensity: "easy",
        weatherDependent: true,
      },
      {
        category: "food_drink",
        name: "Old Town Tequila Trail",
        costPerPerson: "$60",
        groupSize: "Any",
        bookingLead: "Walk-up",
        duration: "3 hours",
        intensity: "moderate",
        weatherDependent: false,
        note: "Self-guided: Diego Pops → Blanco Tacos → Salty Señorita",
      },
      {
        category: "sports_events",
        name: "Spring Training (Feb–Mar)",
        costPerPerson: "$30–80",
        groupSize: "Any",
        bookingLead: "Same week",
        duration: "4 hours",
        intensity: "easy",
        weatherDependent: true,
        interestTags: ["sports_watching"],
        note: "Cubs, Giants, Angels all train here — check the schedule",
      },
      {
        category: "nightlife",
        name: "Old Town Bar Route",
        costPerPerson: "$80–120",
        groupSize: "Any",
        bookingLead: "None",
        duration: "All night",
        intensity: "full_send",
        weatherDependent: false,
        note: "Bottled Blonde → Casa Amigos → Coach House. That's the route.",
      },
      {
        category: "unique",
        name: "Hot air balloon sunrise",
        costPerPerson: "$225",
        groupSize: "Up to 12",
        bookingLead: "1 week out",
        duration: "3 hours + early call time",
        intensity: "easy",
        weatherDependent: true,
        note: "If the groom is into it — otherwise skip",
      },
    ],
    accommodation: {
      house:
        "Get a 6+ bedroom Airbnb in Old Town with a pool, grill, and street parking. Walkable to bars means no one's driving at 2 AM. Budget $2,500–$4,500 for the weekend split.",
      hotel:
        "W Scottsdale or Hotel Valley Ho if you want pool scene + housekeeping. Fine for 4–6 guys, overkill for 8+.",
      upgrade:
        "Four Seasons Troon North or The Phoenician. Resort golf on property, spa for the hangover. Add $600/person to the trip.",
      budget: "Group Airbnb further out in Tempe saves ~30% but loses walkability. Not worth it for a short trip.",
    },
    logistics: {
      gettingThere:
        "Fly into PHX — 20 min from Old Town. Uber is fine; splitting a rental is fine too but not necessary.",
      gettingAround:
        "Old Town is walkable. Everywhere else is Uber territory. Don't rent cars for the whole crew — one SUV is plenty for Costco runs and airport shuttles.",
      moneyMath:
        "House ~$350/person · Golf ~$350/person · Food & drinks ~$300/person · Activities ~$150/person · Total per person: $1,100–$1,400 (not incl. flights)",
      bookingTimeline:
        "Stadium Course tee time: 60 days out at 6 AM. Steak 44: 6 weeks out. House: as soon as the date's locked — Old Town 6-bedrooms book fast. Flights: ASAP.",
      bestManTips:
        "Collect money upfront via Venmo — don't chase people day-of. Put the groom's green fee on your card and split separately. Assign one person to the cooler/Costco run so nobody's waiting at the house. Pre-order a cigar case from the Old Town tobacconist — easy win.",
    },
  },

  // ── Nashville ──────────────────────────────────────────────────────────
  nashville: {
    overview:
      "Nashville is a volume game — live music every night, bars everywhere, and enough hot chicken to make the flight home regrettable. The trick is to skip the tourist-bus stuff (pedal tavern is fine if you're 6 or fewer; 10+ gets embarrassing) and anchor the trip around one great dinner and one live show.",
    sampleItinerary: [
      {
        label: "Day 1",
        title: "Broadway Orientation",
        body: "Land by 4, drop bags downtown. First stop is Hattie B's for hot chicken — yes, it's touristy; yes, it's worth it. Line moves fast. After that, walk Broadway at 6 PM while it's still manageable. Pick one honky-tonk (Robert's Western World — free cover, great band) for 2 drinks, then get out before it's a zoo. Dinner at Peg Leg Porker. Crash early — Saturday is long.",
        highlights: [
          { time: "4:00 PM", activity: "Check in — downtown or Germantown house" },
          { time: "5:00 PM", activity: "Hattie B's hot chicken (pick your heat honestly)" },
          { time: "7:00 PM", activity: "Robert's Western World — 2 drinks, then out" },
          { time: "9:00 PM", activity: "Dinner — Peg Leg Porker" },
          { time: "11:00 PM", activity: "Cap at Honky Tonk Central, home by 1" },
        ],
      },
      {
        label: "Day 2",
        title: "The Long One",
        body: "Late brunch at Biscuit Love or The Pharmacy. Afternoon move: pedal tavern if you're 4–6 guys (it's a thing, embrace it); otherwise, Topgolf or axe throwing at Stumpy's. 7pm anchor dinner at The 404 Kitchen or Butcher & Bee. Catch a show at the Ryman if there's something on — otherwise a late show at the Bluebird Cafe. Broadway at 10 if you still have legs; Printers Alley has a dive bar scene that's less chaotic.",
        highlights: [
          { time: "11:00 AM", activity: "Brunch at Biscuit Love" },
          { time: "1:30 PM", activity: "Pedal tavern / Topgolf / Stumpy's Axe" },
          { time: "7:00 PM", activity: "Anchor dinner — The 404 Kitchen" },
          { time: "9:00 PM", activity: "Ryman show or Bluebird late set" },
          { time: "11:00 PM", activity: "Printers Alley bar crawl" },
        ],
      },
      {
        label: "Day 3",
        title: "Wind Down & Fly",
        body: "Brunch at Pinewood Social — there's bowling if you want to kill time. Stroll the Gulch for shopping if that's the crew's thing. Flights out by 4. If you have an extra day, do the Distillery District (Nelson's Green Brier, Nashville Barrel Co) as a half-day move.",
        highlights: [
          { time: "10:30 AM", activity: "Brunch + bowling at Pinewood Social" },
          { time: "12:30 PM", activity: "Optional: Distillery District tour" },
          { time: "3:00 PM", activity: "Airport" },
        ],
      },
    ],
    foodAndDrink: [
      {
        category: "anchor_dinner",
        name: "The 404 Kitchen",
        neighborhood: "The Gulch",
        priceRange: "$$$$",
        perPerson: "$120–160",
        vibe: "Modern Southern, small room, excellent wine, the one fine dinner on the trip",
        reservationNote: "4 weeks out — large parties need the private room",
        groupNote: "Private room fits 12",
        insiderTip: "Order the tasting if the kitchen's running it. Let them pair wine.",
      },
      {
        category: "group_lunch",
        name: "Peg Leg Porker",
        neighborhood: "The Gulch",
        priceRange: "$$",
        perPerson: "$30",
        vibe: "Dry-rub Memphis-style BBQ, picnic tables, cash-and-carry energy",
        reservationNote: "No reservations — go before 12 or after 2",
        groupNote: "Can handle 10+ if you spread across two tables",
        insiderTip: "Nashville hot chicken is the calling card but the BBQ nachos slap.",
      },
      {
        category: "morning_after",
        name: "Biscuit Love",
        neighborhood: "The Gulch / Hillsboro",
        priceRange: "$",
        perPerson: "$25",
        vibe: "Line out the door for a reason — biscuits the size of your hand",
        reservationNote: "No reservations. Bonuts are worth the wait.",
        insiderTip: "Hillsboro Village location has a shorter line than the Gulch.",
      },
      {
        category: "dive_bar",
        name: "Santa's Pub",
        neighborhood: "South Nashville",
        priceRange: "$",
        perPerson: "$15",
        vibe: "Cash-only karaoke trailer. Yes, a trailer. Legendary.",
        reservationNote: "Walk-in, cash only, BYOB on certain nights",
        insiderTip: "Sing early. It gets crowded by 10 PM and the list gets long.",
      },
      {
        category: "steakhouse",
        name: "Bourbon Steak",
        neighborhood: "JW Marriott downtown",
        priceRange: "$$$$",
        perPerson: "$160",
        vibe: "Corporate-polished, great for group steakhouse night",
        reservationNote: "2 weeks out fine",
        groupNote: "Reserve a half-private section for 10+",
        insiderTip: "Duck-fat fries. Order two rounds.",
      },
      {
        category: "sports_bar",
        name: "The Big Bang",
        neighborhood: "Printers Alley",
        priceRange: "$$",
        perPerson: "$35",
        vibe: "Dueling pianos + sports on TV, surprisingly fun for groups",
        reservationNote: "Call ahead for 8+",
        insiderTip: "Tip the piano players $20 upfront — they'll play your songs all night.",
      },
      {
        category: "late_night",
        name: "Arnold's Country Kitchen (breakfast) / Party Fowl (night)",
        neighborhood: "Downtown",
        priceRange: "$",
        perPerson: "$18",
        vibe: "Party Fowl does hot chicken + cocktails past midnight",
        reservationNote: "Walk-in",
        insiderTip: "The Nashville-hot tenders with ranch is a life-saver at 1 AM.",
      },
      {
        category: "brewery_distillery",
        name: "Nelson's Green Brier Distillery",
        neighborhood: "Marathon Village",
        priceRange: "$",
        perPerson: "$15 tour",
        vibe: "Small-batch Tennessee whiskey, solid tour, buy a bottle before the flight",
        reservationNote: "Book the Friday/Sat 1 PM tour — 2 weeks out",
        groupNote: "Private tours available for 10+",
        insiderTip: "Pick up the Belle Meade bourbon — not sold widely outside TN.",
      },
    ],
    activities: [
      {
        category: "competitive",
        name: "Stumpy's Hatchet House",
        costPerPerson: "$40",
        groupSize: "Up to 16 across lanes",
        bookingLead: "1 week out",
        duration: "90 minutes",
        intensity: "easy",
        weatherDependent: false,
      },
      {
        category: "competitive",
        name: "Topgolf Nashville",
        costPerPerson: "$45",
        groupSize: "Up to 8 per bay",
        bookingLead: "2 weeks out",
        duration: "2 hours",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["golf"],
      },
      {
        category: "food_drink",
        name: "Hot chicken crawl (Hattie B's → Prince's → Party Fowl)",
        costPerPerson: "$60",
        groupSize: "Any",
        bookingLead: "None",
        duration: "Half day",
        intensity: "moderate",
        weatherDependent: false,
        note: "Pace yourself — these are not small portions",
      },
      {
        category: "food_drink",
        name: "Nashville Whiskey Trail",
        costPerPerson: "$85",
        groupSize: "Max 14",
        bookingLead: "2 weeks out",
        duration: "3 hours",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["bourbon"],
      },
      {
        category: "sports_events",
        name: "Titans or Preds game",
        costPerPerson: "$80–200",
        groupSize: "Any",
        bookingLead: "3+ weeks out",
        duration: "4 hours",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["sports_watching"],
        note: "Preds in-arena energy is top-5 in the NHL",
      },
      {
        category: "sports_events",
        name: "Ryman / Grand Ole Opry show",
        costPerPerson: "$50–120",
        groupSize: "Any",
        bookingLead: "3 weeks out",
        duration: "2.5 hours",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["live_music"],
        note: "If there's a name on the bill you recognize, book it",
      },
      {
        category: "nightlife",
        name: "Pedal tavern (if you're 6 or fewer)",
        costPerPerson: "$45",
        groupSize: "Max 15 (but ideal at 6)",
        bookingLead: "1 week out",
        duration: "2 hours",
        intensity: "moderate",
        weatherDependent: true,
        note: "Wear something you don't care about. Bring water. Tip the driver.",
      },
      {
        category: "unique",
        name: "Private songwriter session at a writer's round",
        costPerPerson: "$60",
        groupSize: "Up to 20",
        bookingLead: "4 weeks out",
        duration: "90 minutes",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["live_music"],
        note: "Bluebird Cafe is the famous one — private sessions are hard to get. Try Commodore Grille as a backup.",
      },
    ],
    accommodation: {
      house:
        "Germantown or the Gulch — modern 5-6 BR townhomes with rooftops run $2,800–$4,200 for 3 nights. Worth the splurge over downtown tourist zones.",
      hotel:
        "The Noelle downtown is the move — walkable to Broadway, rooftop bar, cool rooms. Book 4+ rooms and ask for a group rate.",
      upgrade:
        "The Hermitage Hotel for the classic 'Nashville millionaire' feel. Overkill unless the crew wants that energy.",
      budget: "Homewood Suites in the Gulch — unglamorous but clean, walkable, ~$180/night per room split.",
    },
    logistics: {
      gettingThere:
        "Fly BNA. Ubers are easy and cheap. If the crew's flying in from multiple cities, stagger arrival so the first 2 guys do the Costco-style beer run before everyone else lands.",
      gettingAround:
        "Walk Broadway, Uber everything else. Pedal tavern is its own mode of transport and it sucks with big crews — think twice.",
      moneyMath:
        "House ~$280/person · Food & drinks ~$250/person · Activities & shows ~$150/person · Nightlife ~$120/person · Total: ~$800–$1,100 (not incl. flights)",
      bookingTimeline:
        "Game/show tickets: 3+ weeks. The 404 Kitchen: 4 weeks. House: as soon as date's set — Germantown goes fast. Hot chicken: walk-in, always.",
      bestManTips:
        "Don't book bachelor-party-branded anything (sashes, matching shirts). Nashville is saturated with that and it makes the crew look like tourists. Keep the vibe grown-up and you'll have more fun.",
    },
  },

  // ── Vegas ──────────────────────────────────────────────────────────────
  vegas: {
    overview:
      "Vegas works best when you lean all the way in — nobody's there for subtle. The classic 3-day play: one big night with bottle service or a UFC/fight card, one day at a dayclub or pool, and one recovery day with a good steak and a golf round or poker session. Pace matters more than you think.",
    sampleItinerary: [
      {
        label: "Day 1",
        title: "Land + Steady Start",
        body: "Land midday, check into the strip hotel (MGM area, Aria, or Cosmo are the group sweet spot). First move: the pool for 2 hours to shake off the flight. 6pm dinner at Carbone — you're not gonna regret it. After dinner, do a casino floor cruise with a small gambling session — keep it to $100/person. If the energy's right, hit a lounge (Vesper at Cosmo) for drinks. DO NOT open the night with a nightclub. Tomorrow's the marathon.",
        highlights: [
          { time: "1:00 PM", activity: "Check in — Aria / Cosmo / MGM" },
          { time: "2:30 PM", activity: "Pool time + first beers" },
          { time: "6:30 PM", activity: "Dinner — Carbone (6pm reservation)" },
          { time: "9:00 PM", activity: "Blackjack / craps for 90 min, $100 cap" },
          { time: "11:00 PM", activity: "Drinks at Vesper, home by 1" },
        ],
      },
      {
        label: "Day 2",
        title: "Full Send",
        body: "11am brunch at Bouchon. Dayclub from 1-6 PM at Encore Beach or Ayu Dayclub — bottle service cabana is the move for any group of 8+, it's not actually that much per person and saves your sanity. Back to the room at 6 to regroup and change. 8pm dinner at STK or Delmonico — make reservations weeks out. Night move: either (a) UFC/fight at T-Mobile if there's one on, or (b) bottle service at XS/Omnia/Zouk. End at Peppermill for the 3 AM breakfast tradition.",
        highlights: [
          { time: "11:00 AM", activity: "Brunch — Bouchon" },
          { time: "1:00 PM", activity: "Dayclub cabana — Encore Beach or Ayu" },
          { time: "8:00 PM", activity: "Anchor dinner — STK or Delmonico" },
          { time: "11:00 PM", activity: "Nightclub: XS / Omnia / Zouk" },
          { time: "3:00 AM", activity: "Peppermill breakfast at the fireside" },
        ],
      },
      {
        label: "Day 3",
        title: "Recovery Round",
        body: "Sleep in — no alarms. Coffee + lobby breakfast. Optional: morning round at Shadow Creek if you booked it (huge splurge — only do this if money isn't the issue). Otherwise, poker at Bellagio, 11am–3pm. 4pm check-out, late flight. The crew's done — send everyone home before anyone gets a second wind.",
        highlights: [
          { time: "10:30 AM", activity: "Lobby breakfast + coffee" },
          { time: "11:30 AM", activity: "Bellagio poker room OR Shadow Creek round" },
          { time: "4:00 PM", activity: "Check out + airport runs" },
        ],
      },
    ],
    foodAndDrink: [
      {
        category: "anchor_dinner",
        name: "Carbone",
        neighborhood: "Aria",
        priceRange: "$$$$",
        perPerson: "$200–260",
        vibe: "Campy-glamorous Italian-American, spicy rigatoni vodka is the dish to order",
        reservationNote: "Book the day reservations open — typically 60 days out",
        groupNote: "Private dining room fits 10",
        insiderTip: "Spicy rigatoni + meatballs for the table. Don't let anyone talk you out of it.",
      },
      {
        category: "group_lunch",
        name: "Bouchon",
        neighborhood: "Venetian",
        priceRange: "$$$",
        perPerson: "$75",
        vibe: "Thomas Keller's bistro — croissants, steak frites, daylight dining",
        reservationNote: "Brunch — reserve 2 weeks out",
        groupNote: "Private patio for 12+",
        insiderTip: "Get the short rib burger. Trust.",
      },
      {
        category: "morning_after",
        name: "Peppermill Fireside Lounge",
        neighborhood: "Strip (near Wynn)",
        priceRange: "$",
        perPerson: "$25",
        vibe: "3 AM breakfast in a sunken fireplace lounge — a Vegas classic",
        reservationNote: "Walk-in, 24 hours",
        insiderTip: "Pancakes + side of bacon. This exists for exactly the moment you're in.",
      },
      {
        category: "dive_bar",
        name: "Atomic Liquors",
        neighborhood: "Downtown (Fremont)",
        priceRange: "$",
        perPerson: "$20",
        vibe: "Oldest freestanding bar in Vegas — no slot machines, just actual bar",
        reservationNote: "Walk-in",
        insiderTip: "Take an Uber off-strip for this one. The vibe is a different Vegas entirely.",
      },
      {
        category: "steakhouse",
        name: "Delmonico Steakhouse (Emeril)",
        neighborhood: "Venetian",
        priceRange: "$$$$",
        perPerson: "$180",
        vibe: "Classic steakhouse, banquet room for groups, the Bananas Foster dessert is tableside theater",
        reservationNote: "3 weeks out",
        groupNote: "Private dining room seats 14",
        insiderTip: "Do the Bananas Foster dessert. They set it on fire at the table.",
      },
      {
        category: "sports_bar",
        name: "Sage at Aria (bar) / Nudo at MGM",
        neighborhood: "Strip",
        priceRange: "$$$",
        perPerson: "$60",
        vibe: "Classy sports bars — flat screens + decent food",
        reservationNote: "Walk-in fine",
        insiderTip: "Strip sports books are the move if there's a big game — set a per-person cap before you sit down.",
      },
      {
        category: "late_night",
        name: "Secret Pizza (Cosmopolitan)",
        neighborhood: "Cosmopolitan, 3rd floor",
        priceRange: "$",
        perPerson: "$10",
        vibe: "Unmarked pizza counter, 2 AM line, NY-style slices",
        reservationNote: "Walk-in, cash only",
        insiderTip: "It's genuinely good and the line moves fast. Don't skip it.",
      },
    ],
    activities: [
      {
        category: "nightlife",
        name: "Bottle service cabana — XS / Omnia / Zouk",
        costPerPerson: "$250–600 depending on club + night",
        groupSize: "Table fits 8–12",
        bookingLead: "3+ weeks out for weekends",
        duration: "All night",
        intensity: "full_send",
        weatherDependent: false,
        note: "DJ schedule drives which club — check Zedd/Tiesto/etc tour calendars and book from there",
      },
      {
        category: "water",
        name: "Dayclub cabana — Encore Beach, Ayu, Liquid",
        costPerPerson: "$150–250 with bottle",
        groupSize: "Cabana fits 10",
        bookingLead: "3 weeks out",
        duration: "5 hours",
        intensity: "moderate",
        weatherDependent: true,
        note: "Book a shaded cabana — sun in Vegas is no joke, even in May.",
      },
      {
        category: "sports_events",
        name: "UFC / boxing card at T-Mobile Arena",
        costPerPerson: "$200–1000",
        groupSize: "Any",
        bookingLead: "As soon as card drops",
        duration: "5 hours",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["sports_watching"],
        note: "If your dates line up with a card, this becomes the anchor of the whole trip",
      },
      {
        category: "sports_events",
        name: "F1 Vegas GP (November)",
        costPerPerson: "$1500+",
        groupSize: "Any",
        bookingLead: "6+ months out",
        duration: "Full weekend",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["cars_racing"],
        note: "Expensive. Worth it if the groom cares about racing.",
      },
      {
        category: "competitive",
        name: "Bellagio poker room",
        costPerPerson: "Buy-in varies ($100–500+)",
        groupSize: "Any",
        bookingLead: "Walk-up",
        duration: "3–5 hours",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["poker"],
        note: "Set a per-person stop-loss before you sit down. Discipline > variance.",
      },
      {
        category: "competitive",
        name: "Shadow Creek (invite-only course, MGM guests)",
        costPerPerson: "$750",
        groupSize: "Max 4 per group, book two groups",
        bookingLead: "60 days out, MGM high-roller contact",
        duration: "Full day",
        intensity: "easy",
        weatherDependent: true,
        interestTags: ["golf"],
        note: "If money isn't the issue, this is the move. Otherwise, TPC Las Vegas is great at ~$250.",
      },
      {
        category: "adrenaline",
        name: "Exotics Racing (drive a Ferrari)",
        costPerPerson: "$280 for 5 laps",
        groupSize: "Any, but reserve time slots",
        bookingLead: "2 weeks out",
        duration: "2 hours",
        intensity: "moderate",
        weatherDependent: true,
        interestTags: ["cars_racing"],
      },
      {
        category: "unique",
        name: "Sphere show",
        costPerPerson: "$200–500",
        groupSize: "Any",
        bookingLead: "4+ weeks out",
        duration: "2 hours",
        intensity: "easy",
        weatherDependent: false,
        note: "Even if you don't love the artist — the venue is the show.",
      },
    ],
    accommodation: {
      house:
        "Airbnb doesn't really work in Vegas — house rentals are far from the strip and the point is walking between casinos. Skip.",
      hotel:
        "Aria, Cosmopolitan, or Wynn for the right vibe — book a 2BR suite for $500–900/night. For 8+ guys, get 3–4 standard rooms instead.",
      upgrade:
        "Encore Tower Suite, Cosmo Boulevard Penthouse, or the Palms Sky Villa. $3k+/night for the full 'HBO show' treatment.",
      budget: "Flamingo or Linq — on the strip, clean, $100/night. Less glamorous but saves $400 over the weekend per guy.",
    },
    logistics: {
      gettingThere:
        "LAS is 10 min from the strip. Uber/Lyft, don't bother with rentals unless you're going to Shadow Creek or off-strip.",
      gettingAround:
        "Walking the strip is a lie — it takes 25 minutes between casinos. Use the monorail or Uber between properties. Never walk at 3 PM in July.",
      moneyMath:
        "Hotel ~$300/person · Club/dayclub ~$500/person · Food & drinks ~$400/person · Gambling (budgeted) ~$300 · Total: ~$1,500–$2,500 (not incl. flights)",
      bookingTimeline:
        "Big restaurants (Carbone, STK): 4–6 weeks. Nightclub tables: 3+ weeks, or day-of if flexible. UFC/shows: as soon as announced. Hotel: 2 months out for weekends.",
      bestManTips:
        "Set a cap with each guy on gambling up front — it's the thing that ends friendships. Open a group chat that's ONLY for logistics and a separate one for memes, or the real plan gets buried. Don't plan a pool day if it's over 105° — book indoor stuff.",
    },
  },

  // ── Bozeman ────────────────────────────────────────────────────────────
  bozeman: {
    overview:
      "Bozeman is the antidote to the Vegas-Nashville-Scottsdale trifecta. Fly fishing, a Yellowstone day, big downtown Main Street, and a steakhouse dinner you'll remember. It's a long-weekend trip that leaves the crew feeling good rather than wrecked. Best in July–September.",
    sampleItinerary: [
      {
        label: "Day 1",
        title: "Arrive + Settle In",
        body: "Land at BZN by 3. Drive (30 min) to the rental — get a big house in Big Sky or Gallatin Gateway with a hot tub. Grocery stop in downtown Bozeman on the way. First night: grill at the house, bourbon on the porch, stars you can actually see. Low-key on purpose.",
        highlights: [
          { time: "3:00 PM", activity: "Land BZN + rental car pickup" },
          { time: "4:00 PM", activity: "Grocery stop — Town & Country" },
          { time: "5:30 PM", activity: "House check-in + hot tub" },
          { time: "7:30 PM", activity: "Steaks on the grill, cigars outside" },
        ],
      },
      {
        label: "Day 2",
        title: "Fly Fishing Day",
        body: "Early start — 7am pickup by the guide service. Full-day float on the Madison or Yellowstone River — even if half the crew has never fished, the guides handle everything. Lunch is on the river. Back at the house by 4, quick shower, 7pm dinner at Plonk or Open Range in downtown Bozeman. Bars on Main Street after — Pour House is the move for pool tables and cheap beer.",
        highlights: [
          { time: "7:00 AM", activity: "Guide pickup — Gallatin River Guides" },
          { time: "9:00 AM", activity: "Float on the Madison / Yellowstone" },
          { time: "4:30 PM", activity: "Back at the house — shower + regroup" },
          { time: "7:00 PM", activity: "Dinner — Plonk (Main Street)" },
          { time: "9:30 PM", activity: "Pour House → Molly Brown" },
        ],
      },
      {
        label: "Day 3",
        title: "Yellowstone Day",
        body: "Pack lunches, leave the house by 8. 90 min drive to the north entrance (Gardiner). Lamar Valley for wildlife, Mammoth Hot Springs, Grand Prismatic if you push further. Back at the house by 7. Dinner: Blackbird in Bozeman or Buck's T-4 if you stay in Big Sky. This is the day people talk about 3 years later.",
        highlights: [
          { time: "8:00 AM", activity: "Leave for Yellowstone (pack lunches)" },
          { time: "10:00 AM", activity: "Lamar Valley wildlife drive" },
          { time: "2:00 PM", activity: "Mammoth Hot Springs boardwalk" },
          { time: "7:30 PM", activity: "Dinner — Blackbird Kitchen & Bar" },
        ],
      },
      {
        label: "Day 4",
        title: "Brewery + Fly Out",
        body: "Coffee at Wild Joe's. Lunch at Mountains Walking Brewery or Bridger Brewing. Easy afternoon — flights out by 5. If you have time and the groom's into hot springs, Bozeman Hot Springs is 15 min from the airport.",
        highlights: [
          { time: "10:00 AM", activity: "Wild Joe's coffee + stroll Main Street" },
          { time: "12:30 PM", activity: "Lunch — Mountains Walking Brewery" },
          { time: "3:00 PM", activity: "Bozeman Hot Springs (optional)" },
          { time: "5:00 PM", activity: "Fly out of BZN" },
        ],
      },
    ],
    foodAndDrink: [
      {
        category: "anchor_dinner",
        name: "Plonk",
        neighborhood: "Downtown Bozeman (Main Street)",
        priceRange: "$$$",
        perPerson: "$85",
        vibe: "Mountain bistro feel, good wine list, handles a crew of 10 without losing service",
        reservationNote: "2 weeks out for dinner",
        groupNote: "Back room fits 12",
        insiderTip: "Get the bison short rib. The fried brussels are also non-negotiable.",
      },
      {
        category: "group_lunch",
        name: "Mountains Walking Brewery",
        neighborhood: "North Bozeman",
        priceRange: "$$",
        perPerson: "$35",
        vibe: "Big hall, long tables, excellent beer, pizza and food-truck rotation",
        reservationNote: "No reservations — go before noon or after 2",
        groupNote: "Plenty of room for 10+",
        insiderTip: "The lagers are genuinely world-class. Try the pilsner even if you're an IPA guy.",
      },
      {
        category: "morning_after",
        name: "Nova Cafe",
        neighborhood: "Downtown Bozeman",
        priceRange: "$$",
        perPerson: "$22",
        vibe: "Breakfast with actual ingredients — huevos rancheros, big benedicts",
        reservationNote: "Call ahead for 8+, gets busy Sat/Sun",
        insiderTip: "Bison breakfast hash. Hangover cure.",
      },
      {
        category: "steakhouse",
        name: "Open Range",
        neighborhood: "Downtown Bozeman",
        priceRange: "$$$$",
        perPerson: "$120",
        vibe: "Serious steakhouse — dry-aged cuts, deep wine list, dark room",
        reservationNote: "3 weeks out",
        insiderTip: "Order the tomahawk for the table. Ask for the wine director's pick at your price.",
      },
      {
        category: "dive_bar",
        name: "Molly Brown",
        neighborhood: "Downtown Bozeman",
        priceRange: "$",
        perPerson: "$18",
        vibe: "College bar with character — pool, jukebox, cheap drinks, zero pretense",
        reservationNote: "Walk-in",
        insiderTip: "Cash is faster at the bar than the card line. Bring $40.",
      },
      {
        category: "brewery_distillery",
        name: "Wildrye Distilling",
        neighborhood: "Downtown Bozeman",
        priceRange: "$$",
        perPerson: "$30 tasting flight",
        vibe: "Small batch Montana whiskey — tasting room is low-key and the staff tells you everything",
        reservationNote: "Walk-in, reserve tasting for 8+",
        insiderTip: "The wheat whiskey is the sleeper — not available outside the region.",
      },
    ],
    activities: [
      {
        category: "water",
        name: "Full-day guided fly fishing float",
        costPerPerson: "$550 (2 per boat, tip included)",
        groupSize: "2 per boat — book 3–4 boats for a crew of 8",
        bookingLead: "60+ days out for July–Aug",
        duration: "8 hours",
        intensity: "moderate",
        weatherDependent: true,
        interestTags: ["fishing"],
        note: "Gallatin River Guides or Bozeman Fly Supply are the go-tos. No experience needed.",
      },
      {
        category: "unique",
        name: "Yellowstone wildlife day",
        costPerPerson: "$50 (gas + park pass per car)",
        groupSize: "Any",
        bookingLead: "None",
        duration: "Full day (leave by 8)",
        intensity: "easy",
        weatherDependent: true,
        interestTags: ["hiking"],
        note: "North entrance (Gardiner) — Lamar Valley for bison, wolves, bears. Pack sandwiches.",
      },
      {
        category: "adrenaline",
        name: "Whitewater rafting — Gallatin River",
        costPerPerson: "$95",
        groupSize: "Up to 16",
        bookingLead: "2 weeks out",
        duration: "Half day",
        intensity: "moderate",
        weatherDependent: true,
      },
      {
        category: "chill",
        name: "Bozeman Hot Springs",
        costPerPerson: "$15",
        groupSize: "Any",
        bookingLead: "Walk-up",
        duration: "2 hours",
        intensity: "easy",
        weatherDependent: false,
        note: "Less scenic than Chico Hot Springs but 15 min from the airport — perfect for departure day.",
      },
      {
        category: "food_drink",
        name: "Brewery crawl (Bridger → Mountains Walking → Bozeman Brewing)",
        costPerPerson: "$60",
        groupSize: "Any",
        bookingLead: "None",
        duration: "Afternoon",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["craft_beer"],
      },
      {
        category: "competitive",
        name: "Sporting clays — Gallatin Gun Club",
        costPerPerson: "$75 (incl. shells)",
        groupSize: "Up to 12",
        bookingLead: "1 week out",
        duration: "2 hours",
        intensity: "easy",
        weatherDependent: true,
        interestTags: ["hunting"],
      },
      {
        category: "unique",
        name: "Chico Hot Springs dinner + soak",
        costPerPerson: "$95",
        groupSize: "Any",
        bookingLead: "3 weeks out for dinner",
        duration: "Evening (60 min drive each way)",
        intensity: "easy",
        weatherDependent: false,
        note: "1 hour drive to Pray, MT. Historic resort — dinner is legit. Makes a great last night.",
      },
    ],
    accommodation: {
      house:
        "Rent a 5–6 BR cabin in Gallatin Gateway or Big Sky — $600–$900/night, splits nicely for 8 guys. Look for hot tub + mountain view + grill.",
      hotel:
        "Element by Westin or Kimpton Armory downtown — walkable to Main Street for bars, ~$250/night.",
      upgrade:
        "Lone Mountain Ranch or The Ranch at Rock Creek — $600–$1200/person/night, all-inclusive luxury ranch. Overkill unless the crew is dialed in.",
      budget: "Downtown Bozeman hostel or the La Quinta on 7th — $120/night room, clean, nothing special.",
    },
    logistics: {
      gettingThere:
        "Fly BZN. It's a small airport — book direct from Denver, Seattle, Salt Lake, Chicago, Minneapolis, or Dallas. Budget in the rental car line if you're not first off the plane.",
      gettingAround:
        "Rent cars — you need them. One big SUV for the crew + one backup is the move. Yellowstone is 90 min, fishing put-ins are 30–60 min, Bozeman downtown is 15 min from Big Sky.",
      moneyMath:
        "House ~$250/person · Fishing ~$350/person · Food & drinks ~$300/person · Park/activity costs ~$100 · Rental car split ~$80 · Total: ~$1,100–$1,400 (not incl. flights)",
      bookingTimeline:
        "Fishing guides: 60+ days out for peak summer. House: 90 days out for July–Aug. Anchor dinner: 3 weeks. Yellowstone: just show up, no reservation needed for drive-thrus.",
      bestManTips:
        "Assign one guy to drive each day — swap. Nobody should be driving after 2 beers on mountain roads. Check the fire situation (Inciweb) if you're going Aug–Sept. If smoke is bad, pivot to indoor activities.",
    },
  },

  // ── Lake Tahoe ─────────────────────────────────────────────────────────
  tahoe: {
    overview:
      "Tahoe is a cheat code for the crew that wants outdoors without 'roughing it.' Lakefront rental, a boat charter, a good grill, and a poker table are the whole plan. Summer = boat + lake days; winter = ski + hot tub. Both are great. Avoid shoulder seasons.",
    sampleItinerary: [
      {
        label: "Day 1",
        title: "Lake House Roll In",
        body: "Drive or fly in by 3. Check into the lakefront house — hot tub is mandatory, private dock is the dream. Unpack, stock the fridge (Raley's on the way up), first round of beers on the deck. Evening grill + poker night. If someone forgot their swimsuit, don't swim.",
        highlights: [
          { time: "3:00 PM", activity: "House check-in — lakefront in Incline or Tahoma" },
          { time: "4:30 PM", activity: "Grocery stop + liquor run" },
          { time: "6:00 PM", activity: "Beers on the deck, sunset over the lake" },
          { time: "8:00 PM", activity: "Grill + poker night at the house" },
        ],
      },
      {
        label: "Day 2",
        title: "Boat Day",
        body: "This is the day. Book an 8-hour boat charter — pontoon with captain and cooler. Launch by 10, anchor at Sand Harbor or Emerald Bay for cliff jumping. Lunch on board, music going, rotations of swimming and sitting. Back to the dock by 6. Dinner: Lone Eagle Grille at Hyatt Incline (slightly dressy, worth it) or grill again if the crew's wiped. Late-night poker or a bonfire.",
        highlights: [
          { time: "9:00 AM", activity: "Breakfast at the house" },
          { time: "10:00 AM", activity: "Boat charter launch — 8 hour block" },
          { time: "12:30 PM", activity: "Lunch on the water, cliff jumping at Hidden Beach" },
          { time: "6:30 PM", activity: "Dinner — Lone Eagle Grille (waterfront)" },
          { time: "9:30 PM", activity: "Bonfire + whiskey at the house" },
        ],
      },
      {
        label: "Day 3",
        title: "Choose Your Own",
        body: "Split day based on energy. Active option: hike Eagle Falls (2 hours, easy) or Mt. Tallac (all day, serious). Chill option: paddleboards from the dock + beers. Or: drive 30 min to Reno for casino night at Peppermill or GSR — cheaper tables than Vegas, less intense, good for a crew that wants to gamble without committing to the Strip. Dinner back at the house: order pizza from Base Camp, light the fire pit.",
        highlights: [
          { time: "9:30 AM", activity: "Breakfast + split into active/chill groups" },
          { time: "10:30 AM", activity: "Active: Eagle Falls hike | Chill: paddleboards" },
          { time: "3:00 PM", activity: "Back at the house — hot tub" },
          { time: "6:30 PM", activity: "Pizza + fire pit" },
          { time: "9:00 PM", activity: "Optional: Reno casino run" },
        ],
      },
      {
        label: "Day 4",
        title: "Send-Off",
        body: "Slow coffee morning. Clean-up duty split among the crew (someone's getting the deposit back). Brunch at Fire Sign Cafe if you're on the west shore. Drive or fly out by 2. That's a weekend.",
        highlights: [
          { time: "9:30 AM", activity: "Coffee + clean up" },
          { time: "11:30 AM", activity: "Brunch — Fire Sign Cafe" },
          { time: "1:30 PM", activity: "Head out" },
        ],
      },
    ],
    foodAndDrink: [
      {
        category: "anchor_dinner",
        name: "Lone Eagle Grille",
        neighborhood: "Incline Village (north shore)",
        priceRange: "$$$",
        perPerson: "$95",
        vibe: "Waterfront lodge feel, fireplaces, sunset views — actually romantic but works for groups",
        reservationNote: "3 weeks out",
        groupNote: "Private dining alcove seats 12",
        insiderTip: "Request a table on the lake side by name when you book.",
      },
      {
        category: "group_lunch",
        name: "Jake's on the Lake",
        neighborhood: "Tahoe City (north shore)",
        priceRange: "$$",
        perPerson: "$45",
        vibe: "Classic Tahoe lakefront lunch spot, deck tables, boats pull up to the dock",
        reservationNote: "Call ahead for 8+",
        groupNote: "Deck works for 10+",
        insiderTip: "Fish tacos. Boat-up service if you're on the water.",
      },
      {
        category: "morning_after",
        name: "Fire Sign Cafe",
        neighborhood: "Tahoe City",
        priceRange: "$",
        perPerson: "$22",
        vibe: "Log-cabin breakfast joint, mountain-sized portions, worth the 30 min wait",
        reservationNote: "No reservations — go before 9 or after 11:30",
        insiderTip: "Scramble with housemade sausage. Plus a short stack.",
      },
      {
        category: "dive_bar",
        name: "Fiddle Creek Saloon",
        neighborhood: "Kings Beach",
        priceRange: "$",
        perPerson: "$18",
        vibe: "Locals' spot — pool tables, cheap beer, character",
        reservationNote: "Walk-in",
        insiderTip: "Play pool. Don't hustle — this is a regular's place and they'll remember.",
      },
      {
        category: "steakhouse",
        name: "Soule Domain",
        neighborhood: "Crystal Bay",
        priceRange: "$$$$",
        perPerson: "$110",
        vibe: "Old-school Tahoe dinner — log cabin, excellent wine list",
        reservationNote: "4 weeks out",
        insiderTip: "Pair with a drive over to Crystal Bay Club for a drink after — old-school casino vibe.",
      },
      {
        category: "late_night",
        name: "Base Camp Pizza",
        neighborhood: "Heavenly Village (south shore) / various",
        priceRange: "$",
        perPerson: "$18",
        vibe: "Legit NY-style pizza, open late, delivers to lakefront rentals",
        reservationNote: "Walk-in or delivery",
        insiderTip: "The honey pepperoni slice is the move.",
      },
      {
        category: "brewery_distillery",
        name: "Alibi Ale Works",
        neighborhood: "Incline Village (also Truckee)",
        priceRange: "$",
        perPerson: "$25 with flight",
        vibe: "Local Tahoe brewery, easygoing tasting room, live music on weekends",
        reservationNote: "Walk-in",
        insiderTip: "The pilsner is underrated. Grab a growler for the house.",
      },
    ],
    activities: [
      {
        category: "water",
        name: "8-hour pontoon boat charter with captain",
        costPerPerson: "$180 (8-guy split)",
        groupSize: "10–14 max on a big pontoon",
        bookingLead: "6+ weeks out for summer weekends",
        duration: "8 hours",
        intensity: "easy",
        weatherDependent: true,
        interestTags: ["water_sports"],
        note: "Action Watersports in Zephyr Cove or Lake Tahoe Boat Rentals. Get the captain — don't pilot yourself.",
      },
      {
        category: "water",
        name: "Paddleboards + kayaks (half day)",
        costPerPerson: "$60",
        groupSize: "Any",
        bookingLead: "2 days out",
        duration: "Half day",
        intensity: "moderate",
        weatherDependent: true,
      },
      {
        category: "adrenaline",
        name: "Jet ski rentals (Zephyr Cove)",
        costPerPerson: "$200",
        groupSize: "1–2 per ski",
        bookingLead: "1 week out",
        duration: "2 hours",
        intensity: "full_send",
        weatherDependent: true,
      },
      {
        category: "competitive",
        name: "Round at Incline Championship Course",
        costPerPerson: "$200",
        groupSize: "Foursomes",
        bookingLead: "2 weeks out",
        duration: "5 hours",
        intensity: "easy",
        weatherDependent: true,
        interestTags: ["golf"],
      },
      {
        category: "chill",
        name: "Hike Eagle Falls / Emerald Bay",
        costPerPerson: "Free",
        groupSize: "Any",
        bookingLead: "None",
        duration: "2 hours",
        intensity: "moderate",
        weatherDependent: true,
        interestTags: ["hiking"],
      },
      {
        category: "nightlife",
        name: "Reno casino run (Peppermill or GSR)",
        costPerPerson: "Buy-in varies",
        groupSize: "Any",
        bookingLead: "None",
        duration: "Evening (45 min drive)",
        intensity: "moderate",
        weatherDependent: false,
        interestTags: ["poker"],
        note: "Cheaper tables than Vegas. Good for a change-up if the lake house is starting to feel small.",
      },
      {
        category: "unique",
        name: "Sand Harbor Shakespeare (summer)",
        costPerPerson: "$85",
        groupSize: "Any",
        bookingLead: "4 weeks out",
        duration: "Evening",
        intensity: "easy",
        weatherDependent: true,
        note: "Lake-edge amphitheater. Pack a picnic + bottle of wine. Niche but unforgettable.",
      },
      {
        category: "sports_events",
        name: "Heavenly / Palisades skiing (winter)",
        costPerPerson: "$180 day pass",
        groupSize: "Any",
        bookingLead: "2 days out (get Epic/Ikon season pass if it's a ski trip)",
        duration: "Full day",
        intensity: "moderate",
        weatherDependent: true,
        interestTags: ["skiing"],
      },
    ],
    accommodation: {
      house:
        "Lakefront in Incline (north), Tahoma, or Homewood (west shore). 5–6 BR houses with private beaches run $1,200–$2,500/night — splits to $100–$200/person/night. Private dock is worth the premium if you can swing it.",
      hotel:
        "Ritz-Carlton Lake Tahoe if you want luxury. Hyatt Regency Incline for mid-tier. Not a hotel trip at heart — go house.",
      upgrade:
        "Private lakefront estate via Lake Tahoe Vacation Rentals — $3,000+/night, worth it for 12+ guys.",
      budget: "Kings Beach or South Lake Tahoe studio-style rentals — $150/night. Further from the good stuff but fine.",
    },
    logistics: {
      gettingThere:
        "Fly into Reno (RNO) — 45 min to north shore. Sacramento (SMF) is 2 hours. Drivable from SF Bay Area in 3–4 hours.",
      gettingAround:
        "Rent cars. One big SUV + one backup. Ubers are scarce outside the main areas. If you're lakefront in Incline, you can walk to bars.",
      moneyMath:
        "House ~$250/person · Boat day ~$200/person · Food & drinks ~$280/person · Activities ~$150/person · Car split ~$60 · Total: ~$900–$1,200 (not incl. flights)",
      bookingTimeline:
        "House: 90+ days out for summer. Boat charter: 6+ weeks out. Anchor dinner: 3 weeks. In winter add ski passes a month out for discounts.",
      bestManTips:
        "Assign 'boat captain' duties — who's in charge of the cooler, who's handling the speaker, who's bringing the tube. The lake-day logistics matter more than the activity itself. Check the weather the week before — afternoon thunderstorms can shut down the boat day.",
    },
  },

  // ── Louisville ─────────────────────────────────────────────────────────
  louisville: {
    overview:
      "Louisville is the stealth bachelor play — bourbon trail, Churchill Downs energy, great steakhouses, and a downtown that's walkable without being touristy. Perfect for the groom who's into whiskey and would rather spend time talking than yelling over club music. Book around Derby week (May) only if you want to pay 3x.",
    sampleItinerary: [
      {
        label: "Day 1",
        title: "Downtown Arrival",
        body: "Land by 3. Check into a downtown hotel or a NuLu townhouse. First stop: walk NuLu's shops and duck into a cocktail bar — Hell or High Water is the move, speakeasy-style. Dinner at Jeff Ruby's. Night cap at Pat's Steakhouse downstairs bar or head to 4th Street Live if you need a louder vibe (you won't).",
        highlights: [
          { time: "3:30 PM", activity: "Check in — NuLu or downtown" },
          { time: "5:30 PM", activity: "Hell or High Water speakeasy cocktail" },
          { time: "7:30 PM", activity: "Dinner — Jeff Ruby's Steakhouse" },
          { time: "10:00 PM", activity: "Night cap + cigars on a rooftop (Hotel Distil or Proof on Main)" },
        ],
      },
      {
        label: "Day 2",
        title: "Bourbon Trail Day",
        body: "This is the trip's calling card. Book a private driver or a bourbon trail tour (Mint Julep Tours is the reputable one). Hit 3–4 distilleries — the right combo is Buffalo Trace (go early to beat crowds), Maker's Mark (lunch break — they have a legit dining room), and either Woodford Reserve (photogenic) or Willett (lesser-known, better whiskey). Back by 6. Dinner at Butchertown Grocery. Late drinks at The Silver Dollar for honky-tonk country energy.",
        highlights: [
          { time: "8:30 AM", activity: "Driver pickup (don't drive — you're tasting)" },
          { time: "9:30 AM", activity: "Buffalo Trace tour + tasting" },
          { time: "12:30 PM", activity: "Lunch at Maker's Mark or Star Hill Provisions" },
          { time: "2:30 PM", activity: "Willett or Woodford Reserve" },
          { time: "7:30 PM", activity: "Dinner — Butchertown Grocery" },
          { time: "10:00 PM", activity: "The Silver Dollar — honky-tonk drinks" },
        ],
      },
      {
        label: "Day 3",
        title: "Churchill + Send-Off",
        body: "Late breakfast at Wagner's Pharmacy (across from Churchill Downs). Tour Churchill Downs or, if there's live racing that day, make an afternoon of it — wear something nice-ish, bet small, drink mint juleps. Lunch nearby. Head to airport by 3.",
        highlights: [
          { time: "10:00 AM", activity: "Breakfast — Wagner's Pharmacy" },
          { time: "11:30 AM", activity: "Churchill Downs tour OR live racing" },
          { time: "2:30 PM", activity: "Lunch near the track" },
          { time: "4:00 PM", activity: "Fly out of SDF" },
        ],
      },
    ],
    foodAndDrink: [
      {
        category: "anchor_dinner",
        name: "Jeff Ruby's Steakhouse",
        neighborhood: "Downtown Louisville",
        priceRange: "$$$$",
        perPerson: "$160",
        vibe: "Old-school Jeff Ruby steakhouse template — leather, low light, jackets preferred",
        reservationNote: "3 weeks out; dress the part",
        groupNote: "Private dining fits 12",
        insiderTip: "Bourbon selection is stacked — ask for a rare pour and the sommelier lights up.",
      },
      {
        category: "group_lunch",
        name: "Butchertown Grocery",
        neighborhood: "Butchertown",
        priceRange: "$$$",
        perPerson: "$65",
        vibe: "Modern Southern — can do casual lunch or serious dinner depending on the crew",
        reservationNote: "2 weeks out",
        groupNote: "Patio fits 14",
        insiderTip: "The fried chicken sandwich is a quiet masterpiece.",
      },
      {
        category: "morning_after",
        name: "Wagner's Pharmacy",
        neighborhood: "Across from Churchill Downs",
        priceRange: "$",
        perPerson: "$18",
        vibe: "Pharmacy-turned-diner from 1922 — where jockeys and trainers still eat",
        reservationNote: "Walk-in, no reservations ever",
        insiderTip: "Sit at the counter. Listen. The horse racing talk is its own entertainment.",
      },
      {
        category: "dive_bar",
        name: "Pat's Steakhouse (bar side)",
        neighborhood: "Louisville Blvd",
        priceRange: "$",
        perPerson: "$20",
        vibe: "1950s neighborhood bar — longest-running in Louisville, zero changes",
        reservationNote: "Walk-in",
        insiderTip: "Old-fashioned done right, cheap. Eat the fried chicken at the bar.",
      },
      {
        category: "steakhouse",
        name: "610 Magnolia",
        neighborhood: "Old Louisville",
        priceRange: "$$$$",
        perPerson: "$145",
        vibe: "Ed Lee's Southern tasting menu — if you want something memorable beyond steak",
        reservationNote: "4 weeks out",
        insiderTip: "Do the full tasting. This is the restaurant in town.",
      },
      {
        category: "brewery_distillery",
        name: "Kentucky Peerless Distillery",
        neighborhood: "Downtown",
        priceRange: "$",
        perPerson: "$20 tour",
        vibe: "Small, honest, city-based distillery with an excellent bourbon — skippable on the bourbon trail but worth a visit in town",
        reservationNote: "2 weeks out for tours",
        insiderTip: "Buy a bottle — the double barrel is only sold at the distillery.",
      },
    ],
    activities: [
      {
        category: "food_drink",
        name: "Bourbon trail — private driver + 3–4 distilleries",
        costPerPerson: "$300 (driver split + tour fees)",
        groupSize: "10–12 (bigger = multiple vans)",
        bookingLead: "6+ weeks out",
        duration: "Full day",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["bourbon"],
        note: "Mint Julep Tours or Louisville Loves Bourbon. Don't try to drive yourself.",
      },
      {
        category: "sports_events",
        name: "Churchill Downs live racing",
        costPerPerson: "$20–80 (seats)",
        groupSize: "Any",
        bookingLead: "Check the schedule — Thu/Fri/Sat racing in spring/fall",
        duration: "Half day",
        intensity: "easy",
        weatherDependent: true,
        interestTags: ["cars_racing"],
        note: "If the dates line up, this is the trip's highlight. Pack a sportcoat.",
      },
      {
        category: "food_drink",
        name: "Urban Bourbon Trail (downtown)",
        costPerPerson: "$80",
        groupSize: "Any",
        bookingLead: "None",
        duration: "Afternoon/evening",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["bourbon"],
        note: "Self-guided: Proof on Main → The Brown Hotel Lobby Bar → Silver Dollar → Hell or High Water",
      },
      {
        category: "unique",
        name: "Louisville Slugger factory tour",
        costPerPerson: "$20",
        groupSize: "Any",
        bookingLead: "1 week out",
        duration: "90 minutes",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["sports_watching"],
      },
      {
        category: "competitive",
        name: "Valhalla Golf Club (PGA course)",
        costPerPerson: "$300 (member guest rules apply)",
        groupSize: "Foursomes",
        bookingLead: "30 days out, need member referral",
        duration: "5 hours",
        intensity: "easy",
        weatherDependent: true,
        interestTags: ["golf"],
        note: "If no Valhalla access, Standard Country Club or Hurstbourne are solid public options",
      },
      {
        category: "competitive",
        name: "Cigar poker night at the house",
        costPerPerson: "$40 (buy-in + cigars)",
        groupSize: "6–10",
        bookingLead: "None",
        duration: "Evening",
        intensity: "easy",
        weatherDependent: false,
        interestTags: ["poker", "cigars"],
      },
    ],
    accommodation: {
      house:
        "NuLu townhouses — walkable to downtown bars and distillery row, 4–6 BR rentals for $800–$1,400/night.",
      hotel:
        "Hotel Distil (Autograph Collection) — whiskey-themed boutique on Whiskey Row, bar downstairs is a destination. ~$300/night.",
      upgrade:
        "The Brown Hotel — historic, clean, legendary lobby bar. Perfect for a crew that wants old-school Louisville.",
      budget: "Holiday Inn Express downtown — fine, walkable, $150/night.",
    },
    logistics: {
      gettingThere:
        "Fly SDF. Small airport, 15 min from downtown. Ubers and Lyfts are plentiful.",
      gettingAround:
        "Downtown + NuLu are walkable. Bourbon trail is 60-90 min out of the city — private driver essential.",
      moneyMath:
        "Hotel ~$250/person · Bourbon trail ~$300/person · Food & drinks ~$300/person · Activities ~$150/person · Total: ~$1,000–$1,300 (not incl. flights)",
      bookingTimeline:
        "Bourbon trail: 6+ weeks. Anchor dinner: 3–4 weeks. Hotel: 4 weeks out, longer if Derby-adjacent. Avoid Derby week (first Saturday in May) unless that IS the plan.",
      bestManTips:
        "Pace the whiskey — 4 distilleries in a day with full pours is a lot. Eat the lunch at Maker's Mark, hydrate, and keep taking water between tastings. Save the cigars for the evening.",
    },
  },
};

export function getPlaybook(
  destinationId: string,
): DestinationPlaybook | undefined {
  return PLAYBOOKS[destinationId];
}
