// ── Documents vault seed data ──────────────────────────────────────────────
// A handful of realistic pre-filed documents so the canvas isn't empty on
// first load. Mirrors what the Haiku classifier would produce after a real
// upload.

import type { DocumentRecord } from "@/types/documents";
import { folderPathFor } from "@/types/documents";

function doc(
  overrides: Partial<DocumentRecord> & Pick<DocumentRecord, "id" | "name" | "document_type" | "vendor_category" | "folder">,
): DocumentRecord {
  const base: DocumentRecord = {
    id: overrides.id,
    name: overrides.name,
    file_url: `/uploads/seed-${overrides.id}.pdf`,
    mime_type: "application/pdf",
    size_bytes: 180_000,
    document_type: overrides.document_type,
    vendor_category: overrides.vendor_category,
    vendor_name: null,
    folder_path: folderPathFor(overrides.folder, overrides.vendor_category),
    folder: overrides.folder,
    financial: false,
    amount: null,
    currency: null,
    document_date: null,
    due_date: null,
    event_date: "2026-05-12",
    expiration_date: null,
    parties: [],
    signed: null,
    key_terms: [],
    summary: "",
    tags: [],
    confidence_overall: 0.92,
    needs_review: false,
    review_reason: null,
    uploaded_by: "priya",
    uploaded_at: "2026-03-02T14:00:00.000Z",
    updated_at: "2026-03-02T14:00:00.000Z",
  };
  return { ...base, ...overrides };
}

export const SEED_DOCUMENTS: DocumentRecord[] = [
  doc({
    id: "d_contract_moksha",
    name: "Moksha Studios — Photography Contract.pdf",
    document_type: "contract",
    vendor_category: "photography",
    vendor_name: "Moksha Studios",
    folder: "contracts",
    financial: true,
    amount: 850_000,
    currency: "INR",
    document_date: "2026-01-14",
    signed: true,
    parties: ["Priya Menon", "Moksha Studios"],
    key_terms: ["3-day coverage", "50% deposit", "Raw + edits in 8 weeks"],
    summary:
      "Three-day wedding coverage across Haldi, Wedding, and Reception. Includes drone, second shooter, and 500+ edited images delivered within 8 weeks.",
    tags: ["photography", "signed"],
    uploaded_at: "2026-01-14T10:20:00.000Z",
    updated_at: "2026-01-14T10:20:00.000Z",
  }),
  doc({
    id: "d_invoice_bloom",
    name: "Bloom & Vine — Mandap Florals Invoice.pdf",
    document_type: "invoice",
    vendor_category: "decor_florals",
    vendor_name: "Bloom & Vine",
    folder: "invoices_receipts",
    financial: true,
    amount: 425_000,
    currency: "INR",
    document_date: "2026-03-20",
    due_date: "2026-04-15",
    parties: ["Bloom & Vine"],
    key_terms: ["Mandap + reception stage", "50% on signing", "Balance day-of"],
    summary:
      "Invoice for mandap and reception stage florals. Covers jasmine, marigold cascades, and orchid installations.",
    tags: ["florals", "unpaid"],
    uploaded_at: "2026-03-20T08:45:00.000Z",
    updated_at: "2026-03-20T08:45:00.000Z",
  }),
  doc({
    id: "d_receipt_catering",
    name: "Spice Route — Tasting Deposit Receipt.pdf",
    document_type: "receipt",
    vendor_category: "catering",
    vendor_name: "Spice Route Catering",
    folder: "invoices_receipts",
    financial: true,
    amount: 25_000,
    currency: "INR",
    document_date: "2026-02-08",
    tags: ["catering", "paid"],
    summary: "Receipt for the six-course tasting on Feb 12. Applied toward final catering invoice.",
    uploaded_at: "2026-02-08T17:10:00.000Z",
    updated_at: "2026-02-08T17:10:00.000Z",
  }),
  doc({
    id: "d_coi_venue",
    name: "Amrit Bagh — Certificate of Insurance.pdf",
    document_type: "coi",
    vendor_category: "venue",
    vendor_name: "Amrit Bagh",
    folder: "legal_admin",
    document_date: "2026-02-01",
    expiration_date: "2027-02-01",
    parties: ["Amrit Bagh"],
    summary: "General liability COI issued for the wedding weekend. Valid through Feb 2027.",
    tags: ["venue", "compliance"],
    uploaded_at: "2026-02-01T12:00:00.000Z",
    updated_at: "2026-02-01T12:00:00.000Z",
  }),
  doc({
    id: "d_shotlist",
    name: "Must-Capture Shot List — Draft v2.pdf",
    document_type: "shot_list",
    vendor_category: "photography",
    vendor_name: "Moksha Studios",
    folder: "planning",
    event_date: "2026-05-12",
    summary: "Draft shot list covering family portraits, pheras, and reception first dance. Sent to lead photographer for sign-off.",
    tags: ["photography", "planning"],
    uploaded_at: "2026-03-28T09:30:00.000Z",
    updated_at: "2026-03-28T09:30:00.000Z",
  }),
  doc({
    id: "d_seating_ballroom",
    name: "Reception Seating Chart — Ballroom A.pdf",
    document_type: "seating_chart",
    vendor_category: "venue",
    vendor_name: "Amrit Bagh",
    folder: "planning",
    event_date: "2026-05-12",
    summary: "Draft seating chart for the reception ballroom. 18 rounds of 10, head table of 12.",
    tags: ["reception", "seating"],
    uploaded_at: "2026-04-02T15:00:00.000Z",
    updated_at: "2026-04-02T15:00:00.000Z",
  }),
  doc({
    id: "d_unsorted_receipt",
    name: "IMG_2381.jpg",
    document_type: "other",
    vendor_category: "other",
    vendor_name: null,
    folder: "unsorted",
    mime_type: "image/jpeg",
    size_bytes: 2_400_000,
    confidence_overall: 0.34,
    needs_review: true,
    review_reason: "Low confidence on document type and vendor. Could be a receipt photo or random image.",
    summary: "Handwritten receipt photo — vendor unclear.",
    tags: [],
    uploaded_at: "2026-04-10T19:22:00.000Z",
    updated_at: "2026-04-10T19:22:00.000Z",
  }),
];
