// ── Finance seed data ──────────────────────────────────────────────────────
// Realistic v1 data for a $500K luxury wedding. Mirrors what a real Supabase
// query would return after the module goes live. Totals are tuned so the
// Overview stat tiles land on clean numbers.

import type {
  AllocationPreset,
  FinanceBudget,
  FinanceCategory,
  FinanceContributor,
  FinanceContributorAllocation,
  FinanceEvent,
  FinanceInvoice,
  FinancePayment,
  FinanceSettings,
  FinanceTransaction,
} from "@/types/finance";
import {
  DEFAULT_CATEGORY_SLUGS,
  DEFAULT_WEDDING_ID,
  FINANCE_CATEGORY_LABEL,
  FINANCE_CATEGORY_TINT,
  SPEC_DEFAULT_EVENTS,
  SPEC_DEFAULT_PERCENTAGES,
} from "@/types/finance";

const W = DEFAULT_WEDDING_ID;

// Sums to $501,500 across the 12 workspace categories — round enough.
export const SEED_FINANCE_BUDGETS: FinanceBudget[] = [
  { wedding_id: W, category_id: "venue", allocated_cents: 12_500_000, notes: "Main ballroom + garden ceremony site. Weekend rate.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "catering", allocated_cents: 11_500_000, notes: "3 events, ~350 covers total, full bar.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "decor_florals", allocated_cents: 7_500_000, notes: "Mandap, reception install, florals across 4 events.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "photography", allocated_cents: 4_500_000, notes: "3-day coverage + albums + engagement session.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "videography", allocated_cents: 3_000_000, notes: "Cinematic film + same-day edit.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "entertainment", allocated_cents: 3_500_000, notes: "DJ + live band for sangeet + dhol for baraat.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "hmua", allocated_cents: 1_800_000, notes: "Bride + bridal party, 3 events.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "wardrobe", allocated_cents: 2_500_000, notes: "Bride's lehenga + reception gown + groom's sherwanis.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "stationery", allocated_cents: 900_000, notes: "Save-the-dates, suites, event cards, day-of paper.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "mehndi", allocated_cents: 350_000, notes: "Bridal + guest queue artists.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "transportation", allocated_cents: 750_000, notes: "Guest shuttles, VIP cars, baraat horse.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "pandit_ceremony", allocated_cents: 1_350_000, notes: "Pandit, samagri, ceremonial essentials.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "jewelry", allocated_cents: 4_000_000, notes: "Bridal sets + heirloom rentals + insurance.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "cake_sweets", allocated_cents: 600_000, notes: "Reception cake + mithai + dessert tables.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "gifting", allocated_cents: 900_000, notes: "Welcome bags, favors, trousseau packaging, family exchanges.", updated_at: "2026-02-10T10:00:00.000Z" },
  { wedding_id: W, category_id: "travel_accommodations", allocated_cents: 2_800_000, notes: "Hotel room blocks, group flights, shuttle vendor.", updated_at: "2026-02-10T10:00:00.000Z" },
];

// ── Invoices ──────────────────────────────────────────────────────────────
// Mix of states to demo all filters. Dates are relative to 2026-04-18 (today).

export const SEED_FINANCE_INVOICES: FinanceInvoice[] = [
  {
    id: "inv_01",
    wedding_id: W,
    vendor_id: null,
    vendor_name_fallback: "Bay View Estate",
    category_id: "venue",
    invoice_number: "BVE-2026-0042",
    amount_cents: 6_000_000,
    due_date: "2026-02-01",
    status: "paid",
    pdf_url: null,
    pdf_filename: null,
    notes: "Venue deposit, 50%.",
    event_splits: [],
    extracted_data_jsonb: null,
    created_at: "2026-01-20T10:00:00.000Z",
    updated_at: "2026-02-01T10:00:00.000Z",
  },
  {
    id: "inv_02",
    wedding_id: W,
    vendor_id: null,
    vendor_name_fallback: "Saffron & Sage Catering",
    category_id: "catering",
    invoice_number: "SS-2026-112",
    amount_cents: 2_500_000,
    due_date: "2026-03-15",
    status: "paid",
    pdf_url: null,
    pdf_filename: null,
    notes: "Tasting + 25% deposit.",
    event_splits: [],
    extracted_data_jsonb: null,
    created_at: "2026-02-25T10:00:00.000Z",
    updated_at: "2026-03-15T10:00:00.000Z",
  },
  {
    id: "inv_03",
    wedding_id: W,
    vendor_id: null,
    vendor_name_fallback: "Mira Studio",
    category_id: "photography",
    invoice_number: "MS-039",
    amount_cents: 1_800_000,
    due_date: "2026-03-30",
    status: "paid",
    pdf_url: null,
    pdf_filename: null,
    notes: "Photography retainer, 40%.",
    event_splits: [],
    extracted_data_jsonb: null,
    created_at: "2026-03-10T10:00:00.000Z",
    updated_at: "2026-03-30T10:00:00.000Z",
  },
  {
    id: "inv_04",
    wedding_id: W,
    vendor_id: null,
    vendor_name_fallback: "Kalyana Florals",
    category_id: "decor_florals",
    invoice_number: "KF-2026-08",
    amount_cents: 2_250_000,
    due_date: "2026-04-22",
    status: "approved",
    pdf_url: null,
    pdf_filename: null,
    notes: "Décor 30% deposit — due in 4 days.",
    event_splits: [],
    extracted_data_jsonb: null,
    created_at: "2026-03-28T10:00:00.000Z",
    updated_at: "2026-04-01T10:00:00.000Z",
  },
  {
    id: "inv_05",
    wedding_id: W,
    vendor_id: null,
    vendor_name_fallback: "Rhythm House DJ",
    category_id: "entertainment",
    invoice_number: "RH-115",
    amount_cents: 875_000,
    due_date: "2026-04-25",
    status: "approved",
    pdf_url: null,
    pdf_filename: null,
    notes: "Sangeet DJ deposit.",
    event_splits: [],
    extracted_data_jsonb: null,
    created_at: "2026-04-01T10:00:00.000Z",
    updated_at: "2026-04-05T10:00:00.000Z",
  },
  {
    id: "inv_06",
    wedding_id: W,
    vendor_id: null,
    vendor_name_fallback: "Studio Nirmaan (Stationery)",
    category_id: "stationery",
    invoice_number: "SN-021",
    amount_cents: 425_000,
    due_date: "2026-04-14",
    status: "overdue",
    pdf_url: null,
    pdf_filename: null,
    notes: "Final invitation print run — 4 days overdue.",
    event_splits: [],
    extracted_data_jsonb: null,
    created_at: "2026-03-20T10:00:00.000Z",
    updated_at: "2026-04-14T10:00:00.000Z",
  },
  {
    id: "inv_07",
    wedding_id: W,
    vendor_id: null,
    vendor_name_fallback: "Anaya Couture",
    category_id: "wardrobe",
    invoice_number: "AC-2026-03",
    amount_cents: 1_250_000,
    due_date: "2026-05-05",
    status: "awaiting_approval",
    pdf_url: null,
    pdf_filename: null,
    notes: "Bridal lehenga final payment.",
    event_splits: [],
    extracted_data_jsonb: null,
    created_at: "2026-04-10T10:00:00.000Z",
    updated_at: "2026-04-10T10:00:00.000Z",
  },
  {
    id: "inv_08",
    wedding_id: W,
    vendor_id: null,
    vendor_name_fallback: "Glam Arc HMUA",
    category_id: "hmua",
    invoice_number: "GA-09",
    amount_cents: 540_000,
    due_date: "2026-05-12",
    status: "draft",
    pdf_url: null,
    pdf_filename: null,
    notes: "Trial + 3-event package quote.",
    event_splits: [],
    extracted_data_jsonb: null,
    created_at: "2026-04-12T10:00:00.000Z",
    updated_at: "2026-04-12T10:00:00.000Z",
  },
  {
    id: "inv_09",
    wedding_id: W,
    vendor_id: null,
    vendor_name_fallback: "FrameStory Films",
    category_id: "videography",
    invoice_number: "FS-2026-11",
    amount_cents: 1_200_000,
    due_date: "2026-05-01",
    status: "approved",
    pdf_url: null,
    pdf_filename: null,
    notes: "Videography deposit.",
    event_splits: [],
    extracted_data_jsonb: null,
    created_at: "2026-04-05T10:00:00.000Z",
    updated_at: "2026-04-08T10:00:00.000Z",
  },
  {
    id: "inv_10",
    wedding_id: W,
    vendor_id: null,
    vendor_name_fallback: "Pandit Sharma",
    category_id: "pandit_ceremony",
    invoice_number: "PS-01",
    amount_cents: 480_000,
    due_date: "2026-05-18",
    status: "approved",
    pdf_url: null,
    pdf_filename: null,
    notes: "Pandit fee + samagri advance.",
    event_splits: [],
    extracted_data_jsonb: null,
    created_at: "2026-04-08T10:00:00.000Z",
    updated_at: "2026-04-10T10:00:00.000Z",
  },
  {
    id: "inv_11",
    wedding_id: W,
    vendor_id: null,
    vendor_name_fallback: "Bay View Estate",
    category_id: "venue",
    invoice_number: "BVE-2026-0081",
    amount_cents: 6_000_000,
    due_date: "2026-06-01",
    status: "approved",
    pdf_url: null,
    pdf_filename: null,
    notes: "Venue balance, 50%.",
    event_splits: [],
    extracted_data_jsonb: null,
    created_at: "2026-04-15T10:00:00.000Z",
    updated_at: "2026-04-15T10:00:00.000Z",
  },
  {
    id: "inv_12",
    wedding_id: W,
    vendor_id: null,
    vendor_name_fallback: "Saffron & Sage Catering",
    category_id: "catering",
    invoice_number: "SS-2026-199",
    amount_cents: 5_500_000,
    due_date: "2026-06-10",
    status: "approved",
    pdf_url: null,
    pdf_filename: null,
    notes: "Catering balance — 50% + service.",
    event_splits: [],
    extracted_data_jsonb: null,
    created_at: "2026-04-15T10:00:00.000Z",
    updated_at: "2026-04-15T10:00:00.000Z",
  },
];

// ── Payments ──────────────────────────────────────────────────────────────

export const SEED_FINANCE_PAYMENTS: FinancePayment[] = [
  {
    id: "pay_01",
    invoice_id: "inv_01",
    amount_cents: 6_000_000,
    paid_date: "2026-02-01",
    payment_method: "wire",
    notes: "Wire transfer to Bay View Estate.",
    created_at: "2026-02-01T10:00:00.000Z",
  },
  {
    id: "pay_02",
    invoice_id: "inv_02",
    amount_cents: 2_500_000,
    paid_date: "2026-03-15",
    payment_method: "ach",
    notes: "ACH to Saffron & Sage.",
    created_at: "2026-03-15T10:00:00.000Z",
  },
  {
    id: "pay_03",
    invoice_id: "inv_03",
    amount_cents: 1_800_000,
    paid_date: "2026-03-30",
    payment_method: "check",
    notes: "Check #4421 to Mira Studio.",
    created_at: "2026-03-30T10:00:00.000Z",
  },
];

// ── Contributors ──────────────────────────────────────────────────────────

export const SEED_FINANCE_CONTRIBUTORS: FinanceContributor[] = [
  {
    id: "ctb_01",
    wedding_id: W,
    name: "Shalini & Vikram Patel",
    relationship: "Bride's parents",
    pledged_cents: 25_000_000,
    paid_cents: 10_000_000,
    visibility_scope: "all",
    notes: "Primary contributors — covering venue + catering.",
    created_at: "2026-01-15T10:00:00.000Z",
  },
  {
    id: "ctb_02",
    wedding_id: W,
    name: "Rajesh & Meena Shah",
    relationship: "Groom's parents",
    pledged_cents: 15_000_000,
    paid_cents: 5_000_000,
    visibility_scope: "all",
    notes: "Covering baraat, sangeet, and jewelry.",
    created_at: "2026-01-20T10:00:00.000Z",
  },
  {
    id: "ctb_03",
    wedding_id: W,
    name: "Priya & Arjun",
    relationship: "Couple",
    pledged_cents: 8_000_000,
    paid_cents: 4_000_000,
    visibility_scope: "self",
    notes: "Personal savings — photography, wardrobe, and extras.",
    created_at: "2026-02-01T10:00:00.000Z",
  },
  {
    id: "ctb_04",
    wedding_id: W,
    name: "Uncle Nikhil",
    relationship: "Bride's uncle (mama)",
    pledged_cents: 2_000_000,
    paid_cents: 2_000_000,
    visibility_scope: "named_categories",
    notes: "Dhol + baraat sponsorship gift, paid in full.",
    created_at: "2026-02-10T10:00:00.000Z",
  },
];

export const SEED_FINANCE_CONTRIBUTOR_ALLOCATIONS: FinanceContributorAllocation[] = [
  { id: "alo_01", contributor_id: "ctb_01", category_id: "venue", invoice_id: null, amount_cents: 12_500_000, note: "Venue" },
  { id: "alo_02", contributor_id: "ctb_01", category_id: "catering", invoice_id: null, amount_cents: 11_500_000, note: "Catering" },
  { id: "alo_03", contributor_id: "ctb_01", category_id: "decor_florals", invoice_id: null, amount_cents: 1_000_000, note: "Décor topup" },
  { id: "alo_04", contributor_id: "ctb_02", category_id: "entertainment", invoice_id: null, amount_cents: 3_500_000, note: "Entertainment incl. sangeet" },
  { id: "alo_05", contributor_id: "ctb_02", category_id: "decor_florals", invoice_id: null, amount_cents: 6_500_000, note: "Remaining florals" },
  { id: "alo_06", contributor_id: "ctb_02", category_id: "wardrobe", invoice_id: null, amount_cents: 2_500_000, note: "Wardrobe + jewelry" },
  { id: "alo_07", contributor_id: "ctb_02", category_id: "pandit_ceremony", invoice_id: null, amount_cents: 1_350_000, note: "Pandit + samagri" },
  { id: "alo_08", contributor_id: "ctb_02", category_id: "transportation", invoice_id: null, amount_cents: 750_000, note: "Baraat + shuttles" },
  { id: "alo_09", contributor_id: "ctb_03", category_id: "photography", invoice_id: null, amount_cents: 4_500_000, note: "Photography" },
  { id: "alo_10", contributor_id: "ctb_03", category_id: "videography", invoice_id: null, amount_cents: 3_000_000, note: "Videography" },
  { id: "alo_11", contributor_id: "ctb_03", category_id: "hmua", invoice_id: null, amount_cents: 500_000, note: "HMUA" },
  { id: "alo_12", contributor_id: "ctb_04", category_id: "entertainment", invoice_id: null, amount_cents: 1_500_000, note: "Dhol + baraat band" },
  { id: "alo_13", contributor_id: "ctb_04", category_id: "transportation", invoice_id: null, amount_cents: 500_000, note: "Horse for baraat" },
];

// ── Categories (default set) ─────────────────────────────────────────────
// Seed row per default workspace category. Keeping ids identical to the
// workspace slug means every existing invoice/allocation links cleanly.

export const SEED_FINANCE_CATEGORIES: FinanceCategory[] = DEFAULT_CATEGORY_SLUGS.map(
  (slug, idx) => ({
    id: slug,
    wedding_id: W,
    name: FINANCE_CATEGORY_LABEL[slug],
    color_class: FINANCE_CATEGORY_TINT[slug],
    is_default: true,
    hidden: false,
    sort_order: idx,
    created_at: "2026-02-10T10:00:00.000Z",
  }),
);

// ── Events (default Indian wedding timeline) ─────────────────────────────

export const SEED_FINANCE_EVENTS: FinanceEvent[] = SPEC_DEFAULT_EVENTS.map(
  (e, idx) => ({
    id: `evt_${idx + 1}`,
    wedding_id: W,
    name: e.name,
    date: null,
    sort_order: e.sort_order,
    allocated_cents: 0,
    created_at: "2026-02-10T10:00:00.000Z",
  }),
);

// ── Wedding-level settings ───────────────────────────────────────────────
// Total budget starts at the sum of seeded allocations so Overview/Budget
// display coherent numbers out of the box.

const SEEDED_TOTAL = SEED_FINANCE_BUDGETS.reduce(
  (s, b) => s + b.allocated_cents,
  0,
);

export const SEED_FINANCE_SETTINGS: FinanceSettings = {
  wedding_id: W,
  total_budget_cents: SEEDED_TOTAL,
  active_preset_id: "preset_default",
  onboarding: {
    completed: false,
    split_model: null,
    has_total_budget: true,
    track_personal: null,
    category_responsibility_notes: [],
    completed_at: null,
  },
  updated_at: "2026-02-10T10:00:00.000Z",
};

// ── Allocation presets ───────────────────────────────────────────────────

export const SEED_FINANCE_PRESETS: AllocationPreset[] = [
  {
    id: "preset_default",
    wedding_id: W,
    name: "Ananya default",
    percentages: { ...SPEC_DEFAULT_PERCENTAGES } as Record<string, number>,
    is_default: true,
    created_at: "2026-02-10T10:00:00.000Z",
  },
];

// ── Transactions ─────────────────────────────────────────────────────────
// A handful of seeded ledger rows mirrors what a typical statement import
// would produce. Links inv_01, inv_02, inv_03 to their paid counterparts
// so the reconciliation strip in the category drawer reads realistically.

export const SEED_FINANCE_TRANSACTIONS: FinanceTransaction[] = [
  {
    id: "txn_01",
    wedding_id: W,
    date: "2026-02-01",
    description: "WIRE BAY VIEW ESTATE EVENTS",
    amount_cents: 6_000_000,
    account_last4: "4821",
    category_id: "venue",
    event_splits: [{ event_id: "evt_5", amount_cents: 6_000_000 }],
    payer_contributor_id: "ctb_01",
    invoice_id: "inv_01",
    notes: "Venue deposit wire.",
    receipt_url: null,
    receipt_filename: null,
    fund_source: "shared",
    source: "manual",
    dedupe_hash: "2026-02-01|6000000|wire bay view estate events",
    created_at: "2026-02-01T12:00:00.000Z",
  },
  {
    id: "txn_02",
    wedding_id: W,
    date: "2026-03-15",
    description: "ACH SAFFRON & SAGE CATERING",
    amount_cents: 2_500_000,
    account_last4: "4821",
    category_id: "catering",
    event_splits: [
      { event_id: "evt_4", amount_cents: 800_000 },
      { event_id: "evt_5", amount_cents: 1_100_000 },
      { event_id: "evt_6", amount_cents: 600_000 },
    ],
    payer_contributor_id: "ctb_01",
    invoice_id: "inv_02",
    notes: "Tasting + 25% deposit.",
    receipt_url: null,
    receipt_filename: null,
    fund_source: "shared",
    source: "csv_import",
    dedupe_hash: "2026-03-15|2500000|ach saffron & sage catering",
    created_at: "2026-03-15T12:00:00.000Z",
  },
  {
    id: "txn_03",
    wedding_id: W,
    date: "2026-03-30",
    description: "CHECK 4421 MIRA STUDIO",
    amount_cents: 1_800_000,
    account_last4: "4821",
    category_id: "photography",
    event_splits: [],
    payer_contributor_id: "ctb_03",
    invoice_id: "inv_03",
    notes: "Photographer retainer.",
    receipt_url: null,
    receipt_filename: null,
    fund_source: "shared",
    source: "pdf_import",
    dedupe_hash: "2026-03-30|1800000|check 4421 mira studio",
    created_at: "2026-03-30T12:00:00.000Z",
  },
  {
    id: "txn_04",
    wedding_id: W,
    date: "2026-04-05",
    description: "ZELLE KALYANA FLORALS LLC",
    amount_cents: 450_000,
    account_last4: "4821",
    category_id: "decor_florals",
    event_splits: [{ event_id: "evt_3", amount_cents: 450_000 }],
    payer_contributor_id: "ctb_01",
    invoice_id: null,
    notes: "Mehendi mandap flowers — advance.",
    receipt_url: null,
    receipt_filename: null,
    fund_source: "shared",
    source: "csv_import",
    dedupe_hash: "2026-04-05|450000|zelle kalyana florals llc",
    created_at: "2026-04-05T12:00:00.000Z",
  },
  {
    id: "txn_05",
    wedding_id: W,
    date: "2026-04-12",
    description: "CC PURCHASE STATIONERY NIRMAAN",
    amount_cents: 120_000,
    account_last4: "9912",
    category_id: "stationery",
    event_splits: [],
    payer_contributor_id: "ctb_03",
    invoice_id: null,
    notes: "Welcome signage samples.",
    receipt_url: null,
    receipt_filename: null,
    fund_source: "shared",
    source: "csv_import",
    dedupe_hash: "2026-04-12|120000|cc purchase stationery nirmaan",
    created_at: "2026-04-12T12:00:00.000Z",
  },
  // ── Personal expenses (not from the shared fund) ─────────────────────
  {
    id: "txn_p1",
    wedding_id: W,
    date: "2026-03-22",
    description: "SABYASACHI BRIDAL LEHENGA",
    amount_cents: 850_000,
    account_last4: "1156",
    category_id: "wardrobe",
    event_splits: [{ event_id: "evt_5", amount_cents: 850_000 }],
    payer_contributor_id: "ctb_03",
    invoice_id: null,
    notes: "Bride's lehenga — personal funds.",
    receipt_url: null,
    receipt_filename: null,
    fund_source: "personal",
    source: "csv_import",
    dedupe_hash: "2026-03-22|850000|sabyasachi bridal lehenga",
    created_at: "2026-03-22T12:00:00.000Z",
  },
  {
    id: "txn_p2",
    wedding_id: W,
    date: "2026-04-08",
    description: "TANISHQ JEWELERS",
    amount_cents: 320_000,
    account_last4: "1156",
    category_id: "jewelry",
    event_splits: [],
    payer_contributor_id: "ctb_03",
    invoice_id: null,
    notes: "Engagement set + personal pieces.",
    receipt_url: null,
    receipt_filename: null,
    fund_source: "personal",
    source: "csv_import",
    dedupe_hash: "2026-04-08|320000|tanishq jewelers",
    created_at: "2026-04-08T12:00:00.000Z",
  },
  {
    id: "txn_p3",
    wedding_id: W,
    date: "2026-04-15",
    description: "GLOW SPA — BRIDAL FACIAL PACKAGE",
    amount_cents: 65_000,
    account_last4: "1156",
    category_id: "hmua",
    event_splits: [],
    payer_contributor_id: "ctb_03",
    invoice_id: null,
    notes: "Pre-wedding facial series.",
    receipt_url: null,
    receipt_filename: null,
    fund_source: "personal",
    source: "csv_import",
    dedupe_hash: "2026-04-15|65000|glow spa bridal facial package",
    created_at: "2026-04-15T12:00:00.000Z",
  },
];

// ── Invoice milestones ────────────────────────────────────────────────────
// Realistic 3-installment cadence on a few invoices so the detail view has
// something to render out of the box.

export const SEED_FINANCE_INVOICE_MILESTONES = [
  // inv_01 — Bay View Estate venue: 50% paid, midpoint paid, final unpaid.
  {
    id: "ms_inv01_1",
    invoice_id: "inv_01",
    name: "Signing deposit (50%)",
    amount_cents: 6_000_000,
    due_date: "2026-02-01",
    status: "paid" as const,
    paid_date: "2026-02-01",
    payment_method: "wire" as const,
    payment_reference: "WIRE-202602-0042",
    transaction_id: "txn_01",
    sort_order: 0,
    created_at: "2026-01-20T10:00:00.000Z",
  },
  {
    id: "ms_inv01_2",
    invoice_id: "inv_01",
    name: "Mid-point payment (25%)",
    amount_cents: 3_000_000,
    due_date: "2026-05-15",
    status: "unpaid" as const,
    paid_date: null,
    payment_method: null,
    payment_reference: null,
    transaction_id: null,
    sort_order: 1,
    created_at: "2026-01-20T10:00:00.000Z",
  },
  {
    id: "ms_inv01_3",
    invoice_id: "inv_01",
    name: "Final balance (25%)",
    amount_cents: 3_500_000,
    due_date: "2026-08-15",
    status: "unpaid" as const,
    paid_date: null,
    payment_method: null,
    payment_reference: null,
    transaction_id: null,
    sort_order: 2,
    created_at: "2026-01-20T10:00:00.000Z",
  },
  // inv_02 — Saffron & Sage Catering: deposit paid, 2 unpaid.
  {
    id: "ms_inv02_1",
    invoice_id: "inv_02",
    name: "Tasting + 25% deposit",
    amount_cents: 2_500_000,
    due_date: "2026-03-15",
    status: "paid" as const,
    paid_date: "2026-03-15",
    payment_method: "ach" as const,
    payment_reference: null,
    transaction_id: "txn_02",
    sort_order: 0,
    created_at: "2026-02-25T10:00:00.000Z",
  },
  {
    id: "ms_inv02_2",
    invoice_id: "inv_02",
    name: "50% midpoint",
    amount_cents: 5_000_000,
    due_date: "2026-06-01",
    status: "unpaid" as const,
    paid_date: null,
    payment_method: null,
    payment_reference: null,
    transaction_id: null,
    sort_order: 1,
    created_at: "2026-02-25T10:00:00.000Z",
  },
  {
    id: "ms_inv02_3",
    invoice_id: "inv_02",
    name: "Final balance",
    amount_cents: 4_000_000,
    due_date: "2026-08-20",
    status: "unpaid" as const,
    paid_date: null,
    payment_method: null,
    payment_reference: null,
    transaction_id: null,
    sort_order: 2,
    created_at: "2026-02-25T10:00:00.000Z",
  },
];

// ── Invoice comments (threaded notes) ─────────────────────────────────────

export const SEED_FINANCE_INVOICE_COMMENTS = [
  {
    id: "cmt_01",
    invoice_id: "inv_01",
    author_name: "Priya",
    body: "Vendor said they'll waive the $2k setup fee if we book the rehearsal dinner here too. Worth bringing up.",
    pinned: true,
    created_at: "2026-02-18T15:30:00.000Z",
  },
  {
    id: "cmt_02",
    invoice_id: "inv_01",
    author_name: "Shalini",
    body: "Wired the deposit from the joint account. Confirmation # WIRE-202602-0042.",
    pinned: false,
    created_at: "2026-02-01T11:15:00.000Z",
  },
  {
    id: "cmt_03",
    invoice_id: "inv_02",
    author_name: "Arjun",
    body: "Tasting was incredible. Locked in the menu — no more changes after May 1.",
    pinned: true,
    created_at: "2026-03-16T09:00:00.000Z",
  },
];

// ── Invoice activity log (auto-generated entries) ─────────────────────────

export const SEED_FINANCE_INVOICE_ACTIVITY = [
  {
    id: "act_01",
    invoice_id: "inv_01",
    kind: "invoice_created" as const,
    message: "Invoice created from Bay View Estate proposal",
    actor_name: "Priya",
    created_at: "2026-01-20T10:00:00.000Z",
  },
  {
    id: "act_02",
    invoice_id: "inv_01",
    kind: "milestone_paid" as const,
    message: "Marked 'Signing deposit (50%)' as paid — $60,000",
    actor_name: "Shalini",
    created_at: "2026-02-01T11:30:00.000Z",
  },
  {
    id: "act_03",
    invoice_id: "inv_01",
    kind: "comment_added" as const,
    message: "Pinned a comment about the setup fee",
    actor_name: "Priya",
    created_at: "2026-02-18T15:30:00.000Z",
  },
];
