// ── Music Day-of Schedule seed ────────────────────────────────────────────
// One operational timeline per event. Sangeet + Reception are dense (the
// shows). Haldi is a one-liner. Curfew + handoff slots are first-class so
// the renderer can highlight them.

import type { MusicScheduleSlot } from "@/types/music";

export const DEMO_MUSIC_WEDDING_ID = "wedding-demo";

let counter = 0;
const id = () => `seed-sch-${++counter}`;

export const SEED_MUSIC_SCHEDULE: MusicScheduleSlot[] = [
  // ── Haldi ──────────────────────────────────────────────────────────
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "haldi",
    start_time: "08:30",
    kind: "background_music",
    label: "Curated dholki / haldi songs Bluetooth playlist",
    owner: "Priya's bridesmaids",
    sort_order: 1,
  },
  // ── Mehendi ────────────────────────────────────────────────────────
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "mehendi",
    start_time: "12:00",
    end_time: "13:30",
    kind: "load_in",
    label: "DJ + lighting load-in (lawn)",
    owner: "DJ Pranav crew",
    sort_order: 1,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "mehendi",
    start_time: "14:00",
    end_time: "14:30",
    kind: "sound_check",
    label: "Mic + PA check (lawn)",
    owner: "DJ Pranav + venue AV",
    sort_order: 2,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "mehendi",
    start_time: "15:00",
    kind: "background_music",
    label: "Sufi instrumental — guests arriving",
    owner: "DJ Pranav",
    sort_order: 3,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "mehendi",
    start_time: "16:30",
    kind: "cue",
    label: "Bride's mehendi begins → Mehendi Laga Ke Rakhna",
    owner: "DJ Pranav",
    sort_order: 4,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "mehendi",
    start_time: "18:00",
    end_time: "18:45",
    kind: "cue",
    label: "Live qawwali set (Aaryan trio)",
    owner: "Aaryan Classical Trio",
    sort_order: 5,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "mehendi",
    start_time: "18:45",
    kind: "handoff",
    label: "Qawwali → DJ — crossfade on last note",
    handoff_from: "Aaryan trio",
    handoff_to: "DJ Pranav",
    sort_order: 6,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "mehendi",
    start_time: "20:30",
    kind: "teardown",
    label: "Strike PA + lights",
    owner: "DJ crew",
    sort_order: 7,
  },
  // ── Sangeet ────────────────────────────────────────────────────────
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "sangeet",
    start_time: "13:00",
    end_time: "15:00",
    kind: "load_in",
    label: "Full PA + intelligent lighting + stage rig load-in",
    owner: "DJ Pranav + Wildfire (band) + lighting crew",
    sort_order: 1,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "sangeet",
    start_time: "15:00",
    end_time: "16:00",
    kind: "sound_check",
    label: "Sound check — performers, mics, monitor mixes",
    owner: "All performers + DJ Pranav + Choreographer Neha",
    sort_order: 2,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "sangeet",
    start_time: "18:00",
    kind: "background_music",
    label: "Lounge Bollywood remixes — guests arriving",
    owner: "DJ Pranav",
    sort_order: 3,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "sangeet",
    start_time: "19:30",
    kind: "cue",
    label: "Emcee opens — house lights down",
    owner: "MC Rajiv + DJ Pranav",
    sort_order: 4,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "sangeet",
    start_time: "19:35",
    end_time: "21:00",
    kind: "cue",
    label: "Sangeet acts (see Sangeet Planner running order)",
    owner: "DJ Pranav (cue ops)",
    sort_order: 5,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "sangeet",
    start_time: "21:00",
    kind: "handoff",
    label: "Choreography acts done → DJ takes the floor",
    handoff_from: "Performers",
    handoff_to: "DJ Pranav",
    sort_order: 6,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "sangeet",
    start_time: "22:45",
    kind: "curfew_warning",
    label: "15-min outdoor curfew warning — last outdoor song call",
    owner: "Urvashi + DJ Pranav",
    curfew: true,
    sort_order: 7,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "sangeet",
    start_time: "23:00",
    kind: "curfew_warning",
    label: "Outdoor curfew — move to indoor lounge",
    owner: "Venue ops",
    curfew: true,
    sort_order: 8,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "sangeet",
    start_time: "23:15",
    end_time: "01:00",
    kind: "after_party",
    label: "Indoor after-party — lower volume, intimate set",
    owner: "DJ Pranav",
    sort_order: 9,
  },
  // ── Ceremony ───────────────────────────────────────────────────────
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "ceremony",
    start_time: "07:00",
    end_time: "08:00",
    kind: "load_in",
    label: "Mandap mics + shehnai PA load-in",
    owner: "Sound engineer",
    sort_order: 1,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "ceremony",
    start_time: "08:00",
    end_time: "08:30",
    kind: "sound_check",
    label: "Pandit lapel test + shehnai instrument mic levels",
    owner: "Sound engineer + Pandit ji",
    sort_order: 2,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "ceremony",
    start_time: "09:30",
    kind: "cue",
    label: "Baraat dhol procession arrives",
    owner: "Mumbai Dhol Ensemble",
    sort_order: 3,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "ceremony",
    start_time: "10:15",
    kind: "cue",
    label: "Bride's entrance — live shehnai",
    owner: "Aaryan trio",
    sort_order: 4,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "ceremony",
    start_time: "11:00",
    kind: "cue",
    label: "Pheras — mantras only, no playback",
    owner: "Pandit ji",
    notes: "Hard rule — no background music during pheras",
    sort_order: 5,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "ceremony",
    start_time: "12:30",
    kind: "cue",
    label: "Vidaai — Babul Ki Duayein",
    owner: "Sound engineer",
    sort_order: 6,
  },
  // ── Reception ──────────────────────────────────────────────────────
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "reception",
    start_time: "13:00",
    end_time: "15:00",
    kind: "load_in",
    label: "Ballroom PA + lighting + DJ rig load-in",
    owner: "DJ Pranav crew",
    sort_order: 1,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "reception",
    start_time: "15:00",
    end_time: "16:00",
    kind: "sound_check",
    label: "Speech mic + dance-floor PA check",
    owner: "DJ Pranav + Venue AV",
    sort_order: 2,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "reception",
    start_time: "18:30",
    kind: "background_music",
    label: "Sophisticated Bollywood lounge — guests arrive",
    owner: "DJ Pranav",
    sort_order: 3,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "reception",
    start_time: "19:30",
    kind: "cue",
    label: "Couple's grand entrance — Dilbar Dilbar (DJ Pranav edit)",
    owner: "DJ Pranav",
    sort_order: 4,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "reception",
    start_time: "19:40",
    kind: "cue",
    label: "First dance — Perfect (Ed Sheeran)",
    owner: "DJ Pranav",
    sort_order: 5,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "reception",
    start_time: "19:50",
    kind: "cue",
    label: "Mother-son dance — Maa (Shankar Mahadevan)",
    owner: "DJ Pranav",
    sort_order: 6,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "reception",
    start_time: "20:00",
    end_time: "21:00",
    kind: "background_music",
    label: "Dinner service — soft Bollywood + Western standards",
    owner: "DJ Pranav",
    sort_order: 7,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "reception",
    start_time: "21:00",
    kind: "cue",
    label: "Cake cutting — couple's chosen song",
    owner: "DJ Pranav",
    sort_order: 8,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "reception",
    start_time: "21:15",
    end_time: "00:30",
    kind: "cue",
    label: "Open dance floor — Bollywood + bhangra + Western mix",
    owner: "DJ Pranav",
    sort_order: 9,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "reception",
    start_time: "00:25",
    kind: "cue",
    label: "Last dance — couple's final song",
    owner: "DJ Pranav",
    sort_order: 10,
  },
  {
    id: id(),
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    event: "reception",
    start_time: "00:30",
    kind: "teardown",
    label: "Strike rig — sparkler send-off underway in lobby",
    owner: "DJ crew",
    sort_order: 11,
  },
];
