// ── Pandit workspace seed data ────────────────────────────────────────────
// Pre-populates a Vedic ceremony: 11 core rituals with meanings, 12 family
// roles (bride's side + groom's side + shared), 40+ samagri items grouped
// by category, a default brief, and a logistics template. All of this is
// freely edited in the UI — the seed is just "day-0 sensible defaults so
// couples aren't staring at an empty canvas."

import type {
  CeremonyBrief,
  CeremonyFamilyRole,
  CeremonyLogistics,
  CeremonyPersonalAddition,
  CeremonyRitual,
  SamagriItem,
} from "@/types/pandit";

const now = "2026-04-20T00:00:00.000Z";

// ── Rituals (Vedic, in traditional order) ────────────────────────────────

export const SEED_CEREMONY_RITUALS: CeremonyRitual[] = [
  {
    id: "rit-ganesh",
    name_sanskrit: "गणेश पूजा",
    name_english: "Ganesh Puja",
    short_description:
      "Invocation of Lord Ganesh to remove obstacles at the start of the ceremony.",
    meaning:
      "Hindu ceremonies begin by honoring Ganesh, the remover of obstacles. The couple and pandit together offer prayers so the rest of the ceremony unfolds smoothly. It's a humbling moment — acknowledging that no union begins in isolation, it begins with blessings from the divine.",
    default_duration_min: 5,
    default_inclusion: "yes",
    traditional_participants: "Couple + pandit",
    inclusion: "yes",
    included_duration_min: 5,
    abbreviated: false,
    couple_notes: "",
    sort_order: 1,
    what_happens:
      "Couple sits together facing the havan kund. Pandit leads a short invocation to Ganesh. Couple offers flowers and rice to a small Ganesh murti.",
    music_note: "No recorded music. Soft instrumental acceptable before the invocation begins.",
    photography_note: "Wide shot from the aisle — establishes the ceremony start.",
    guest_instruction: "Seated. Silent attention as the mantras begin.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rit-baraat",
    name_sanskrit: "बरात और मिलनी",
    name_english: "Baraat & Milni",
    short_description:
      "Groom's procession arrives; families greet each other with garlands.",
    meaning:
      "The baraat is the groom's joyous arrival — historically on horseback, today often with a band and dancing. Milni is the formal greeting between the families, garlanding male elders on both sides to symbolize the merging of two lineages.",
    default_duration_min: 20,
    default_inclusion: "yes",
    traditional_participants: "Groom, groom's family, bride's family",
    inclusion: "yes",
    included_duration_min: 20,
    abbreviated: false,
    couple_notes: "",
    sort_order: 2,
    what_happens:
      "Groom arrives with his family, dancing to dhol. At the venue entrance, elders from both families exchange garlands in pairs. Bride's family offers tilak and sweets.",
    music_note: "Live dhol or recorded baraat music. Cut to silence as milni begins.",
    photography_note:
      "High-energy. Get the groom's face, the dancing, the grandmothers watching. Capture each milni pair individually.",
    guest_instruction:
      "Guests from both sides meet and mingle. Everyone is welcome to dance with the baraat.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rit-jaimala",
    name_sanskrit: "जयमाला / वरमाला",
    name_english: "Jai Mala / Varmala",
    short_description:
      "Exchange of flower garlands — a mutual act of acceptance.",
    meaning:
      "The couple sees each other as bride and groom for the first time, then exchanges garlands. This is the moment of mutual choice — each is welcoming the other into their life. In North Indian ceremonies, the bride's brothers often playfully lift her so the groom can't easily garland her, a lighthearted tradition.",
    default_duration_min: 5,
    default_inclusion: "yes",
    traditional_participants: "Couple, bride's brothers/cousins",
    inclusion: "yes",
    included_duration_min: 5,
    abbreviated: false,
    couple_notes: "",
    sort_order: 3,
    what_happens:
      "Bride and groom stand facing each other on either side of an antarpat (cloth curtain). The curtain drops. They exchange garlands — three times each, traditionally.",
    music_note: "Soft instrumental during; build during the garland exchange.",
    photography_note: "Must-photograph. Both profiles. The laugh as they garland each other.",
    guest_instruction:
      "Stand. You may cheer and throw flower petals when the garlands are exchanged.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rit-kanyadaan",
    name_sanskrit: "कन्यादान",
    name_english: "Kanyadaan",
    short_description:
      "The bride's parents entrust her to the groom — traditionally the most emotional moment.",
    meaning:
      "Kanyadaan literally means 'giving away of the daughter.' The bride's parents place her hand in the groom's, pour sacred water, and formally entrust her care to his family. For many couples this is the most emotional moment of the ceremony. Modern couples sometimes modify this ritual — it carries patriarchal history, and some reframe it as a blessing rather than a handover.",
    default_duration_min: 10,
    default_inclusion: "discuss",
    traditional_participants: "Bride's parents, bride, groom",
    inclusion: "discuss",
    included_duration_min: 10,
    abbreviated: false,
    couple_notes:
      "Talk with Mom and Dad about how to frame this. We want it to feel like a blessing, not a transfer.",
    sort_order: 4,
    what_happens:
      "Bride's parents sit with the couple at the mandap. Sacred water is poured over the joined hands of the bride and groom. Mantras are recited affirming the union.",
    music_note: "Silence. Let the family speak.",
    photography_note:
      "The hands — bride's, groom's, father's, mother's — all layered. The parents' faces. This often generates tears.",
    guest_instruction: "Seated. Silent. This is a family moment.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rit-havan",
    name_sanskrit: "विवाह हवन",
    name_english: "Vivah Havan",
    short_description:
      "The sacred fire is kindled — Agni witnesses the marriage.",
    meaning:
      "In Hindu tradition, Agni (fire) is the eternal witness to the marriage. Everything said and done at the havan is considered sacred because fire has seen it. The couple makes offerings of ghee and samagri into the flames as mantras are recited.",
    default_duration_min: 15,
    default_inclusion: "yes",
    traditional_participants: "Couple, pandit",
    inclusion: "yes",
    included_duration_min: 15,
    abbreviated: false,
    couple_notes: "",
    sort_order: 5,
    what_happens:
      "Pandit kindles the sacred fire in the havan kund. Couple makes offerings (ghee, samagri) into the fire while mantras are chanted. Bride's brother may assist with offerings.",
    music_note: "No recorded music. Mantras only.",
    photography_note: "The fire and the couple's faces lit by it. The ghee being poured.",
    guest_instruction:
      "Seated. Do not approach the fire. Smoke may drift — this is traditional.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rit-pheras",
    name_sanskrit: "मंगल फेरे",
    name_english: "Mangal Pheras",
    short_description: "Seven circles around the sacred fire — seven vows.",
    meaning:
      "The couple walks around the sacred fire seven times, each circle representing a vow: nourishment, strength, prosperity, wisdom, progeny, health, and lifelong friendship. In some traditions the bride leads the first four, the groom leads the last three.",
    default_duration_min: 15,
    default_inclusion: "yes",
    traditional_participants: "Couple, bride's brother (for offerings)",
    inclusion: "yes",
    included_duration_min: 15,
    abbreviated: false,
    couple_notes: "",
    sort_order: 6,
    what_happens:
      "Couple's clothes are tied together (gath bandhan). They rise and walk slowly around the fire, pausing after each circuit as the pandit recites the vow.",
    music_note: "No recorded music. Mantras only.",
    photography_note:
      "Must-photograph. Each of the seven circles. Wide and tight. Their faces mid-vow.",
    guest_instruction:
      "Stand as they begin. You may silently pray for them during each circuit.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rit-saptapadi",
    name_sanskrit: "सप्तपदी",
    name_english: "Saptapadi",
    short_description: "Seven steps together — seven promises.",
    meaning:
      "The couple takes seven literal steps together, with each step being a specific promise: to share responsibilities, be each other's strength, pursue dharma together, raise a family, grow old together, and remain friends forever. In many modern ceremonies saptapadi is combined with or performed after pheras.",
    default_duration_min: 10,
    default_inclusion: "yes",
    traditional_participants: "Couple, pandit",
    inclusion: "yes",
    included_duration_min: 10,
    abbreviated: false,
    couple_notes: "",
    sort_order: 7,
    what_happens:
      "Couple takes seven deliberate steps together while the pandit recites each promise aloud. This is often where couples are invited to say their own vows in English.",
    music_note: "Silence during steps. Soft instrumental can follow.",
    photography_note: "The feet. The faces. The pandit in frame.",
    guest_instruction: "Seated or standing. Silent witness.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rit-sindoor",
    name_sanskrit: "सिंदूर दान",
    name_english: "Sindoor",
    short_description:
      "Groom applies sindoor to the bride's hairline — marking her as married.",
    meaning:
      "Sindoor (red vermillion powder) is applied by the groom to the parting of the bride's hair. In Hindu tradition this visibly marks a woman as married. It's a brief but emotionally charged moment — the physical symbol of the transition.",
    default_duration_min: 3,
    default_inclusion: "yes",
    traditional_participants: "Couple",
    inclusion: "yes",
    included_duration_min: 3,
    abbreviated: false,
    couple_notes: "",
    sort_order: 8,
    what_happens:
      "Groom dips his finger or a ring in the sindoor and applies it along the bride's hairline. Her head is typically veiled during or immediately after.",
    music_note: "Soft build from instrumental. Audible mantras throughout.",
    photography_note:
      "Close-up. The sindoor, the ring, the hairline. The bride's face as it's applied.",
    guest_instruction: "Seated. A small cheer is appropriate after it's applied.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rit-mangalsutra",
    name_sanskrit: "मंगलसूत्र",
    name_english: "Mangalsutra",
    short_description: "Sacred necklace tied by the groom — the bond of marriage.",
    meaning:
      "The mangalsutra is a gold and black-bead necklace tied by the groom around the bride's neck. 'Mangal' means auspicious, 'sutra' means thread — the auspicious thread of marriage. In South Indian traditions (thali / mangalya dharanam) this is the single most important ritual of the ceremony.",
    default_duration_min: 3,
    default_inclusion: "yes",
    traditional_participants: "Couple",
    inclusion: "yes",
    included_duration_min: 3,
    abbreviated: false,
    couple_notes: "",
    sort_order: 9,
    what_happens:
      "Groom takes the mangalsutra (from a small ceremonial plate) and ties it around the bride's neck. In some traditions, three knots are tied.",
    music_note: "Soft instrumental.",
    photography_note:
      "Must-photograph. Front-facing so the mangalsutra is visible. The moment the knot is tied.",
    guest_instruction: "Seated. Cheer welcome after it's tied.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rit-aashirvad",
    name_sanskrit: "आशीर्वाद",
    name_english: "Aashirvad",
    short_description: "Blessings from elders — the couple receives grace.",
    meaning:
      "After the sacred rites are complete, the couple receives blessings from elders. Traditionally parents and grandparents place rice, flowers, or grain on the couple's heads while reciting blessings. This is the community's formal endorsement of the marriage.",
    default_duration_min: 10,
    default_inclusion: "yes",
    traditional_participants:
      "All parents and grandparents (both sides), followed by other elders",
    inclusion: "yes",
    included_duration_min: 10,
    abbreviated: false,
    couple_notes: "",
    sort_order: 10,
    what_happens:
      "Couple touches the feet of each elder in sequence (or each elder comes forward). Elder places rice/flowers/grain on their heads, murmurs a blessing, and sometimes gives a token gift.",
    music_note: "Soft instrumental appropriate.",
    photography_note:
      "Each elder individually. The couple touching feet. Capture the older generation — this is a shot that matters in ten years.",
    guest_instruction: "Seated. You may photograph from your seat with phones off flash.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rit-vidaai",
    name_sanskrit: "विदाई",
    name_english: "Vidaai",
    short_description:
      "The bride's farewell from her family — the most emotional moment.",
    meaning:
      "Vidaai is the bride's departure from her parents' home. Traditionally she throws rice backward over her shoulder — symbolically repaying her parents for everything they've given her. It is almost always the moment guests and family weep openly. A bittersweet closing to the ceremony.",
    default_duration_min: 10,
    default_inclusion: "yes",
    traditional_participants: "Bride, bride's family, groom",
    inclusion: "yes",
    included_duration_min: 10,
    abbreviated: false,
    couple_notes: "",
    sort_order: 11,
    what_happens:
      "Bride embraces each member of her family. She throws three handfuls of rice backward over her shoulder. She walks out with the groom — sometimes to the car, sometimes to a waiting palki/doli.",
    music_note:
      "A dedicated vidaai song. Often 'Babul' or a family-specific favorite. Live singer welcome.",
    photography_note:
      "Must-photograph. The tears. The rice. The car door closing. This is the emotional bookend of the day.",
    guest_instruction: "Stand. You may cry. You may wave.",
    created_at: now,
    updated_at: now,
  },
];

// ── Personal additions (sample) ───────────────────────────────────────────

export const SEED_PERSONAL_ADDITIONS: CeremonyPersonalAddition[] = [
  {
    id: "add-1",
    body:
      "We want to include our own vows in English right after saptapadi — short, 1–2 minutes each.",
    sort_order: 1,
    created_at: now,
  },
  {
    id: "add-2",
    body:
      "A moment of silence for Arjun's late grandmother Kamala between the havan and pheras.",
    sort_order: 2,
    created_at: now,
  },
];

// ── Default brief ─────────────────────────────────────────────────────────

export const SEED_CEREMONY_BRIEF: CeremonyBrief = {
  tradition: "vedic",
  duration_target_min: 90,
  language_balance: "sanskrit_english_explain",
  guest_participation: "participate_key_moments",
  cultural_context:
    "Your Vedic ceremony will run traditionally with Sanskrit mantras — we'll add a short English explanation after each major ritual so that your non-Hindi-speaking guests can follow along. A printed ceremony program will help bridge the language gap without adding time to the ceremony itself.",
  wants_printed_program: true,
  program_content: {
    include_ritual_meanings: true,
    include_family_roles: true,
    include_love_story: true,
    include_dress_code: true,
    include_unplugged_reminder: true,
  },
  updated_at: now,
};

// ── Family roles ──────────────────────────────────────────────────────────

export const SEED_FAMILY_ROLES: CeremonyFamilyRole[] = [
  {
    id: "role-kanyadaan",
    role_name: "Kanyadaan — who gives away the bride?",
    tradition_text: "Traditionally, the bride's father and mother together.",
    side: "brides",
    linked_ritual_id: "rit-kanyadaan",
    primary_name: "Rajesh Shah",
    primary_relationship: "Bride's father",
    backup_name: "",
    physical_requirements: "Must sit cross-legged on the floor for ~10 minutes.",
    accommodation_notes: "",
    practice_needed: false,
    practice_note: "",
    planner_private_note: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "role-kanyadaan-mother",
    role_name: "Kanyadaan — mother's role",
    tradition_text: "Bride's mother places her hand with the father's.",
    side: "brides",
    linked_ritual_id: "rit-kanyadaan",
    primary_name: "Anita Shah",
    primary_relationship: "Bride's mother",
    backup_name: "",
    physical_requirements: "Seated on floor, arms extended.",
    accommodation_notes: "",
    practice_needed: false,
    practice_note: "",
    planner_private_note: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "role-antarpat",
    role_name: "Antarpat holders — the cloth curtain",
    tradition_text:
      "Two brothers or male cousins of the bride hold the cloth curtain before jaimala.",
    side: "brides",
    linked_ritual_id: "rit-jaimala",
    primary_name: "Rohan Shah",
    primary_relationship: "Bride's brother",
    backup_name: "Kabir Mehta — bride's cousin",
    physical_requirements: "Stand holding a 6-ft cloth for ~3 minutes.",
    accommodation_notes: "",
    practice_needed: true,
    practice_note:
      "Practice the drop — on the pandit's cue, both lower the cloth smoothly.",
    planner_private_note: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "role-havan-support",
    role_name: "Havan support — ghee and samagri",
    tradition_text:
      "The bride's brother typically assists by offering ghee into the fire.",
    side: "brides",
    linked_ritual_id: "rit-havan",
    primary_name: "Rohan Shah",
    primary_relationship: "Bride's brother",
    backup_name: "",
    physical_requirements: "Seated beside the couple; pours ghee on cue.",
    accommodation_notes: "",
    practice_needed: true,
    practice_note:
      "Practice with the pandit — where to pour, how much, when to stop.",
    planner_private_note: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "role-aashirvad-brides",
    role_name: "Aashirvad — bride's side elders",
    tradition_text: "Grandparents and elder aunts/uncles from the bride's side.",
    side: "brides",
    linked_ritual_id: "rit-aashirvad",
    primary_name: "Kamla-ben (dadi), Prakash-kaka, Meena-mami",
    primary_relationship: "Elders",
    backup_name: "",
    physical_requirements:
      "Stand briefly or sit in a designated chair to bless the couple.",
    accommodation_notes:
      "Chairs staged for elders with mobility concerns. Do not expect standing.",
    practice_needed: false,
    practice_note: "",
    planner_private_note: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "role-vidaai",
    role_name: "Vidaai — the farewell escort",
    tradition_text:
      "Immediate family walks the bride out of the venue or to the car.",
    side: "brides",
    linked_ritual_id: "rit-vidaai",
    primary_name: "Parents, brother, closest cousins",
    primary_relationship: "Immediate family",
    backup_name: "",
    physical_requirements: "Walk alongside the bride from mandap to car.",
    accommodation_notes: "",
    practice_needed: false,
    practice_note: "",
    planner_private_note:
      "Dad has been worried about this moment — offer a tissue and give him a minute.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "role-baraat-leader",
    role_name: "Baraat leader",
    tradition_text:
      "The senior-most male from the groom's side leads the procession.",
    side: "grooms",
    linked_ritual_id: "rit-baraat",
    primary_name: "Vijay Kapoor",
    primary_relationship: "Groom's father",
    backup_name: "Sameer Kapoor — groom's uncle",
    physical_requirements: "Walking + optional dancing for ~15 minutes.",
    accommodation_notes: "",
    practice_needed: false,
    practice_note: "",
    planner_private_note: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "role-milni",
    role_name: "Milni — elders who exchange garlands",
    tradition_text:
      "Senior male relatives from both sides pair up in hierarchy order.",
    side: "grooms",
    linked_ritual_id: "rit-baraat",
    primary_name: "Vijay (father) with Rajesh (bride's father), then uncles in turn",
    primary_relationship: "Elders — groom's side",
    backup_name: "",
    physical_requirements: "Stand and exchange garlands.",
    accommodation_notes: "",
    practice_needed: true,
    practice_note:
      "Confirm pairing order with both sides 1 week before. Photograph each pair.",
    planner_private_note: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "role-granthi",
    role_name: "Granthi Bandhan — tying the couple's knot",
    tradition_text:
      "The groom's sister (or an aunt) ties the couple's garments before pheras.",
    side: "grooms",
    linked_ritual_id: "rit-pheras",
    primary_name: "Priya Kapoor",
    primary_relationship: "Groom's sister",
    backup_name: "",
    physical_requirements: "Kneel briefly to tie the garments.",
    accommodation_notes: "",
    practice_needed: true,
    practice_note:
      "Practice the knot with the pandit — tight enough to hold, loose enough to untie.",
    planner_private_note: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "role-aashirvad-grooms",
    role_name: "Aashirvad — groom's side elders",
    tradition_text: "Grandparents and elder aunts/uncles from the groom's side.",
    side: "grooms",
    linked_ritual_id: "rit-aashirvad",
    primary_name: "Dadaji, Dadiji, Vinod-chacha, Rekha-bua",
    primary_relationship: "Elders",
    backup_name: "",
    physical_requirements:
      "Stand briefly or sit in a designated chair to bless the couple.",
    accommodation_notes: "",
    practice_needed: false,
    practice_note: "",
    planner_private_note: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "role-fire-tender",
    role_name: "Fire tender — keeps havan fire going",
    tradition_text:
      "An assistant or relative adds kindling/camphor to keep the havan lit.",
    side: "shared",
    linked_ritual_id: "rit-havan",
    primary_name: "Pandit's assistant (Sudhir-ji)",
    primary_relationship: "Pandit's side",
    backup_name: "Kabir Mehta — if needed",
    physical_requirements: "Sit near the fire. Heat-tolerant clothing.",
    accommodation_notes: "",
    practice_needed: true,
    practice_note: "Confirm with pandit before the ceremony day.",
    planner_private_note: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "role-ring-holder",
    role_name: "Ring / mangalsutra holder",
    tradition_text:
      "A close family member holds the mangalsutra and rings on a plate before they're used.",
    side: "shared",
    linked_ritual_id: "rit-mangalsutra",
    primary_name: "Priya Kapoor (with bride's cousin Meera)",
    primary_relationship: "Groom's sister + bride's cousin",
    backup_name: "",
    physical_requirements: "Stand near the mandap with a decorated plate.",
    accommodation_notes: "",
    practice_needed: false,
    practice_note: "",
    planner_private_note:
      "Confirm plate decoration matches mandap florals — coordinate with Décor workspace.",
    created_at: now,
    updated_at: now,
  },
];

// ── Samagri items ─────────────────────────────────────────────────────────

export const SEED_SAMAGRI_ITEMS: SamagriItem[] = [
  // ── General / Setup ──
  {
    id: "sam-havan-kund",
    name_local: "हवन कुंड",
    name_english: "Havan kund (fire vessel)",
    category: "general_setup",
    used_for_ritual_id: "rit-havan",
    quantity: "1 large copper vessel",
    source: "pandit_provides",
    responsibility: "pandit",
    status: "confirmed",
    added_by_pandit: true,
    notes: "Confirm dimensions and fire-safe mat placement with venue.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-ghee",
    name_local: "घी",
    name_english: "Ghee (clarified butter)",
    category: "general_setup",
    used_for_ritual_id: "rit-havan",
    quantity: "500 g",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-camphor",
    name_local: "कपूर",
    name_english: "Camphor",
    category: "general_setup",
    quantity: "1 box",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-incense",
    name_local: "अगरबत्ती",
    name_english: "Incense sticks",
    category: "general_setup",
    quantity: "2 packs",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-lighter",
    name_local: "माचिस / लाइटर",
    name_english: "Matchbox / lighter",
    category: "general_setup",
    quantity: "2",
    source: "other",
    responsibility: "planner",
    status: "needed",
    added_by_pandit: false,
    notes: "Backup lighter essential.",
    created_at: now,
    updated_at: now,
  },

  // ── Floral ──
  {
    id: "sam-jaimala",
    name_local: "जयमाला",
    name_english: "Jai mala garlands",
    category: "floral",
    used_for_ritual_id: "rit-jaimala",
    quantity: "2 large garlands (bride + groom)",
    source: "other",
    responsibility: "planner",
    status: "needed",
    added_by_pandit: false,
    notes: "Coordinate with Décor/florist — rose + marigold, substantial size.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-petals",
    name_local: "फूल पंखुड़ियाँ",
    name_english: "Flower petals (for guests to throw)",
    category: "floral",
    used_for_ritual_id: "rit-jaimala",
    quantity: "2 kg loose petals",
    source: "other",
    responsibility: "planner",
    status: "needed",
    added_by_pandit: false,
    notes: "Rose + marigold blend. Basket stations near aisle.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-mango-leaves",
    name_local: "आम के पत्ते",
    name_english: "Mango leaves",
    category: "floral",
    quantity: "1 small bundle",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "For kalash decoration.",
    created_at: now,
    updated_at: now,
  },

  // ── Food / Grain ──
  {
    id: "sam-rice",
    name_local: "अक्षत (चावल)",
    name_english: "Rice — akshata (uncooked)",
    category: "food_grain",
    used_for_ritual_id: "rit-aashirvad",
    quantity: "500 g",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "Mixed with a pinch of turmeric for color.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-haldi",
    name_local: "हल्दी",
    name_english: "Turmeric — haldi (powder + root)",
    category: "food_grain",
    quantity: "100 g powder + 2 roots",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-kumkum",
    name_local: "कुमकुम",
    name_english: "Kumkum (red vermillion powder)",
    category: "food_grain",
    quantity: "2 small containers",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "Separate from sindoor.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-coconut",
    name_local: "नारियल",
    name_english: "Coconut (whole, with husk)",
    category: "food_grain",
    quantity: "3",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-supari",
    name_local: "सुपारी",
    name_english: "Supari (betel nut)",
    category: "food_grain",
    quantity: "100 g",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-paan",
    name_local: "पान के पत्ते",
    name_english: "Paan leaves (betel)",
    category: "food_grain",
    quantity: "12 fresh leaves",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "Keep wrapped in damp paper — they wilt quickly.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-dates",
    name_local: "खजूर / सूखे मेवे",
    name_english: "Dates / dry fruits",
    category: "food_grain",
    quantity: "250 g assorted",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-honey",
    name_local: "शहद",
    name_english: "Honey",
    category: "food_grain",
    quantity: "1 small jar",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-fruits",
    name_local: "फल",
    name_english: "Fresh fruits (banana, apple)",
    category: "food_grain",
    quantity: "6 bananas, 6 apples",
    source: "other",
    responsibility: "planner",
    status: "needed",
    added_by_pandit: false,
    notes: "Day-of procurement — source fresh from local grocer.",
    created_at: now,
    updated_at: now,
  },

  // ── Fabric ──
  {
    id: "sam-mandap-cloth",
    name_local: "लाल चुनरी",
    name_english: "Red/maroon cloth for mandap seat",
    category: "fabric",
    quantity: "2 meters",
    source: "other",
    responsibility: "planner",
    status: "needed",
    added_by_pandit: false,
    notes: "Coordinate with Décor — should complement mandap florals.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-antarpat",
    name_local: "अंतरपट",
    name_english: "Antarpat (cloth curtain for Jaimala)",
    category: "fabric",
    used_for_ritual_id: "rit-jaimala",
    quantity: "6 x 6 ft embroidered cloth",
    source: "other",
    responsibility: "planner",
    status: "needed",
    added_by_pandit: false,
    notes: "Traditional red-and-gold preferred.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-chunri",
    name_local: "लाल चूनर",
    name_english: "Red chunri / dupatta for bride",
    category: "fabric",
    quantity: "1",
    source: "other",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes:
      "Used for head covering after sindoor. Confirm if it's part of the bridal outfit — if so, mark as confirmed.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-moli",
    name_local: "मौली / कलावा",
    name_english: "Sacred thread — moli (red-gold)",
    category: "fabric",
    quantity: "1 spool",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "Tied on wrists of couple and family members.",
    created_at: now,
    updated_at: now,
  },

  // ── Metal / Vessels ──
  {
    id: "sam-kalash",
    name_local: "कलश",
    name_english: "Kalash (brass water vessel)",
    category: "metal_vessels",
    quantity: "1",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "Decorated with mango leaves + coconut on top.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-bowls",
    name_local: "छोटे कटोरे",
    name_english: "Small brass bowls (for offerings)",
    category: "metal_vessels",
    quantity: "6",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-sindoor-container",
    name_local: "सिंदूर दानी",
    name_english: "Sindoor container + sindoor",
    category: "metal_vessels",
    used_for_ritual_id: "rit-sindoor",
    quantity: "1 decorated container + 50 g sindoor",
    source: "indian_grocery",
    responsibility: "brides_family",
    status: "needed",
    added_by_pandit: false,
    notes: "",
    created_at: now,
    updated_at: now,
  },

  // ── Personal items ──
  {
    id: "sam-mangalsutra",
    name_local: "मंगलसूत्र",
    name_english: "Mangalsutra",
    category: "personal_items",
    used_for_ritual_id: "rit-mangalsutra",
    quantity: "1",
    source: "other",
    responsibility: "grooms_family",
    status: "needed",
    added_by_pandit: false,
    notes:
      "Cross-ref Jewelry workspace. Ensure accessible — NOT packed away in luggage.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sam-rings",
    name_local: "अंगूठियां",
    name_english: "Wedding rings",
    category: "personal_items",
    quantity: "2",
    source: "other",
    responsibility: "grooms_family",
    status: "confirmed",
    added_by_pandit: false,
    notes: "With best man / maid of honor.",
    created_at: now,
    updated_at: now,
  },
];

// ── Logistics defaults ───────────────────────────────────────────────────

export const SEED_CEREMONY_LOGISTICS: CeremonyLogistics = {
  mandap_orientation: "east",
  mandap_dimensions: "12 x 12 ft",
  havan_kund_placement:
    "Center of mandap. Fire-safe mat required — confirm with venue.",
  fire_permit_needed: true,
  fire_permit_status: "Pending — check with venue coordinator",

  pandit_mic_type: "lapel",
  amplify_mantras: true,
  background_instrumental: true,
  background_instrumental_note:
    "Soft sitar during transitions only. Silent during mantras.",
  sound_check_time: "1:00 PM — 90 minutes before ceremony",

  shoe_removal_plan:
    "Numbered shoe racks at venue entrance. 400-capacity. Ushers hand out claim tickets.",
  water_available: true,
  weather_considerations:
    "Outdoor mandap — tent required. Check 10-day forecast starting T-14.",
  unplugged_ceremony: true,
  childrens_area: true,
  childrens_area_note:
    "Quiet corner at back with coloring pages and a designated caretaker (cousin Seema, confirmed).",

  photography_note:
    "Pre-position for Baraat by 5:45 PM. Varmala is the key emotional shot — two photographers, both profiles.",
  videography_note:
    "Lapel mic the pandit, bride, and groom before ceremony. Audio is critical — do not rely on boom.",
  dj_note:
    "Play baraat music 5:30–6:00 PM. Cut completely when pandit begins. Cue vidaai song ('Babul' — list at end of file) when bride rises from mandap.",
  decor_note:
    "Fire-safe mat placement before mandap florals are set up. Do not drape fabrics within 3 ft of havan kund.",

  updated_at: now,
};
