import type {
  PhotoCrewMember,
  PhotoDayOfSlot,
  PhotoDeliverable,
  PhotoRitual,
  PhotoShot,
  PhotoVIP,
} from "@/types/photography";

const CAT = "cat-photography";

// ── Ritual moments — canonical Indian ceremony guidance ────────────────────
// Pre-seeded with the full arc; couples toggle off rituals that don't apply
// (e.g. Sikh weddings skip pheras, regional variations drop milni, etc.).

export const SEED_PHOTO_RITUALS: PhotoRitual[] = [
  {
    id: "prt-ganesh",
    category_id: CAT,
    name: "Ganesh Puja",
    description: "Opening invocation to Lord Ganesh before the wedding begins — a small family-only puja.",
    key_moment: "Priest placing the tilak on the couple; close family circling the kalash.",
    duration: "20–30 minutes",
    position: "Close, but behind family — this is intimate, not staged.",
    applies: true,
    sort_order: 1,
  },
  {
    id: "prt-haldi",
    category_id: CAT,
    name: "Haldi",
    description: "Turmeric paste applied by family on the bride and groom separately. Joyful, messy, morning light.",
    key_moment: "Grandmother/aunties smearing haldi on face — and the bride laughing as it drips.",
    duration: "1–2 hours per side",
    position: "Low and close for hand-to-face; pull wide for group reactions.",
    applies: true,
    sort_order: 2,
  },
  {
    id: "prt-mehendi",
    category_id: CAT,
    name: "Mehendi",
    description: "Henna applied to the bride's hands and feet while family and friends gather around.",
    key_moment: "Close-up on hands mid-application, and the bride's reveal at the end.",
    duration: "4–6 hours (plan for candids, not continuous coverage)",
    position: "Seated angle, just above the artist's shoulder for the close; wide for the gathering.",
    applies: true,
    sort_order: 3,
  },
  {
    id: "prt-sangeet",
    category_id: CAT,
    name: "Sangeet",
    description: "Musical evening with family choreographies, speeches, and dancing.",
    key_moment: "Parents' solo/duet moments — these often aren't rehearsed for the camera.",
    duration: "3–5 hours",
    position: "Front-of-stage + roaming floor; a second shooter on the balcony helps.",
    applies: true,
    sort_order: 4,
  },
  {
    id: "prt-baraat",
    category_id: CAT,
    name: "Baraat",
    description: "Groom's procession — horse, dhol, dancing family arriving at the venue.",
    key_moment: "First beat of the dhol; groom atop the horse; family dancing at peak.",
    duration: "30–60 minutes",
    position: "Ahead of the procession walking backward, then alongside. A drone is a huge upgrade here.",
    applies: true,
    sort_order: 5,
  },
  {
    id: "prt-milni",
    category_id: CAT,
    name: "Milni",
    description: "Formal greeting between matching relatives of both families (grooms's uncle meets bride's uncle, etc.).",
    key_moment: "Garland exchange at each pairing; tilak by the priest.",
    duration: "15–30 minutes",
    position: "Side-on for the exchange, catching both faces in frame.",
    applies: true,
    sort_order: 6,
  },
  {
    id: "prt-varmala",
    category_id: CAT,
    name: "Var Mala / Jaimala",
    description: "Exchange of floral garlands between bride and groom, often playful — friends lift one side to delay.",
    key_moment: "Exchange at first attempt — crowd often lifts the groom or bride, so be ready to track upward.",
    duration: "5–10 minutes",
    position: "Front-center on a step, with a second shooter at a 45° angle. Don't back up — you'll lose the crowd.",
    applies: true,
    sort_order: 7,
  },
  {
    id: "prt-kanyadaan",
    category_id: CAT,
    name: "Kanyadaan",
    description: "Bride's father (or guardian) ritually gives her hand to the groom — emotionally the heaviest moment.",
    key_moment: "The father's hand over hers — and the look between father and daughter.",
    duration: "10–15 minutes",
    position: "Tight on hands from a low angle; then swing to the father's face. No flash — preserve the mood.",
    applies: true,
    sort_order: 8,
  },
  {
    id: "prt-pheras",
    category_id: CAT,
    name: "Mangal Pheras",
    description: "Seven circles around the sacred fire, each with a vow. The central ceremony.",
    key_moment: "Each phera's first step; the smoke rising; a clear overhead or side profile.",
    duration: "20–40 minutes",
    position: "One shooter overhead or on a ladder, one at ground level side-on. Avoid crossing the fire line.",
    applies: true,
    sort_order: 9,
  },
  {
    id: "prt-sindoor",
    category_id: CAT,
    name: "Sindoor Daan",
    description: "Groom applies sindoor (vermilion) to the bride's hair parting — marks her as married.",
    key_moment: "The application itself — close, tight, and respectful. It happens fast.",
    duration: "1–2 minutes",
    position: "Over the groom's shoulder, tight on the bride's face and hair.",
    applies: true,
    sort_order: 10,
  },
  {
    id: "prt-mangalsutra",
    category_id: CAT,
    name: "Mangalsutra",
    description: "Groom ties the sacred thread/necklace around the bride's neck.",
    key_moment: "The moment of tying — and the bride's expression after.",
    duration: "1–2 minutes",
    position: "Behind the bride, catching the groom's hands + her face. Or front-on if seating allows.",
    applies: true,
    sort_order: 11,
  },
  {
    id: "prt-jootachurai",
    category_id: CAT,
    name: "Joota Churai",
    description: "Bride's sisters/cousins steal the groom's shoes and negotiate a ransom.",
    key_moment: "The chase, the negotiation, and the cash exchange — all candid.",
    duration: "20–60 minutes of chaos",
    position: "Roaming, low and fast. A second shooter doubles your coverage.",
    applies: true,
    sort_order: 12,
  },
  {
    id: "prt-vidaai",
    category_id: CAT,
    name: "Vidaai",
    description: "Bride's farewell to her family — she throws rice back over her shoulder as she leaves.",
    key_moment: "The rice throw; the final hug with parents; the walk to the car.",
    duration: "15–30 minutes",
    position: "Behind the bride for the rice throw; then swing to catch parents' faces. No flash.",
    applies: true,
    sort_order: 13,
  },
  {
    id: "prt-griha",
    category_id: CAT,
    name: "Griha Pravesh",
    description: "Bride's first entry into the groom's home — kicks a pot of rice, steps on vermilion.",
    key_moment: "The moment the pot spills; the footprint on the threshold.",
    duration: "10–15 minutes",
    position: "From inside the doorway looking out, so both bride and threshold are in frame.",
    applies: false,
    sort_order: 14,
  },
];

// ── VIPs & family — example seed for Priya × Arjun demo wedding ────────────

export const SEED_PHOTO_VIPS: PhotoVIP[] = [
  {
    id: "pvip-001",
    category_id: CAT,
    name: "Sushila Sharma",
    relationship: "Bride's dadi (paternal grandmother)",
    side: "bride",
    tier: "immediate",
    must_capture: true,
    note: "In wheelchair — plan accessible angles. Will not be standing for group shots.",
    sort_order: 1,
  },
  {
    id: "pvip-002",
    category_id: CAT,
    name: "Rajesh Sharma",
    relationship: "Bride's father",
    side: "bride",
    tier: "immediate",
    must_capture: true,
    note: "Emotional during Kanyadaan — give him space, shoot tight on face.",
    sort_order: 2,
  },
  {
    id: "pvip-003",
    category_id: CAT,
    name: "Meera Sharma",
    relationship: "Bride's mother",
    side: "bride",
    tier: "immediate",
    must_capture: true,
    sort_order: 3,
  },
  {
    id: "pvip-004",
    category_id: CAT,
    name: "Vikram Mehta",
    relationship: "Groom's mamaji (maternal uncle)",
    side: "groom",
    tier: "extended",
    must_capture: true,
    note: "Flying in from London — limited time together, catch him during Sangeet.",
    sort_order: 4,
  },
  {
    id: "pvip-005",
    category_id: CAT,
    name: "Sunita Mehta",
    relationship: "Groom's mother",
    side: "groom",
    tier: "immediate",
    must_capture: true,
    sort_order: 5,
  },
  {
    id: "pvip-006",
    category_id: CAT,
    name: "Anil Mehta",
    relationship: "Groom's father",
    side: "groom",
    tier: "immediate",
    must_capture: true,
    sort_order: 6,
  },
  {
    id: "pvip-007",
    category_id: CAT,
    name: "Kavya Iyer",
    relationship: "Bride's best friend / maid of honour",
    side: "bride",
    tier: "close",
    must_capture: false,
    note: "Writing the MOH speech at Sangeet — capture her delivery and Priya's reaction.",
    sort_order: 7,
  },
  {
    id: "pvip-008",
    category_id: CAT,
    name: "Rohan Kapoor",
    relationship: "Groom's best man",
    side: "groom",
    tier: "close",
    must_capture: false,
    sort_order: 8,
  },
];

// ── Shot list — common Indian wedding shots, pre-seeded per event ──────────

export const SEED_PHOTO_SHOTS: PhotoShot[] = [
  // Haldi
  { id: "psh-hal-01", category_id: CAT, event: "haldi", moment: "Pre-ceremony setup", priority: "must", title: "Paste mixing — close-up on the bowl", vip_ids: [], sort_order: 1 },
  { id: "psh-hal-02", category_id: CAT, event: "haldi", moment: "Paste application", priority: "must", title: "Grandmother applying haldi", description: "First application is traditionally by the eldest.", vip_ids: ["pvip-001"], sort_order: 2 },
  { id: "psh-hal-03", category_id: CAT, event: "haldi", moment: "Candids", priority: "preferred", title: "Candid — bride reacting to the mess", vip_ids: [], sort_order: 3 },
  { id: "psh-hal-04", category_id: CAT, event: "haldi", moment: "Family moments", priority: "preferred", title: "Wide — all family in frame together", vip_ids: [], sort_order: 4 },

  // Mehendi
  { id: "psh-meh-01", category_id: CAT, event: "mehendi", moment: "Bridal mehendi", priority: "must", title: "Bridal mehendi — full reveal of hands", vip_ids: [], sort_order: 1 },
  { id: "psh-meh-02", category_id: CAT, event: "mehendi", moment: "Bridal mehendi", priority: "must", title: "Artist mid-application — close on hennaed fingers", vip_ids: [], sort_order: 2 },
  { id: "psh-meh-03", category_id: CAT, event: "mehendi", moment: "Details & reveal", priority: "preferred", title: "Groom's name hidden in the design — find-it shot", vip_ids: [], sort_order: 3 },
  { id: "psh-meh-04", category_id: CAT, event: "mehendi", moment: "Guest applications", priority: "preferred", title: "Sisters/cousins getting their own mehendi", vip_ids: [], sort_order: 4 },

  // Sangeet
  { id: "psh-san-01", category_id: CAT, event: "sangeet", moment: "Performances", priority: "must", title: "Parents' solo or duet performance", vip_ids: ["pvip-002", "pvip-003"], sort_order: 1 },
  { id: "psh-san-02", category_id: CAT, event: "sangeet", moment: "Performances", priority: "must", title: "Couple's opening dance", vip_ids: [], sort_order: 2 },
  { id: "psh-san-03", category_id: CAT, event: "sangeet", moment: "Speeches", priority: "preferred", title: "Maid of honour speech + reaction", vip_ids: ["pvip-007"], sort_order: 3 },
  { id: "psh-san-04", category_id: CAT, event: "sangeet", moment: "Dance floor", priority: "preferred", title: "Crowd dance floor — wide with stage lights", vip_ids: [], sort_order: 4 },

  // Baraat
  { id: "psh-bar-01", category_id: CAT, event: "baraat", moment: "Procession", priority: "must", title: "Groom's entrance on the horse", vip_ids: [], sort_order: 1 },
  { id: "psh-bar-02", category_id: CAT, event: "baraat", moment: "Procession", priority: "must", title: "Dhol player — tight on hands hitting the drum", vip_ids: [], sort_order: 2 },
  { id: "psh-bar-03", category_id: CAT, event: "baraat", moment: "Procession", priority: "preferred", title: "Drone — overhead of the procession", vip_ids: [], sort_order: 3 },
  { id: "psh-bar-04", category_id: CAT, event: "baraat", moment: "Family reactions", priority: "preferred", title: "Groom's face reactions mid-procession", vip_ids: [], sort_order: 4 },

  // Wedding (ceremony)
  { id: "psh-wed-01", category_id: CAT, event: "wedding", moment: "First look", priority: "must", title: "First look — orchard at golden hour", vip_ids: [], sort_order: 1 },
  { id: "psh-wed-02", category_id: CAT, event: "wedding", moment: "Var mala", priority: "must", title: "Var mala exchange — first attempt", vip_ids: [], sort_order: 2 },
  { id: "psh-wed-03", category_id: CAT, event: "wedding", moment: "Kanyadaan & pheras", priority: "must", title: "Kanyadaan — hands + father's face", vip_ids: ["pvip-002"], sort_order: 3 },
  { id: "psh-wed-04", category_id: CAT, event: "wedding", moment: "Kanyadaan & pheras", priority: "must", title: "All seven pheras — detail of the knot", vip_ids: [], sort_order: 4 },
  { id: "psh-wed-05", category_id: CAT, event: "wedding", moment: "Sindoor & mangalsutra", priority: "must", title: "Sindoor daan — the application moment", vip_ids: [], sort_order: 5 },
  { id: "psh-wed-06", category_id: CAT, event: "wedding", moment: "Sindoor & mangalsutra", priority: "must", title: "Mangalsutra — tying the thread", vip_ids: [], sort_order: 6 },
  { id: "psh-wed-07", category_id: CAT, event: "wedding", moment: "Family portraits", priority: "must", title: "Family portraits — bride's side", vip_ids: [], sort_order: 7 },
  { id: "psh-wed-08", category_id: CAT, event: "wedding", moment: "Family portraits", priority: "must", title: "Family portraits — groom's side", vip_ids: [], sort_order: 8 },
  { id: "psh-wed-09", category_id: CAT, event: "wedding", moment: "Vidaai", priority: "must", title: "Vidaai — rice throw over shoulder", vip_ids: [], sort_order: 9 },
  { id: "psh-wed-10", category_id: CAT, event: "wedding", moment: "Vidaai", priority: "preferred", title: "Joota churai — shoe-stealing negotiation", vip_ids: [], sort_order: 10 },
  { id: "psh-wed-11", category_id: CAT, event: "wedding", moment: "Family portraits", priority: "preferred", title: "Grandmother(s) seated — dignified portraits", vip_ids: ["pvip-001"], sort_order: 11 },

  // Reception
  { id: "psh-rec-01", category_id: CAT, event: "reception", moment: "Entrance", priority: "must", title: "Couple's entrance — backlit", vip_ids: [], sort_order: 1 },
  { id: "psh-rec-02", category_id: CAT, event: "reception", moment: "Toasts & cake", priority: "must", title: "Cake cutting", vip_ids: [], sort_order: 2 },
  { id: "psh-rec-03", category_id: CAT, event: "reception", moment: "Toasts & cake", priority: "preferred", title: "Toasts — speaker + reactions", vip_ids: [], sort_order: 3 },
  { id: "psh-rec-04", category_id: CAT, event: "reception", moment: "First dance", priority: "preferred", title: "Couple's first dance", vip_ids: [], sort_order: 4 },

  // General
  { id: "psh-gen-01", category_id: CAT, event: "general", moment: "Detail still-lifes", priority: "must", title: "Detail shots — invitation, rings, jewelry", vip_ids: [], sort_order: 1 },
  { id: "psh-gen-02", category_id: CAT, event: "general", moment: "Golden hour portraits", priority: "preferred", title: "Couple at the venue — editorial portrait set", vip_ids: [], sort_order: 2 },
];

// ── Day-of schedule ────────────────────────────────────────────────────────

export const SEED_PHOTO_DAY_OF: PhotoDayOfSlot[] = [
  {
    id: "pds-haldi",
    category_id: CAT,
    event: "haldi",
    arrival_time: "9:00 AM",
    location: "Leela Palace — poolside courtyard",
    lighting: "outdoor",
    golden_hour: "—",
    travel_time: "On-property",
    sort_order: 1,
  },
  {
    id: "pds-mehendi",
    category_id: CAT,
    event: "mehendi",
    arrival_time: "2:30 PM",
    location: "Leela Palace — garden pavilion",
    lighting: "mixed",
    coverage_gap: "Break from 6pm–7pm between Mehendi wrap and Sangeet setup.",
    travel_time: "On-property",
    sort_order: 2,
  },
  {
    id: "pds-sangeet",
    category_id: CAT,
    event: "sangeet",
    arrival_time: "6:30 PM",
    location: "Leela Palace — ballroom",
    lighting: "indoor",
    sort_order: 3,
  },
  {
    id: "pds-baraat",
    category_id: CAT,
    event: "baraat",
    arrival_time: "5:30 AM — be in position before dhol starts",
    location: "Temple driveway → main hall",
    lighting: "outdoor",
    golden_hour: "Sunrise 6:12 AM — baraat should peak around then.",
    sort_order: 4,
  },
  {
    id: "pds-wedding",
    category_id: CAT,
    event: "wedding",
    arrival_time: "4:00 AM (bride getting-ready)",
    location: "Bridal suite → mandap → family portrait lawn",
    lighting: "mixed",
    golden_hour: "7:30 AM — first look in orchard.",
    coverage_gap: "Lunch break 1pm–2pm; crew rotates.",
    travel_time: "5 min between suite and mandap",
    sort_order: 5,
  },
  {
    id: "pds-reception",
    category_id: CAT,
    event: "reception",
    arrival_time: "7:00 PM",
    location: "Taj Palace — ballroom",
    lighting: "indoor",
    travel_time: "45 min from Leela — crew transfers at 6pm.",
    sort_order: 6,
  },
];

// ── Crew ───────────────────────────────────────────────────────────────────

export const SEED_PHOTO_CREW: PhotoCrewMember[] = [
  {
    id: "pcrew-001",
    category_id: CAT,
    role: "second_shooter",
    name: "Aditi Rao",
    arrival_time: "With lead",
    handoff_note: "Owns groom-side coverage during Haldi/getting-ready; wide shots during pheras.",
    sort_order: 1,
  },
  {
    id: "pcrew-002",
    category_id: CAT,
    role: "videographer",
    name: "Frames by Ishaan",
    arrival_time: "30 min before lead",
    handoff_note: "Share mandap angle plan so we don't cross each other. Audio runs off couple's lapels.",
    sort_order: 2,
  },
  {
    id: "pcrew-003",
    category_id: CAT,
    role: "drone",
    name: "SkyLens",
    arrival_time: "Baraat call time (5:00 AM)",
    handoff_note: "Cleared with venue for 48h notice. Grounded during pheras.",
    sort_order: 3,
  },
  {
    id: "pcrew-004",
    category_id: CAT,
    role: "assistant",
    name: "Kabir Mehta",
    arrival_time: "With lead",
    handoff_note: "Lighting + card runner. Dual-card backup at end of each event.",
    sort_order: 4,
  },
];

// ── Deliverables ───────────────────────────────────────────────────────────

export const SEED_PHOTO_DELIVERABLES: PhotoDeliverable[] = [
  {
    id: "pdl-001",
    category_id: CAT,
    kind: "same_day",
    name: "Sangeet teaser reel",
    due_label: "Within 6 hours of wrap",
    notes: "60s vertical cut for Sangeet afterparty + socials.",
    sort_order: 1,
  },
  {
    id: "pdl-002",
    category_id: CAT,
    kind: "sneak_peek",
    name: "Sneak peek gallery",
    due_label: "72 hours after wedding day",
    notes: "30 hero frames. Watermarked web-res, shareable link.",
    sort_order: 2,
  },
  {
    id: "pdl-003",
    category_id: CAT,
    kind: "full_gallery",
    name: "Full edited gallery",
    due_label: "6–8 weeks post-wedding",
    notes: "1,200+ images across all events. Two edit rounds included.",
    sort_order: 3,
  },
  {
    id: "pdl-004",
    category_id: CAT,
    kind: "raw",
    name: "Raw files",
    due_label: "Retained by photographer — not delivered",
    notes: "Archived for 2 years. Re-edit requests billable.",
    sort_order: 4,
  },
  {
    id: "pdl-005",
    category_id: CAT,
    kind: "album",
    name: "Heirloom album",
    due_label: "4 months post-wedding",
    notes: "40 spreads, two design rounds, linen cover. Parents' duplicates at cost.",
    sort_order: 5,
  },
  {
    id: "pdl-006",
    category_id: CAT,
    kind: "print",
    name: "Framed prints",
    due_label: "With album delivery",
    notes: "3× 16x20 fine-art prints, archival paper.",
    sort_order: 6,
  },
  {
    id: "pdl-007",
    category_id: CAT,
    kind: "usage_rights",
    name: "Usage rights",
    due_label: "Perpetual, personal use",
    notes: "Photographer retains commercial use + portfolio rights. Couple gets personal/social rights in perpetuity.",
    sort_order: 7,
  },
];
