// ── Sangeet Planner seed ──────────────────────────────────────────────────
// Eight acts of a typical Indian wedding sangeet — a mix of family group
// dances, a comedy skit, parents' surprise, friends' tribute, slideshow.
// Mirrors the kind of running order most couples build over WhatsApp
// chaos for 6 weeks, now in one place.

import type { SangeetAct } from "@/types/music";

export const DEMO_MUSIC_WEDDING_ID = "wedding-demo";

const t0 = "2026-04-01T00:00:00.000Z";
const daysFromNow = (d: number) =>
  new Date(Date.now() + d * 24 * 60 * 60 * 1000).toISOString();

let trkCounter = 0;
const trk = (title: string, artist?: string, moment?: string) => ({
  id: `seed-sg-trk-${++trkCounter}`,
  title,
  artist,
  moment,
  added_by: "priya",
  added_at: t0,
});

export const SEED_SANGEET_ACTS: SangeetAct[] = [
  {
    id: "act-emcee-welcome",
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    name: "Emcee welcome + house rules",
    type: "speech",
    performers: [{ name: "Rajiv Menon (MC)", confirmed: true }],
    songs: [trk("Soft instrumental walk-in", "DJ Pranav curated")],
    estimated_minutes: 5,
    status: "ready",
    needs_screen: false,
    needs_lighting: true,
    wireless_mics: 1,
    sort_order: 1,
    transition_after: "Hold mic, fade to dim — bride's friends take the stage.",
    next_rehearsal_at: daysFromNow(7),
    rehearsal_location: "Skype with Rajiv",
    created_at: t0,
    updated_at: t0,
  },
  {
    id: "act-brides-friends",
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    name: "Bride's friends — Bollywood tribute medley",
    type: "dance",
    performers: [
      { name: "Maya Iyer", confirmed: true, note: "Lead choreographer" },
      { name: "Riya Patel", confirmed: true },
      { name: "Tanya Shah", confirmed: true },
      { name: "Anjali Desai", confirmed: false, note: "In London — flying in T-3" },
      { name: "Shreya Kumar", confirmed: true },
    ],
    songs: [
      trk("Dilbar", "Nora Fatehi", "Opening 60s"),
      trk("Saami Saami", "Saami Saami", "Build"),
      trk("Kala Chashma", "Badshah", "Peak"),
    ],
    estimated_minutes: 6,
    status: "in_rehearsal",
    needs_screen: false,
    needs_lighting: true,
    wireless_mics: 0,
    sort_order: 2,
    transition_after:
      "Hard cut to Karan's intro VO over slideshow — comedy skit comes next.",
    last_rehearsed_at: daysFromNow(-5),
    next_rehearsal_at: daysFromNow(2),
    rehearsal_location: "Maya's place, Bandra",
    created_at: t0,
    updated_at: t0,
  },
  {
    id: "act-grooms-brothers-skit",
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    name: "Groom's brothers — Arjun's life in 3 acts (skit)",
    type: "skit",
    performers: [
      { name: "Karan Mehta", confirmed: true, note: "Older brother — wrote it" },
      { name: "Vikram Mehta", confirmed: true },
      { name: "Rohan Mehta (cousin)", confirmed: false },
    ],
    songs: [trk("Comedy bgm cues", undefined, "Spot beats per script")],
    estimated_minutes: 8,
    status: "not_started",
    needs_screen: true,
    needs_lighting: true,
    wireless_mics: 3,
    props: "Vintage hostel mattress, fake exam papers, Arjun's first cricket bat",
    sort_order: 3,
    transition_after: "Lights down. Slideshow comes up cold.",
    next_rehearsal_at: daysFromNow(10),
    rehearsal_location: "Karan's apartment",
    created_at: t0,
    updated_at: t0,
  },
  {
    id: "act-slideshow",
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    name: "Childhood-to-engagement slideshow",
    type: "slideshow",
    performers: [{ name: "Tanya Shah", confirmed: true, note: "Edited the slideshow" }],
    songs: [
      trk("Tum Hi Ho", "Arijit Singh", "Slideshow underscore"),
      trk("Kabira", "Arijit Singh / Tochi Raina", "Engagement section"),
    ],
    estimated_minutes: 5,
    status: "ready",
    needs_screen: true,
    needs_lighting: false,
    wireless_mics: 0,
    sort_order: 4,
    transition_after: "Slideshow ends on engagement photo. Lights up. Parents come in.",
    next_rehearsal_at: daysFromNow(7),
    created_at: t0,
    updated_at: t0,
  },
  {
    id: "act-parents-surprise",
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    name: "Parents' surprise — joint dance to Lag Ja Gale",
    type: "surprise",
    performers: [
      { name: "Priya's mother", confirmed: true },
      { name: "Priya's father", confirmed: true },
      { name: "Arjun's mother", confirmed: true },
      { name: "Arjun's father", confirmed: false, note: "Hesitant — Maya is convincing him" },
    ],
    songs: [
      trk("Lag Ja Gale", "Lata Mangeshkar", "Slow opening"),
      trk("Maa", "Shankar Mahadevan", "Surprise key change"),
    ],
    estimated_minutes: 6,
    status: "in_rehearsal",
    needs_screen: false,
    needs_lighting: true,
    wireless_mics: 0,
    surprise: true,
    surprise_for: ["couple"],
    sort_order: 5,
    transition_after:
      "Couple invited up — flow straight into their first dance (next act).",
    last_rehearsed_at: daysFromNow(-3),
    next_rehearsal_at: daysFromNow(4),
    rehearsal_location: "Zoom — Aarti aunty leads",
    created_at: t0,
    updated_at: t0,
  },
  {
    id: "act-couple-first-dance",
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    name: "Couple's first dance",
    type: "dance",
    performers: [
      { name: "Priya", confirmed: true },
      { name: "Arjun", confirmed: true },
    ],
    songs: [trk("Tujh Mein Rab Dikhta Hai", "Roop Kumar Rathod", "Couple's song")],
    estimated_minutes: 4,
    status: "in_rehearsal",
    needs_screen: false,
    needs_lighting: true,
    wireless_mics: 0,
    sort_order: 6,
    transition_after:
      "Emcee invites everyone to the floor — DJ Pranav takes over.",
    last_rehearsed_at: daysFromNow(-2),
    next_rehearsal_at: daysFromNow(5),
    rehearsal_location: "Choreographer Neha's studio",
    created_at: t0,
    updated_at: t0,
  },
  {
    id: "act-cousins-mashup",
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    name: "Kapoor cousins — high-energy mashup",
    type: "dance",
    performers: [
      { name: "Aarav Kapoor", confirmed: true, note: "Lead" },
      { name: "Ishaan Kapoor", confirmed: true },
      { name: "Tara Kapoor", confirmed: true },
      { name: "Diya Kapoor", confirmed: false },
      { name: "Vivaan Kapoor", confirmed: true },
    ],
    songs: [
      trk("Mundian To Bach Ke", "Panjabi MC", "Bhangra opener"),
      trk("Patola", "Guru Randhawa", "Mid"),
      trk("Naacho Naacho", "Vishal Mishra", "Peak"),
    ],
    estimated_minutes: 7,
    status: "not_started",
    needs_screen: false,
    needs_lighting: true,
    wireless_mics: 0,
    sort_order: 7,
    transition_after:
      "End on hard hit — strobe — emcee invites priya's dad up for closing speech.",
    next_rehearsal_at: daysFromNow(8),
    rehearsal_location: "Yet to be scheduled",
    created_at: t0,
    updated_at: t0,
  },
  {
    id: "act-fathers-toast",
    wedding_id: DEMO_MUSIC_WEDDING_ID,
    name: "Father of the bride — closing toast",
    type: "speech",
    performers: [{ name: "Priya's father", confirmed: true }],
    songs: [trk("Soft underscore", undefined, "Quiet bgm")],
    estimated_minutes: 4,
    status: "ready",
    needs_screen: false,
    needs_lighting: true,
    wireless_mics: 1,
    sort_order: 8,
    transition_after: "Glass clink → DJ Pranav opens dance floor with Mundian remix.",
    created_at: t0,
    updated_at: t0,
  },
];
