import type {
  StoreProduct,
  StoreVendor,
  StoreVariant,
  StockStatus,
  StoreCategory,
} from "@/lib/link-preview/types";

// Ananya native catalog. In production these come from Supabase (`products`,
// `product_variants`, `vendors` tables). Here we hand-seed a curated sample
// so the catalog modal feels real end-to-end.

const IMG = {
  // Unsplash photo IDs; keep as a single source so swaps are cheap.
  lehenga1: "https://images.unsplash.com/photo-1610030469668-8e45b5c2f8d6?w=1200&q=80",
  lehenga2: "https://images.unsplash.com/photo-1583391733956-6c78276477e1?w=1200&q=80",
  sherwani1: "https://images.unsplash.com/photo-1617096199277-ad93d8b3dd29?w=1200&q=80",
  saree1: "https://images.unsplash.com/photo-1610030006870-2f4e8c9f2b28?w=1200&q=80",
  kundan1: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=1200&q=80",
  polki1: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=1200&q=80",
  chudi1: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=1200&q=80",
  maangtikka: "https://images.unsplash.com/photo-1535632066927-ec3df4ef1ae2?w=1200&q=80",
  marigold: "https://images.unsplash.com/photo-1604322611922-b4c0b44e3d70?w=1200&q=80",
  mandap1: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80",
  diya1: "https://images.unsplash.com/photo-1572375992501-4b0892d50c69?w=1200&q=80",
  centerpiece: "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=1200&q=80",
  invite1: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200&q=80",
  invite2: "https://images.unsplash.com/photo-1546026423-cc4642628d2b?w=1200&q=80",
  rsvp1: "https://images.unsplash.com/photo-1495224814653-94f36c0a31ea?w=1200&q=80",
  thali1: "https://images.unsplash.com/photo-1514533212735-5df27d970db0?w=1200&q=80",
  glasses: "https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&q=80",
  teaset: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=1200&q=80",
  mithai: "https://images.unsplash.com/photo-1615220368123-9b5d9d8bfda8?w=1200&q=80",
  return1: "https://images.unsplash.com/photo-1589998059171-988d887df646?w=1200&q=80",
  return2: "https://images.unsplash.com/photo-1602872030219-ad2b9a54315c?w=1200&q=80",
  dupatta: "https://images.unsplash.com/photo-1610189019831-58baaaa6b4a1?w=1200&q=80",
  pagdi: "https://images.unsplash.com/photo-1606293459209-15b4d52fdaeb?w=1200&q=80",
  mojari: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=1200&q=80",
};

// ── Vendors / Artisans ──────────────────────────────────────────────────────

export const STORE_VENDORS: StoreVendor[] = [
  {
    id: "v-sabya-atelier",
    name: "Sabyavati Atelier",
    tagline: "Hand-embroidered couture from Kolkata",
    origin: "Kolkata, West Bengal",
    bio: "A fourth-generation embroidery house specializing in zardozi and dabka work. Each piece is finished by a single master karigar to preserve stitch consistency.",
    portfolioImages: [IMG.lehenga1, IMG.lehenga2, IMG.sherwani1, IMG.saree1],
    rating: 4.9,
    reviewCount: 148,
    foundedYear: 1987,
    specialties: ["Zardozi", "Dabka", "Bridal Couture"],
  },
  {
    id: "v-jaipur-heritage",
    name: "Jaipur Heritage Jewels",
    tagline: "Kundan & polki from the pink city",
    origin: "Jaipur, Rajasthan",
    bio: "Family-run meenakari and kundan workshop operating since 1923. Stones are set in 22k gold using traditional thappa techniques.",
    portfolioImages: [IMG.kundan1, IMG.polki1, IMG.maangtikka, IMG.chudi1],
    rating: 4.8,
    reviewCount: 212,
    foundedYear: 1923,
    specialties: ["Kundan", "Polki", "Meenakari"],
  },
  {
    id: "v-marigold-studio",
    name: "Marigold Studio",
    tagline: "Floral installations & ceremony decor",
    origin: "Bangalore, Karnataka",
    bio: "Ethically-sourced florals paired with sustainable structural design. Specialists in mandap architecture and hanging installations.",
    portfolioImages: [IMG.marigold, IMG.mandap1, IMG.centerpiece, IMG.diya1],
    rating: 4.7,
    reviewCount: 89,
    foundedYear: 2016,
    specialties: ["Mandaps", "Floral Arches", "Sustainable Decor"],
  },
  {
    id: "v-letterpress-lane",
    name: "Letterpress Lane",
    tagline: "Letterpress & foil stationery studio",
    origin: "Mumbai, Maharashtra",
    bio: "A boutique press running 1920s Heidelberg machines. Each invitation suite is proofed on hand-deckled cotton paper before final run.",
    portfolioImages: [IMG.invite1, IMG.invite2, IMG.rsvp1],
    rating: 4.9,
    reviewCount: 167,
    foundedYear: 2014,
    specialties: ["Letterpress", "Foil", "Bespoke Suites"],
  },
  {
    id: "v-moradabad-brass",
    name: "Moradabad Brass Co.",
    tagline: "Heirloom brass dinnerware",
    origin: "Moradabad, Uttar Pradesh",
    bio: "Brass artisans crafting thalis and serveware using sand-casting techniques passed down through five generations.",
    portfolioImages: [IMG.thali1, IMG.teaset, IMG.glasses],
    rating: 4.6,
    reviewCount: 74,
    foundedYear: 1962,
    specialties: ["Brass", "Copper", "Serveware"],
  },
  {
    id: "v-sweetshop-royale",
    name: "Sweetshop Royale",
    tagline: "Curated mithai & return gift boxes",
    origin: "Delhi, NCR",
    bio: "A concierge mithai service partnering with heritage halwais across India. Boxes are assembled to order with 72-hour freshness guarantee.",
    portfolioImages: [IMG.mithai, IMG.return1, IMG.return2],
    rating: 4.8,
    reviewCount: 203,
    foundedYear: 2019,
    specialties: ["Mithai", "Return Gifts", "Custom Packaging"],
  },
  {
    id: "v-benares-weaves",
    name: "Benares Weaves",
    tagline: "Pure Banarasi silk weavers",
    origin: "Varanasi, Uttar Pradesh",
    bio: "A collective of master weavers producing Banarasi sarees and dupattas in pure silk with real zari. Each piece takes 4-8 weeks on handloom.",
    portfolioImages: [IMG.saree1, IMG.dupatta],
    rating: 4.9,
    reviewCount: 121,
    foundedYear: 1978,
    specialties: ["Banarasi", "Silk", "Real Zari"],
  },
  {
    id: "v-punjabi-saddlery",
    name: "Punjabi Saddlery",
    tagline: "Groom accessories & mojari",
    origin: "Amritsar, Punjab",
    bio: "Hand-crafted groom accessories including pagdis, mojari, and sehra. Known for crystal-work pagdis worn at royal weddings.",
    portfolioImages: [IMG.pagdi, IMG.mojari, IMG.sherwani1],
    rating: 4.7,
    reviewCount: 58,
    foundedYear: 2001,
    specialties: ["Pagdi", "Mojari", "Sehra"],
  },
];

const VENDOR_BY_ID = new Map(STORE_VENDORS.map((v) => [v.id, v]));

export function getStoreVendor(id: string | null): StoreVendor | null {
  if (!id) return null;
  return VENDOR_BY_ID.get(id) ?? null;
}

// ── Variant helpers ────────────────────────────────────────────────────────

function sizeVariants(stock: StockStatus = "in_stock"): StoreVariant[] {
  return [
    { id: "xs", label: "XS", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: stock, stockCount: null },
    { id: "s", label: "S", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: stock, stockCount: null },
    { id: "m", label: "M", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: stock, stockCount: null },
    { id: "l", label: "L", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: stock, stockCount: null },
    { id: "xl", label: "XL", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: stock, stockCount: null },
  ];
}

function colorVariants(colors: { id: string; label: string; stock?: StockStatus }[]): StoreVariant[] {
  return colors.map((c) => ({
    id: c.id,
    label: c.label,
    attribute: "Color",
    priceDelta: 0,
    leadTimeDeltaDays: 0,
    stockStatus: c.stock ?? "in_stock",
    stockCount: null,
  }));
}

function monogramOption(): StoreVariant[] {
  return [
    { id: "plain", label: "Plain", attribute: "Customization", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
    { id: "monogrammed", label: "Monogrammed", attribute: "Customization", priceDelta: 1800, leadTimeDeltaDays: 14, stockStatus: "made_to_order", stockCount: null },
  ];
}

// ── Products ────────────────────────────────────────────────────────────────

const NOW = "2026-03-01T00:00:00.000Z";

export const STORE_PRODUCTS: StoreProduct[] = [
  // ── Attire ──
  {
    id: "p-lehenga-anarkali",
    title: "Anarkali Bridal Lehenga · Ruby Zardozi",
    description:
      "A crimson silk lehenga with 180 hours of hand zardozi. The dupatta features a scalloped gota border. Includes a fitted blouse in matching silk.",
    category: "attire",
    vendorId: "v-sabya-atelier",
    heroImage: IMG.lehenga1,
    gallery: [IMG.lehenga1, IMG.lehenga2, IMG.dupatta],
    basePrice: 84000,
    currency: "USD",
    stockStatus: "made_to_order",
    stockCount: null,
    baseLeadTimeDays: 56,
    region: "Kolkata",
    material: "Silk",
    color: "Ruby",
    tags: ["bridal", "lehenga", "zardozi"],
    variants: [...sizeVariants("made_to_order"), ...monogramOption()],
    isFeatured: true,
    isNewArrival: false,
    popularity: 94,
    createdAt: NOW,
  },
  {
    id: "p-sherwani-ivory",
    title: "Ivory Sherwani · Gota Patti Hand-work",
    description:
      "Ivory raw silk sherwani with gota patti detailing along the placket and cuffs. Pairs with a brocade-lined stole.",
    category: "attire",
    vendorId: "v-sabya-atelier",
    heroImage: IMG.sherwani1,
    gallery: [IMG.sherwani1, IMG.pagdi],
    basePrice: 62000,
    currency: "USD",
    stockStatus: "made_to_order",
    stockCount: null,
    baseLeadTimeDays: 42,
    region: "Kolkata",
    material: "Raw Silk",
    color: "Ivory",
    tags: ["groom", "sherwani", "gota"],
    variants: sizeVariants("made_to_order"),
    isFeatured: true,
    isNewArrival: true,
    popularity: 88,
    createdAt: NOW,
  },
  {
    id: "p-saree-benares-red",
    title: "Banarasi Silk Saree · Deep Crimson",
    description:
      "Pure Banarasi silk in deep crimson with real zari bootis. Handloom-woven over six weeks by a single weaver.",
    category: "attire",
    vendorId: "v-benares-weaves",
    heroImage: IMG.saree1,
    gallery: [IMG.saree1, IMG.dupatta],
    basePrice: 28000,
    currency: "USD",
    stockStatus: "low_stock",
    stockCount: 3,
    baseLeadTimeDays: 5,
    region: "Varanasi",
    material: "Silk",
    color: "Crimson",
    tags: ["saree", "banarasi", "handloom"],
    variants: colorVariants([
      { id: "crimson", label: "Crimson" },
      { id: "gold", label: "Antique Gold" },
      { id: "forest", label: "Forest Green", stock: "low_stock" },
    ]),
    isFeatured: false,
    isNewArrival: false,
    popularity: 82,
    createdAt: NOW,
  },
  {
    id: "p-dupatta-gota",
    title: "Gota Patti Dupatta · Saffron",
    description: "Lightweight tulle dupatta finished with gota patti scalloped borders.",
    category: "attire",
    vendorId: "v-sabya-atelier",
    heroImage: IMG.dupatta,
    gallery: [IMG.dupatta],
    basePrice: 6800,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: 12,
    baseLeadTimeDays: 5,
    region: "Kolkata",
    material: "Tulle",
    color: "Saffron",
    tags: ["dupatta", "gota"],
    variants: colorVariants([
      { id: "saffron", label: "Saffron" },
      { id: "blush", label: "Blush" },
      { id: "ivory", label: "Ivory" },
    ]),
    isFeatured: false,
    isNewArrival: true,
    popularity: 64,
    createdAt: NOW,
  },
  {
    id: "p-pagdi-crystal",
    title: "Crystal-work Pagdi · Gold",
    description: "Groom pagdi with Swarovski crystal detailing. Adjustable fit, includes a ceremonial kalgi brooch.",
    category: "attire",
    vendorId: "v-punjabi-saddlery",
    heroImage: IMG.pagdi,
    gallery: [IMG.pagdi],
    basePrice: 14500,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: 6,
    baseLeadTimeDays: 7,
    region: "Amritsar",
    material: "Silk, Crystal",
    color: "Gold",
    tags: ["groom", "pagdi"],
    variants: colorVariants([
      { id: "gold", label: "Gold" },
      { id: "ivory", label: "Ivory" },
      { id: "ruby", label: "Ruby" },
    ]),
    isFeatured: false,
    isNewArrival: false,
    popularity: 58,
    createdAt: NOW,
  },
  {
    id: "p-mojari-gold",
    title: "Hand-stitched Mojari · Gold Embroidery",
    description: "Leather mojari with gold thread embroidery. Finished with a pointed toe in traditional Rajasthani style.",
    category: "attire",
    vendorId: "v-punjabi-saddlery",
    heroImage: IMG.mojari,
    gallery: [IMG.mojari],
    basePrice: 4200,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: 24,
    baseLeadTimeDays: 5,
    region: "Amritsar",
    material: "Leather",
    color: "Gold",
    tags: ["mojari", "groom"],
    variants: [
      { id: "7", label: "UK 7", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "8", label: "UK 8", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "9", label: "UK 9", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "10", label: "UK 10", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "low_stock", stockCount: 2 },
      { id: "11", label: "UK 11", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "sold_out", stockCount: 0 },
    ],
    isFeatured: false,
    isNewArrival: false,
    popularity: 51,
    createdAt: NOW,
  },

  // ── Jewelry ──
  {
    id: "p-kundan-choker",
    title: "Kundan Choker · Emerald Drops",
    description:
      "22k gold kundan choker with uncut emerald drops and pearl fringe. Comes with matching jhumkas.",
    category: "jewelry",
    vendorId: "v-jaipur-heritage",
    heroImage: IMG.kundan1,
    gallery: [IMG.kundan1, IMG.polki1],
    basePrice: 48000,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: 2,
    baseLeadTimeDays: 10,
    region: "Jaipur",
    material: "22k Gold, Kundan, Emerald",
    color: "Gold",
    tags: ["necklace", "kundan", "bridal"],
    variants: colorVariants([
      { id: "emerald", label: "Emerald" },
      { id: "ruby", label: "Ruby", stock: "made_to_order" },
    ]),
    isFeatured: true,
    isNewArrival: false,
    popularity: 96,
    createdAt: NOW,
  },
  {
    id: "p-polki-bridal",
    title: "Polki Bridal Set · Complete",
    description:
      "Heritage polki bridal set: necklace, earrings, maang tikka, nath, and haath phool. Hand-set in 22k gold.",
    category: "jewelry",
    vendorId: "v-jaipur-heritage",
    heroImage: IMG.polki1,
    gallery: [IMG.polki1, IMG.maangtikka, IMG.chudi1],
    basePrice: 125000,
    currency: "USD",
    stockStatus: "made_to_order",
    stockCount: null,
    baseLeadTimeDays: 45,
    region: "Jaipur",
    material: "22k Gold, Polki",
    color: "Gold",
    tags: ["bridal set", "polki", "heirloom"],
    variants: [],
    isFeatured: true,
    isNewArrival: false,
    popularity: 91,
    createdAt: NOW,
  },
  {
    id: "p-maang-tikka",
    title: "Meenakari Maang Tikka",
    description: "Delicate meenakari maang tikka with pearl fringe, finished in 22k gold plate.",
    category: "jewelry",
    vendorId: "v-jaipur-heritage",
    heroImage: IMG.maangtikka,
    gallery: [IMG.maangtikka],
    basePrice: 8400,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: 7,
    baseLeadTimeDays: 5,
    region: "Jaipur",
    material: "Gold-plate, Meenakari",
    color: "Gold",
    tags: ["maang tikka", "meenakari"],
    variants: colorVariants([
      { id: "gold", label: "Gold" },
      { id: "rose", label: "Rose Gold" },
      { id: "silver", label: "Silver" },
    ]),
    isFeatured: false,
    isNewArrival: true,
    popularity: 72,
    createdAt: NOW,
  },
  {
    id: "p-chudi-set",
    title: "Wedding Chudi Set · 24 pcs",
    description: "Traditional wedding chudi set with meenakari accents. Sold in 24-piece matched set.",
    category: "jewelry",
    vendorId: "v-jaipur-heritage",
    heroImage: IMG.chudi1,
    gallery: [IMG.chudi1],
    basePrice: 5600,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: 18,
    baseLeadTimeDays: 4,
    region: "Jaipur",
    material: "Brass, Meenakari",
    color: "Red",
    tags: ["chudi", "bangles"],
    variants: [
      { id: "2-4", label: "2.4 (Small)", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "2-6", label: "2.6 (Medium)", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "2-8", label: "2.8 (Large)", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "low_stock", stockCount: 1 },
    ],
    isFeatured: false,
    isNewArrival: false,
    popularity: 66,
    createdAt: NOW,
  },

  // ── Decor ──
  {
    id: "p-mandap-rose-gold",
    title: "Rose Gold Mandap · Full Installation",
    description:
      "A four-pillar mandap finished in rose-gold with draped ivory silk and fresh floral arches. Installation crew included.",
    category: "decor",
    vendorId: "v-marigold-studio",
    heroImage: IMG.mandap1,
    gallery: [IMG.mandap1, IMG.marigold, IMG.centerpiece],
    basePrice: 185000,
    currency: "USD",
    stockStatus: "made_to_order",
    stockCount: null,
    baseLeadTimeDays: 60,
    region: "Bangalore",
    material: "Wood, Silk, Fresh Florals",
    color: "Rose Gold",
    tags: ["mandap", "ceremony", "installation"],
    variants: [
      { id: "rose-gold", label: "Rose Gold", attribute: "Color", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "made_to_order", stockCount: null },
      { id: "ivory", label: "Ivory & Saffron", attribute: "Color", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "made_to_order", stockCount: null },
      { id: "emerald", label: "Emerald & Gold", attribute: "Color", priceDelta: 12000, leadTimeDeltaDays: 7, stockStatus: "made_to_order", stockCount: null },
    ],
    isFeatured: true,
    isNewArrival: false,
    popularity: 89,
    createdAt: NOW,
  },
  {
    id: "p-marigold-garland",
    title: "Fresh Marigold Garland · 50ft",
    description:
      "50 feet of hand-tied fresh marigold garland. Delivered day-of for ceremony backdrop or entrance draping.",
    category: "decor",
    vendorId: "v-marigold-studio",
    heroImage: IMG.marigold,
    gallery: [IMG.marigold],
    basePrice: 1200,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: null,
    baseLeadTimeDays: 2,
    region: "Bangalore",
    material: "Fresh Marigold",
    color: "Saffron",
    tags: ["florals", "garland", "fresh"],
    variants: [
      { id: "25ft", label: "25 ft", attribute: "Length", priceDelta: -600, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "50ft", label: "50 ft", attribute: "Length", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "100ft", label: "100 ft", attribute: "Length", priceDelta: 1200, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
    ],
    isFeatured: false,
    isNewArrival: true,
    popularity: 78,
    createdAt: NOW,
  },
  {
    id: "p-diya-brass-set",
    title: "Brass Diya Set · 24 pieces",
    description: "Hand-cast brass diyas in a graduated set. Pairs beautifully with mehendi & haldi ceremony decor.",
    category: "decor",
    vendorId: "v-moradabad-brass",
    heroImage: IMG.diya1,
    gallery: [IMG.diya1],
    basePrice: 3800,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: 14,
    baseLeadTimeDays: 5,
    region: "Moradabad",
    material: "Brass",
    color: "Brass",
    tags: ["diya", "brass", "ceremony"],
    variants: [],
    isFeatured: false,
    isNewArrival: false,
    popularity: 60,
    createdAt: NOW,
  },
  {
    id: "p-centerpiece-rose",
    title: "Rose & Jasmine Centerpiece · per table",
    description: "Arranged centerpiece of imported roses and local jasmine in a brass urli. Priced per table.",
    category: "decor",
    vendorId: "v-marigold-studio",
    heroImage: IMG.centerpiece,
    gallery: [IMG.centerpiece],
    basePrice: 480,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: null,
    baseLeadTimeDays: 3,
    region: "Bangalore",
    material: "Fresh Florals, Brass",
    color: "Pink",
    tags: ["centerpiece", "florals"],
    variants: [],
    isFeatured: false,
    isNewArrival: true,
    popularity: 55,
    createdAt: NOW,
  },

  // ── Stationery ──
  {
    id: "p-invite-suite-letterpress",
    title: "Letterpress Invitation Suite · 100",
    description:
      "Three-piece letterpress suite (invite, RSVP, details card) on cotton paper. Includes envelope liner and wax seal.",
    category: "stationery",
    vendorId: "v-letterpress-lane",
    heroImage: IMG.invite1,
    gallery: [IMG.invite1, IMG.invite2, IMG.rsvp1],
    basePrice: 2400,
    currency: "USD",
    stockStatus: "made_to_order",
    stockCount: null,
    baseLeadTimeDays: 28,
    region: "Mumbai",
    material: "Cotton Paper",
    color: "Ivory",
    tags: ["invitation", "letterpress", "suite"],
    variants: [
      { id: "50", label: "50 suites", attribute: "Quantity", priceDelta: -900, leadTimeDeltaDays: -4, stockStatus: "made_to_order", stockCount: null },
      { id: "100", label: "100 suites", attribute: "Quantity", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "made_to_order", stockCount: null },
      { id: "200", label: "200 suites", attribute: "Quantity", priceDelta: 1600, leadTimeDeltaDays: 7, stockStatus: "made_to_order", stockCount: null },
      { id: "foil", label: "Gold Foil Upgrade", attribute: "Customization", priceDelta: 900, leadTimeDeltaDays: 10, stockStatus: "made_to_order", stockCount: null },
    ],
    isFeatured: true,
    isNewArrival: false,
    popularity: 86,
    createdAt: NOW,
  },
  {
    id: "p-rsvp-cards",
    title: "Hand-deckled RSVP Cards · 100",
    description: "Hand-torn cotton paper RSVP cards with matching reply envelopes.",
    category: "stationery",
    vendorId: "v-letterpress-lane",
    heroImage: IMG.rsvp1,
    gallery: [IMG.rsvp1],
    basePrice: 680,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: 40,
    baseLeadTimeDays: 7,
    region: "Mumbai",
    material: "Cotton Paper",
    color: "Ivory",
    tags: ["rsvp", "stationery"],
    variants: [],
    isFeatured: false,
    isNewArrival: false,
    popularity: 42,
    createdAt: NOW,
  },

  // ── Catering Accessories ──
  {
    id: "p-thali-brass",
    title: "Heritage Brass Thali · set of 6",
    description: "Hand-cast brass thalis with 7 katoris each. Polished to a mirror finish.",
    category: "catering_accessories",
    vendorId: "v-moradabad-brass",
    heroImage: IMG.thali1,
    gallery: [IMG.thali1],
    basePrice: 3200,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: 9,
    baseLeadTimeDays: 5,
    region: "Moradabad",
    material: "Brass",
    color: "Brass",
    tags: ["thali", "brass", "serveware"],
    variants: [
      { id: "6", label: "Set of 6", attribute: "Quantity", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "12", label: "Set of 12", attribute: "Quantity", priceDelta: 2800, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "24", label: "Set of 24", attribute: "Quantity", priceDelta: 5400, leadTimeDeltaDays: 5, stockStatus: "made_to_order", stockCount: null },
    ],
    isFeatured: false,
    isNewArrival: false,
    popularity: 68,
    createdAt: NOW,
  },
  {
    id: "p-tea-set",
    title: "Meenakari Tea Set · service for 8",
    description: "Enameled meenakari tea service with teapot, tray, and eight cups. Hand-painted with peacock motif.",
    category: "catering_accessories",
    vendorId: "v-moradabad-brass",
    heroImage: IMG.teaset,
    gallery: [IMG.teaset],
    basePrice: 4800,
    currency: "USD",
    stockStatus: "low_stock",
    stockCount: 2,
    baseLeadTimeDays: 6,
    region: "Moradabad",
    material: "Brass, Enamel",
    color: "Teal",
    tags: ["tea", "meenakari"],
    variants: colorVariants([
      { id: "teal", label: "Teal" },
      { id: "saffron", label: "Saffron", stock: "made_to_order" },
    ]),
    isFeatured: false,
    isNewArrival: true,
    popularity: 50,
    createdAt: NOW,
  },
  {
    id: "p-glassware-gold",
    title: "Gold-rim Glassware · 24 pc",
    description: "24-piece gold-rim cocktail glassware set. Includes 12 flutes and 12 coupes.",
    category: "catering_accessories",
    vendorId: "v-moradabad-brass",
    heroImage: IMG.glasses,
    gallery: [IMG.glasses],
    basePrice: 1600,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: 30,
    baseLeadTimeDays: 4,
    region: "Moradabad",
    material: "Crystal",
    color: "Gold",
    tags: ["glassware", "bar"],
    variants: [],
    isFeatured: false,
    isNewArrival: false,
    popularity: 45,
    createdAt: NOW,
  },

  // ── Gifting ──
  {
    id: "p-mithai-box-premium",
    title: "Heritage Mithai Box · 1kg",
    description:
      "Curated mithai assortment from four heritage halwais: Agra petha, Delhi kaju katli, Mumbai pedha, Kolkata rosogolla.",
    category: "gifting",
    vendorId: "v-sweetshop-royale",
    heroImage: IMG.mithai,
    gallery: [IMG.mithai],
    basePrice: 280,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: null,
    baseLeadTimeDays: 3,
    region: "Delhi",
    material: "Food",
    color: "Saffron",
    tags: ["mithai", "gifting", "food"],
    variants: [
      { id: "1kg", label: "1 kg", attribute: "Size", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "2kg", label: "2 kg", attribute: "Size", priceDelta: 240, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "5kg", label: "5 kg", attribute: "Size", priceDelta: 720, leadTimeDeltaDays: 1, stockStatus: "in_stock", stockCount: null },
    ],
    isFeatured: true,
    isNewArrival: false,
    popularity: 85,
    createdAt: NOW,
  },
  {
    id: "p-return-gift-box",
    title: "Return Gift Box · Mithai + Silk Pouch",
    description:
      "Guest return gift: branded box with 250g mithai and a silk pouch containing two mishri bon-bons.",
    category: "gifting",
    vendorId: "v-sweetshop-royale",
    heroImage: IMG.return1,
    gallery: [IMG.return1, IMG.return2],
    basePrice: 38,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: null,
    baseLeadTimeDays: 10,
    region: "Delhi",
    material: "Paper, Silk, Food",
    color: "Saffron",
    tags: ["return gift", "guest", "bulk"],
    variants: [
      { id: "50", label: "50 boxes", attribute: "Quantity", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "100", label: "100 boxes", attribute: "Quantity", priceDelta: 1600, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "200", label: "200 boxes", attribute: "Quantity", priceDelta: 3200, leadTimeDeltaDays: 3, stockStatus: "in_stock", stockCount: null },
      { id: "monogram", label: "Monogrammed Pouch", attribute: "Customization", priceDelta: 900, leadTimeDeltaDays: 14, stockStatus: "made_to_order", stockCount: null },
    ],
    isFeatured: true,
    isNewArrival: true,
    popularity: 92,
    createdAt: NOW,
  },
  {
    id: "p-return-gift-brass",
    title: "Return Gift · Mini Brass Diya Pair",
    description: "Pair of miniature brass diyas boxed as a guest return gift. Hand-polished.",
    category: "gifting",
    vendorId: "v-moradabad-brass",
    heroImage: IMG.return2,
    gallery: [IMG.return2, IMG.diya1],
    basePrice: 24,
    currency: "USD",
    stockStatus: "in_stock",
    stockCount: null,
    baseLeadTimeDays: 7,
    region: "Moradabad",
    material: "Brass",
    color: "Brass",
    tags: ["return gift", "diya", "brass"],
    variants: [
      { id: "50", label: "50 pairs", attribute: "Quantity", priceDelta: 0, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "100", label: "100 pairs", attribute: "Quantity", priceDelta: 1100, leadTimeDeltaDays: 0, stockStatus: "in_stock", stockCount: null },
      { id: "200", label: "200 pairs", attribute: "Quantity", priceDelta: 2100, leadTimeDeltaDays: 7, stockStatus: "made_to_order", stockCount: null },
    ],
    isFeatured: false,
    isNewArrival: false,
    popularity: 64,
    createdAt: NOW,
  },
];

// ── Helpers ────────────────────────────────────────────────────────────────

export const STORE_CATEGORY_LABEL: Record<StoreCategory, string> = {
  attire: "Attire",
  jewelry: "Jewelry",
  decor: "Decor",
  stationery: "Stationery",
  catering_accessories: "Catering Accessories",
  gifting: "Gifting",
};

const PRODUCT_BY_ID = new Map(STORE_PRODUCTS.map((p) => [p.id, p]));

export function getStoreProduct(id: string | null): StoreProduct | null {
  if (!id) return null;
  return PRODUCT_BY_ID.get(id) ?? null;
}

export function priceWithVariant(product: StoreProduct, variantId: string | null): number {
  if (!variantId) return product.basePrice;
  const v = product.variants.find((x) => x.id === variantId);
  return product.basePrice + (v?.priceDelta ?? 0);
}

export function leadTimeWithVariant(
  product: StoreProduct,
  variantId: string | null,
): number {
  if (!variantId) return product.baseLeadTimeDays;
  const v = product.variants.find((x) => x.id === variantId);
  return product.baseLeadTimeDays + (v?.leadTimeDeltaDays ?? 0);
}

export function stockWithVariant(
  product: StoreProduct,
  variantId: string | null,
): StockStatus {
  if (!variantId) return product.stockStatus;
  const v = product.variants.find((x) => x.id === variantId);
  return v?.stockStatus ?? product.stockStatus;
}

export const STOCK_LABEL: Record<StockStatus, string> = {
  in_stock: "In Stock",
  low_stock: "Low Stock",
  made_to_order: "Made to Order",
  sold_out: "Sold Out",
};
