// lib/polls/seed-data.ts
//
// The single source of truth for the 300 seeded polls. Used by:
//   - scripts/seed-polls.mjs to populate the `polls` table
//   - any future content-management surface that needs to enumerate the
//     canonical poll bank
//
// To re-seed after editing this file: `node scripts/seed-polls.mjs`.
//
// poll_type guide:
//   - binary       — two-option vote (Yes/No, A or B)
//   - three_way    — three-option vote (marked with † in the source brief)
//   - settle_this  — binary, but flagged as "(Settle this)" so the UI can
//                    style it as a debate moment
//   - would_you    — binary "Would you ever…?" prompt (Yes/No)

import type { PollSeed } from "@/types/polls";

export const POLL_SEEDS: PollSeed[] = [
  // ── Ceremony & Traditions (1–25) ────────────────────────────────────────
  {
    question: "First look before the ceremony — or traditional reveal at the mandap?",
    category: "ceremony_traditions",
    options: ["First look before the ceremony", "Traditional reveal at the mandap"],
    poll_type: "binary",
  },
  {
    question: "Should the groom ride in on a horse or arrive in a luxury car?",
    category: "ceremony_traditions",
    options: ["Ride in on a horse", "Arrive in a luxury car"],
    poll_type: "binary",
  },
  {
    question: "Pheras — 4 or 7? (for couples navigating regional differences)",
    category: "ceremony_traditions",
    options: ["4 pheras", "7 pheras"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to skip the Joota Chupai?",
    category: "ceremony_traditions",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should the vidaai still be part of modern weddings?",
    category: "ceremony_traditions",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Varmala — sweet romantic moment or full competitive chaos?",
    category: "ceremony_traditions",
    options: ["Sweet romantic moment", "Full competitive chaos"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to write your own vows alongside traditional mantras?",
    category: "ceremony_traditions",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should non-Hindu guests be expected to participate in rituals or just observe?",
    category: "ceremony_traditions",
    options: ["Participate in rituals", "Just observe"],
    poll_type: "binary",
  },
  {
    question: "Sindoor — essential tradition or personal choice?",
    category: "ceremony_traditions",
    options: ["Essential tradition", "Personal choice"],
    poll_type: "binary",
  },
  {
    question: "Is a Haldi ceremony worth the stain risk to your skin?",
    category: "ceremony_traditions",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Kanyadaan — beautiful tradition or outdated concept?",
    category: "ceremony_traditions",
    options: ["Beautiful tradition", "Outdated concept"],
    poll_type: "binary",
  },
  {
    question: "Should the pandit explain every ritual in English during the ceremony?",
    category: "ceremony_traditions",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to shorten the ceremony to under an hour?",
    category: "ceremony_traditions",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Mangalsutra — wear it daily after or just for the wedding?",
    category: "ceremony_traditions",
    options: ["Wear it daily after", "Just for the wedding"],
    poll_type: "binary",
  },
  {
    question: "Should the couple face guests during pheras or face the fire?",
    category: "ceremony_traditions",
    options: ["Face guests", "Face the fire"],
    poll_type: "binary",
  },
  {
    question: "Ganesh puja before every event — necessary or just one is fine?",
    category: "ceremony_traditions",
    options: ["Necessary before every event", "Just one is fine"],
    poll_type: "binary",
  },
  {
    question: "Should both families do aarti or just one side?",
    category: "ceremony_traditions",
    options: ["Both families", "Just one side"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to skip the morning-after games (like ring finding)?",
    category: "ceremony_traditions",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Baraat — peak wedding energy or honestly kind of exhausting?",
    category: "ceremony_traditions",
    options: ["Peak wedding energy", "Honestly kind of exhausting"],
    poll_type: "binary",
  },
  {
    question: "Should kids be part of the ceremony procession or kept seated?",
    category: "ceremony_traditions",
    options: ["Part of the procession", "Kept seated"],
    poll_type: "binary",
  },
  {
    question: "Milni ceremony — fun family moment or awkward for mismatched relatives?",
    category: "ceremony_traditions",
    options: ["Fun family moment", "Awkward for mismatched relatives"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to have a friend officiate instead of a pandit?",
    category: "ceremony_traditions",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should the couple do a reception entrance or already be seated?",
    category: "ceremony_traditions",
    options: ["Reception entrance", "Already be seated"],
    poll_type: "binary",
  },
  {
    question: "Saptapadi — walk together or bride follows groom?",
    category: "ceremony_traditions",
    options: ["Walk together", "Bride follows groom"],
    poll_type: "binary",
  },
  {
    question: "Is a roka/engagement ceremony necessary or just an extra event?",
    category: "ceremony_traditions",
    options: ["Necessary", "Just an extra event"],
    poll_type: "binary",
  },

  // ── Guest Experience & Etiquette (26–50) ────────────────────────────────
  {
    question: "Cash gift or registry gift?",
    category: "guest_experience",
    options: ["Cash gift", "Registry gift"],
    poll_type: "binary",
  },
  {
    question: "Should you put a suggested amount on the invitation?",
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Plus-ones for single guests — always, sometimes, or never?",
    category: "guest_experience",
    options: ["Always", "Sometimes", "Never"],
    poll_type: "three_way",
  },
  {
    question: "Kids at the wedding — yes or no?",
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is a dry wedding ever acceptable?",
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should guests wear white to an Indian wedding?",
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Assigned seating or open seating?",
    category: "guest_experience",
    options: ["Assigned seating", "Open seating"],
    poll_type: "binary",
  },
  {
    question: "Is it rude to leave before the vidaai?",
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should guests be expected to attend ALL events or just pick?",
    category: "guest_experience",
    options: ["Attend all events", "Just pick"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to RSVP yes and then not show up? (Settle this.)",
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "settle_this",
  },
  {
    question: "Welcome bags for out-of-town guests — expected or extra?",
    category: "guest_experience",
    options: ["Expected", "Extra"],
    poll_type: "binary",
  },
  {
    question: "Should you feed guests during the baraat or make them wait?",
    category: "guest_experience",
    options: ["Feed during baraat", "Make them wait"],
    poll_type: "binary",
  },
  {
    question: "Late start times — cultural charm or genuinely disrespectful?",
    category: "guest_experience",
    options: ["Cultural charm", "Genuinely disrespectful"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to ask guests not to post on social media?",
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should the couple greet every table or just do a general thank you?",
    category: "guest_experience",
    options: ["Greet every table", "General thank you"],
    poll_type: "binary",
  },
  {
    question: "Valet parking — necessary or a luxury?",
    category: "guest_experience",
    options: ["Necessary", "A luxury"],
    poll_type: "binary",
  },
  {
    question: "Should there be a kids' area/babysitting at the wedding?",
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is a 3-hour cocktail hour too long?",
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Guest count over 500 — epic celebration or logistical nightmare?",
    category: "guest_experience",
    options: ["Epic celebration", "Logistical nightmare", "Depends on the venue"],
    poll_type: "three_way",
  },
  {
    question: "Should elderly guests get priority seating even if they didn't RSVP?",
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Shagun envelopes at the door — convenient or transactional?",
    category: "guest_experience",
    options: ["Convenient", "Transactional"],
    poll_type: "binary",
  },
  {
    question: 'Should there be a dress code beyond "Indian formal"?',
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is it rude to attend the reception but skip the ceremony?",
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Cell phones during the ceremony — ban them or let it go?",
    category: "guest_experience",
    options: ["Ban them", "Let it go"],
    poll_type: "binary",
  },
  {
    question: "Should you send a thank you note for every gift?",
    category: "guest_experience",
    options: ["Yes", "No"],
    poll_type: "binary",
  },

  // ── Food & Drinks (51–75) ───────────────────────────────────────────────
  {
    question: "Buffet or plated service?",
    category: "food_drinks",
    options: ["Buffet", "Plated service"],
    poll_type: "binary",
  },
  {
    question: "Vegetarian-only wedding — respectful or restrictive?",
    category: "food_drinks",
    options: ["Respectful", "Restrictive"],
    poll_type: "binary",
  },
  {
    question: "Is a live chaat station non-negotiable?",
    category: "food_drinks",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Sit-down dinner or food stations?",
    category: "food_drinks",
    options: ["Sit-down dinner", "Food stations", "A mix of both"],
    poll_type: "three_way",
  },
  {
    question: "Should you serve alcohol at a wedding with conservative family?",
    category: "food_drinks",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Late-night snack station — chai & samosa or pizza & fries?",
    category: "food_drinks",
    options: ["Chai & samosa", "Pizza & fries", "Both, please"],
    poll_type: "three_way",
  },
  {
    question: "Is it okay to serve non-veg at a Hindu wedding?",
    category: "food_drinks",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Dessert table or passed desserts?",
    category: "food_drinks",
    options: ["Dessert table", "Passed desserts"],
    poll_type: "binary",
  },
  {
    question: "One caterer for all events or different ones for each?",
    category: "food_drinks",
    options: ["One caterer for all", "Different ones for each"],
    poll_type: "binary",
  },
  {
    question: "Should the couple eat during their own reception?",
    category: "food_drinks",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Paan station — classic must-have or nobody actually eats it?",
    category: "food_drinks",
    options: ["Classic must-have", "Nobody actually eats it"],
    poll_type: "binary",
  },
  {
    question: "Is a signature cocktail necessary?",
    category: "food_drinks",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Gulab jamun or rasgulla? (Settle this forever.)",
    category: "food_drinks",
    options: ["Gulab jamun", "Rasgulla"],
    poll_type: "settle_this",
    is_featured: true,
    // featured_date is set at seed time to now() so reseeds rotate correctly.
  },
  {
    question: "Should the wedding cake be Indian flavors or classic vanilla/chocolate?",
    category: "food_drinks",
    options: ["Indian flavors", "Classic vanilla/chocolate"],
    poll_type: "binary",
  },
  {
    question: "Is a separate Jain menu necessary even for a few guests?",
    category: "food_drinks",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Food trucks at an Indian wedding — fun or out of place?",
    category: "food_drinks",
    options: ["Fun", "Out of place"],
    poll_type: "binary",
  },
  {
    question: "Should you do a cake cutting or a mithai cutting?",
    category: "food_drinks",
    options: ["Cake cutting", "Mithai cutting"],
    poll_type: "binary",
  },
  {
    question: "Is an ice cream station worth it at a winter wedding?",
    category: "food_drinks",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "South Indian filter coffee or masala chai at the farewell brunch?",
    category: "food_drinks",
    options: ["Filter coffee", "Masala chai", "Serve both"],
    poll_type: "three_way",
  },
  {
    question: "Should you put calorie counts or allergen info on the menu?",
    category: "food_drinks",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Live cooking stations — worth the cost?",
    category: "food_drinks",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Biryani: Hyderabadi or Lucknowi?",
    category: "food_drinks",
    options: ["Hyderabadi", "Lucknowi"],
    poll_type: "binary",
  },
  {
    question: "Is a midnight snack run after the wedding a tradition worth keeping?",
    category: "food_drinks",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should the couple do a first bite/cake moment or skip it?",
    category: "food_drinks",
    options: ["First bite moment", "Skip it"],
    poll_type: "binary",
  },
  {
    question: "Kulfi or ice cream?",
    category: "food_drinks",
    options: ["Kulfi", "Ice cream", "Both options"],
    poll_type: "three_way",
  },

  // ── Fashion & Beauty (76–100) ───────────────────────────────────────────
  {
    question: "Red lehenga or non-traditional color?",
    category: "fashion_beauty",
    options: ["Red lehenga", "Non-traditional color"],
    poll_type: "binary",
  },
  {
    question: "Should the groom's outfit coordinate with the bride's or be independent?",
    category: "fashion_beauty",
    options: ["Coordinate with the bride's", "Independent"],
    poll_type: "binary",
  },
  {
    question: "Renting a lehenga — smart move or absolutely not?",
    category: "fashion_beauty",
    options: ["Smart move", "Absolutely not"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to wear your mom's wedding outfit?",
    category: "fashion_beauty",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Designer lehenga or local boutique?",
    category: "fashion_beauty",
    options: ["Designer lehenga", "Local boutique"],
    poll_type: "binary",
  },
  {
    question: "How many outfit changes is too many? (2, 3, or 4+)",
    category: "fashion_beauty",
    options: ["2", "3", "4+"],
    poll_type: "three_way",
  },
  {
    question: "Should bridesmaids match or just coordinate colors?",
    category: "fashion_beauty",
    options: ["Match", "Coordinate colors"],
    poll_type: "binary",
  },
  {
    question: "Sneakers under the lehenga — cute or disrespectful?",
    category: "fashion_beauty",
    options: ["Cute", "Disrespectful"],
    poll_type: "binary",
  },
  {
    question: "Is it okay for a guest to wear red to an Indian wedding?",
    category: "fashion_beauty",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Groom in a sherwani or a suit for the reception?",
    category: "fashion_beauty",
    options: ["Sherwani", "Suit"],
    poll_type: "binary",
  },
  {
    question: "Should the bride do her own makeup or always hire a MUA?",
    category: "fashion_beauty",
    options: ["Do her own makeup", "Always hire a MUA"],
    poll_type: "binary",
  },
  {
    question: "Heavy jewelry or minimal — what photographs better?",
    category: "fashion_beauty",
    options: ["Heavy jewelry", "Minimal"],
    poll_type: "binary",
  },
  {
    question: "Artificial nails for the wedding — worth it or risky?",
    category: "fashion_beauty",
    options: ["Worth it", "Risky"],
    poll_type: "binary",
  },
  {
    question: "Should the groom wear a safa/pagdi or go without?",
    category: "fashion_beauty",
    options: ["Wear a safa/pagdi", "Go without"],
    poll_type: "binary",
  },
  {
    question: "Is a bridal hair trial actually necessary?",
    category: "fashion_beauty",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Matching couple outfits — adorable or too much?",
    category: "fashion_beauty",
    options: ["Adorable", "Too much"],
    poll_type: "binary",
  },
  {
    question: "Should the Haldi outfit be white or yellow?",
    category: "fashion_beauty",
    options: ["White", "Yellow"],
    poll_type: "binary",
  },
  {
    question: "Flats or heels for a 4-hour ceremony?",
    category: "fashion_beauty",
    options: ["Flats", "Heels"],
    poll_type: "binary",
  },
  {
    question: "Is a pre-wedding glow-up (skin treatments, weight loss) healthy or toxic?",
    category: "fashion_beauty",
    options: ["Healthy", "Toxic"],
    poll_type: "binary",
  },
  {
    question: "Should kids in the wedding party be in matching outfits?",
    category: "fashion_beauty",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Open hair or updo for the wedding day?",
    category: "fashion_beauty",
    options: ["Open hair", "Updo"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to re-wear your reception outfit to other events?",
    category: "fashion_beauty",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Nude makeup or full glam for daytime ceremonies?",
    category: "fashion_beauty",
    options: ["Nude makeup", "Full glam", "Soft glam in between"],
    poll_type: "three_way",
  },
  {
    question: "Should the MUA travel with you between events?",
    category: "fashion_beauty",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Nose ring for the wedding — traditional nath or skip it?",
    category: "fashion_beauty",
    options: ["Traditional nath", "Skip it"],
    poll_type: "binary",
  },

  // ── Photography & Video (101–120) ───────────────────────────────────────
  {
    question: "Candid photography or posed portraits?",
    category: "photography_video",
    options: ["Candid photography", "Posed portraits"],
    poll_type: "binary",
  },
  {
    question: "Is a pre-wedding shoot necessary?",
    category: "photography_video",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Drone shots — epic or overdone?",
    category: "photography_video",
    options: ["Epic", "Overdone"],
    poll_type: "binary",
  },
  {
    question: "Same-day wedding film edit — worth the rush?",
    category: "photography_video",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: 'Should you do a "first look" photo session?',
    category: "photography_video",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Photo booth at the sangeet — fun or outdated?",
    category: "photography_video",
    options: ["Fun", "Outdated"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to ban phones during the ceremony for better photos?",
    category: "photography_video",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Wedding album or just digital files?",
    category: "photography_video",
    options: ["Wedding album", "Just digital files"],
    poll_type: "binary",
  },
  {
    question: "How long should the wedding film be? (Under 10 min, 10-20, or full feature)",
    category: "photography_video",
    options: ["Under 10 min", "10-20 min", "Full feature"],
    poll_type: "three_way",
  },
  {
    question: "Should the photographer capture the couple eating?",
    category: "photography_video",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Morning-after shoot — cute idea or exhausting?",
    category: "photography_video",
    options: ["Cute idea", "Exhausting"],
    poll_type: "binary",
  },
  {
    question: "Should family formals be done before or after the ceremony?",
    category: "photography_video",
    options: ["Before the ceremony", "After the ceremony"],
    poll_type: "binary",
  },
  {
    question: "Is it tacky to have a hashtag?",
    category: "photography_video",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should you tip your photographer?",
    category: "photography_video",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Polaroid guestbook or traditional guestbook?",
    category: "photography_video",
    options: ["Polaroid guestbook", "Traditional guestbook"],
    poll_type: "binary",
  },
  {
    question: "Dark & moody editing or bright & airy?",
    category: "photography_video",
    options: ["Dark & moody", "Bright & airy"],
    poll_type: "binary",
  },
  {
    question: "Is a boudoir shoot before the wedding empowering or unnecessary?",
    category: "photography_video",
    options: ["Empowering", "Unnecessary"],
    poll_type: "binary",
  },
  {
    question: "Should videographers mic the pandit?",
    category: "photography_video",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "How many photographers do you actually need? (1, 2, or 3+)",
    category: "photography_video",
    options: ["1", "2", "3+"],
    poll_type: "three_way",
  },
  {
    question: "Engagement shoot in Indian wear or western?",
    category: "photography_video",
    options: ["Indian wear", "Western"],
    poll_type: "binary",
  },

  // ── Music, Dance & Entertainment (121–135) ──────────────────────────────
  {
    question: "Live band or DJ?",
    category: "music_entertainment",
    options: ["Live band", "DJ"],
    poll_type: "binary",
  },
  {
    question: "Dhol player for the baraat — absolutely essential or optional?",
    category: "music_entertainment",
    options: ["Absolutely essential", "Optional"],
    poll_type: "binary",
  },
  {
    question: "Choreographed sangeet or freestyle?",
    category: "music_entertainment",
    options: ["Choreographed sangeet", "Freestyle"],
    poll_type: "binary",
  },
  {
    question: "Should the couple do a first dance?",
    category: "music_entertainment",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Bollywood songs or Punjabi bangers for the baraat?",
    category: "music_entertainment",
    options: ["Bollywood songs", "Punjabi bangers", "A mix of both"],
    poll_type: "three_way",
  },
  {
    question: "Is a sangeet performance from every family group necessary?",
    category: "music_entertainment",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should you hire a sangeet choreographer?",
    category: "music_entertainment",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Kids' performances at sangeet — adorable or filler?",
    category: "music_entertainment",
    options: ["Adorable", "Filler"],
    poll_type: "binary",
  },
  {
    question: "Is a live singer worth the budget?",
    category: "music_entertainment",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should there be a dance floor at the reception or just the sangeet?",
    category: "music_entertainment",
    options: ["At the reception too", "Just the sangeet"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to play English/Western music at the reception?",
    category: "music_entertainment",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Sparkler exit or flower petal exit?",
    category: "music_entertainment",
    options: ["Sparkler exit", "Flower petal exit", "Combine both"],
    poll_type: "three_way",
  },
  {
    question: "Fire performers at the sangeet — amazing or safety hazard?",
    category: "music_entertainment",
    options: ["Amazing", "Safety hazard"],
    poll_type: "binary",
  },
  {
    question: "Should the couple's first dance be Bollywood or something unexpected?",
    category: "music_entertainment",
    options: ["Bollywood", "Something unexpected"],
    poll_type: "binary",
  },
  {
    question: "Is a mehendi DJ necessary or can you just use a speaker?",
    category: "music_entertainment",
    options: ["DJ is necessary", "A speaker is enough"],
    poll_type: "binary",
  },

  // ── Décor & Venue (136–160) ─────────────────────────────────────────────
  {
    question: "Hotel ballroom or outdoor venue?",
    category: "decor_venue",
    options: ["Hotel ballroom", "Outdoor venue"],
    poll_type: "binary",
  },
  {
    question: "Real flowers or artificial for the mandap?",
    category: "decor_venue",
    options: ["Real flowers", "Artificial"],
    poll_type: "binary",
  },
  {
    question: "Is a destination wedding selfish?",
    category: "decor_venue",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should the mandap match the reception décor or be its own statement?",
    category: "decor_venue",
    options: ["Match the reception décor", "Its own statement"],
    poll_type: "binary",
  },
  {
    question: "Fairy lights or candles?",
    category: "decor_venue",
    options: ["Fairy lights", "Candles"],
    poll_type: "binary",
  },
  {
    question: "Is a photo wall/backdrop necessary?",
    category: "decor_venue",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should the venue allow outside catering or is in-house fine?",
    category: "decor_venue",
    options: ["Allow outside catering", "In-house is fine"],
    poll_type: "binary",
  },
  {
    question: "Ceiling draping — dreamy or overdone?",
    category: "decor_venue",
    options: ["Dreamy", "Overdone"],
    poll_type: "binary",
  },
  {
    question: "Is a separate room for the ceremony and reception better or worse?",
    category: "decor_venue",
    options: ["Better", "Worse"],
    poll_type: "binary",
  },
  {
    question: "Marigold strings or roses for the mandap?",
    category: "decor_venue",
    options: ["Marigold strings", "Roses"],
    poll_type: "binary",
  },
  {
    question: "Should you visit the venue more than twice before booking?",
    category: "decor_venue",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Indoor mandap or outdoor mandap?",
    category: "decor_venue",
    options: ["Indoor mandap", "Outdoor mandap"],
    poll_type: "binary",
  },
  {
    question: "Is it worth flying in a decorator from another city?",
    category: "decor_venue",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Lounges and seating areas at cocktail hour — necessary or extra?",
    category: "decor_venue",
    options: ["Necessary", "Extra"],
    poll_type: "binary",
  },
  {
    question: "Should the baraat route be decorated?",
    category: "decor_venue",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Floating flowers in the pool — stunning or cliché?",
    category: "decor_venue",
    options: ["Stunning", "Cliché"],
    poll_type: "binary",
  },
  {
    question: "Giant LED name sign — cute or tacky?",
    category: "decor_venue",
    options: ["Cute", "Tacky"],
    poll_type: "binary",
  },
  {
    question: "Should the couple have a sweetheart table or sit with family?",
    category: "decor_venue",
    options: ["Sweetheart table", "Sit with family"],
    poll_type: "binary",
  },
  {
    question: "Stage for the reception — traditional or skip it?",
    category: "decor_venue",
    options: ["Traditional", "Skip it"],
    poll_type: "binary",
  },
  {
    question: "Is a separate mehndi setup worth the cost or keep it simple?",
    category: "decor_venue",
    options: ["Worth the cost", "Keep it simple"],
    poll_type: "binary",
  },
  {
    question: "Rangoli at the entrance — must-have or nobody notices?",
    category: "decor_venue",
    options: ["Must-have", "Nobody notices"],
    poll_type: "binary",
  },
  {
    question: "Printed signage or handwritten chalkboards?",
    category: "decor_venue",
    options: ["Printed signage", "Handwritten chalkboards"],
    poll_type: "binary",
  },
  {
    question: "Should the wedding have a theme or just a color palette?",
    category: "decor_venue",
    options: ["A theme", "Just a color palette"],
    poll_type: "binary",
  },
  {
    question: "Is a luxury tent (shamiyana) worth it for outdoor weddings?",
    category: "decor_venue",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Drone light show — futuristic or too much?",
    category: "decor_venue",
    options: ["Futuristic", "Too much"],
    poll_type: "binary",
  },

  // ── Budget & Planning (161–180) ─────────────────────────────────────────
  {
    question: "Is a wedding planner worth the money?",
    category: "budget_planning",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should you set a budget before or after making the guest list?",
    category: "budget_planning",
    options: ["Before the guest list", "After the guest list"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to ask parents to contribute a specific amount?",
    category: "budget_planning",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "DIY elements — charming or obvious cost-cutting?",
    category: "budget_planning",
    options: ["Charming", "Obvious cost-cutting"],
    poll_type: "binary",
  },
  {
    question: "Should you negotiate with every vendor?",
    category: "budget_planning",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is wedding insurance necessary?",
    category: "budget_planning",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should you have a contingency fund and how much? (10%, 15%, 20%+)",
    category: "budget_planning",
    options: ["10%", "15%", "20%+"],
    poll_type: "three_way",
  },
  {
    question: "Weekday wedding for the savings — worth it?",
    category: "budget_planning",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to cut corners on things guests won't notice?",
    category: "budget_planning",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should vendor tips be part of the budget from day one?",
    category: "budget_planning",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Payment plans with vendors — smart or risky?",
    category: "budget_planning",
    options: ["Smart", "Risky"],
    poll_type: "binary",
  },
  {
    question: "Is it worth paying more for a peak-season date?",
    category: "budget_planning",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should the couple pay for everything themselves or accept family help?",
    category: "budget_planning",
    options: ["Pay themselves", "Accept family help"],
    poll_type: "binary",
  },
  {
    question: "Off-season wedding — brilliant savings or sad vibes?",
    category: "budget_planning",
    options: ["Brilliant savings", "Sad vibes"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to have different budgets for different events?",
    category: "budget_planning",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should you track every expense or just set category limits?",
    category: "budget_planning",
    options: ["Track every expense", "Just set category limits"],
    poll_type: "binary",
  },
  {
    question: "Hiring family friends as vendors — good idea or recipe for drama?",
    category: "budget_planning",
    options: ["Good idea", "Recipe for drama"],
    poll_type: "binary",
  },
  {
    question: "Is a spreadsheet enough or do you need planning software?",
    category: "budget_planning",
    options: ["A spreadsheet is enough", "Need planning software"],
    poll_type: "binary",
  },
  {
    question: "Should you book vendors based on portfolio or price first?",
    category: "budget_planning",
    options: ["Portfolio", "Price"],
    poll_type: "binary",
  },
  {
    question: "Deposits — 25% or 50%?",
    category: "budget_planning",
    options: ["25%", "50%"],
    poll_type: "binary",
  },

  // ── Family Dynamics (181–200) ───────────────────────────────────────────
  {
    question: "Should the couple have final say or is it the parents' wedding too?",
    category: "family_dynamics",
    options: ["Couple has final say", "It's the parents' wedding too"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to exclude a family member from the wedding?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Mother-in-law involvement — welcome it or set boundaries early?",
    category: "family_dynamics",
    options: ["Welcome it", "Set boundaries early"],
    poll_type: "binary",
  },
  {
    question: "Should divorced parents sit together?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Joint family events or separate sides for sangeet?",
    category: "family_dynamics",
    options: ["Joint family events", "Separate sides for sangeet"],
    poll_type: "binary",
  },
  {
    question: "Is the bride's family paying for everything still a thing?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should siblings get a say in wedding decisions?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is it okay for the groom's side to request specific rituals?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Family WhatsApp group for planning — helpful or a nightmare?",
    category: "family_dynamics",
    options: ["Helpful", "A nightmare"],
    poll_type: "binary",
  },
  {
    question: "Should cousins be in the wedding party even if you're not close?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is a joint bachelor/bachelorette trip better than separate?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should parents meet before the engagement or is the roka the first meeting?",
    category: "family_dynamics",
    options: ["Meet before the engagement", "Roka is the first meeting"],
    poll_type: "binary",
  },
  {
    question: "Mother-of-the-bride speech — yes or no?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to elope and do a reception later?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should the wedding party be equal on both sides?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Handling unsolicited aunty opinions — engage or ignore?",
    category: "family_dynamics",
    options: ["Engage", "Ignore"],
    poll_type: "binary",
  },
  {
    question: "Should the couple live together before the wedding?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is a joint bank account for wedding expenses a good idea?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should the couple write thank you speeches for parents?",
    category: "family_dynamics",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Extended family drama — address it before the wedding or just get through it?",
    category: "family_dynamics",
    options: ["Address it before the wedding", "Just get through it"],
    poll_type: "binary",
  },

  // ── Honeymoon & Post-Wedding (201–210) ──────────────────────────────────
  {
    question: "Honeymoon right after the wedding or wait a few weeks?",
    category: "honeymoon_post_wedding",
    options: ["Right after the wedding", "Wait a few weeks"],
    poll_type: "binary",
  },
  {
    question: "Adventure honeymoon or relaxation honeymoon?",
    category: "honeymoon_post_wedding",
    options: ["Adventure honeymoon", "Relaxation honeymoon", "A mix of both"],
    poll_type: "three_way",
  },
  {
    question: "Should you post honeymoon photos or keep it private?",
    category: "honeymoon_post_wedding",
    options: ["Post photos", "Keep it private"],
    poll_type: "binary",
  },
  {
    question: "Is a mini-moon (short trip) enough?",
    category: "honeymoon_post_wedding",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Domestic honeymoon or international?",
    category: "honeymoon_post_wedding",
    options: ["Domestic honeymoon", "International"],
    poll_type: "binary",
  },
  {
    question: "Should you open gifts at the wedding or at home?",
    category: "honeymoon_post_wedding",
    options: ["At the wedding", "At home"],
    poll_type: "binary",
  },
  {
    question: "Post-wedding brunch — sweet send-off or one too many events?",
    category: "honeymoon_post_wedding",
    options: ["Sweet send-off", "One too many events"],
    poll_type: "binary",
  },
  {
    question: "Should the bride change her last name?",
    category: "honeymoon_post_wedding",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Thank you cards — handwritten or digital?",
    category: "honeymoon_post_wedding",
    options: ["Handwritten", "Digital"],
    poll_type: "binary",
  },
  {
    question: "How long after the wedding should you send thank you notes?",
    category: "honeymoon_post_wedding",
    options: ["Within 1 month", "Within 3 months"],
    poll_type: "binary",
  },

  // ── Invitations & Communication (211–220) ───────────────────────────────
  {
    question: "Physical invitations or digital?",
    category: "invitations_communication",
    options: ["Physical invitations", "Digital", "Both, depending on the guest"],
    poll_type: "three_way",
  },
  {
    question: "Video invitation — creative or try-hard?",
    category: "invitations_communication",
    options: ["Creative", "Try-hard"],
    poll_type: "binary",
  },
  {
    question: "Should the invitation have a dress code?",
    category: "invitations_communication",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is a wedding website necessary or does WhatsApp handle everything?",
    category: "invitations_communication",
    options: ["Wedding website is necessary", "WhatsApp handles everything"],
    poll_type: "binary",
  },
  {
    question: "Should you call elders personally or is an invite enough?",
    category: "invitations_communication",
    options: ["Call personally", "Invite is enough"],
    poll_type: "binary",
  },
  {
    question: "Save-the-dates — useful or just another thing to design?",
    category: "invitations_communication",
    options: ["Useful", "Just another thing to design"],
    poll_type: "binary",
  },
  {
    question: "Should invitations be in English, Hindi, or both?",
    category: "invitations_communication",
    options: ["English", "Hindi", "Both"],
    poll_type: "three_way",
  },
  {
    question: "Is an RSVP deadline realistic for Indian weddings?",
    category: "invitations_communication",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "WhatsApp broadcast for updates — practical or impersonal?",
    category: "invitations_communication",
    options: ["Practical", "Impersonal"],
    poll_type: "binary",
  },
  {
    question: "Should the invitation include the full event schedule?",
    category: "invitations_communication",
    options: ["Yes", "No"],
    poll_type: "binary",
  },

  // ── Modern vs. Traditional (221–235) ────────────────────────────────────
  {
    question: "Love marriage or arranged — does it change how you plan?",
    category: "modern_vs_traditional",
    options: ["Yes, it changes everything", "No, planning is the same"],
    poll_type: "binary",
  },
  {
    question: "Is a court marriage before the ceremony practical or unromantic?",
    category: "modern_vs_traditional",
    options: ["Practical", "Unromantic"],
    poll_type: "binary",
  },
  {
    question: "Should the bride's side do the reception or the groom's?",
    category: "modern_vs_traditional",
    options: ["Bride's side", "Groom's side"],
    poll_type: "binary",
  },
  {
    question: "Is matching jewelry to the outfit essential or overrated?",
    category: "modern_vs_traditional",
    options: ["Essential", "Overrated"],
    poll_type: "binary",
  },
  {
    question: "Joint bachelor/bachelorette or keep it traditional?",
    category: "modern_vs_traditional",
    options: ["Joint", "Keep it traditional"],
    poll_type: "binary",
  },
  {
    question: "Western-style bridesmaids and groomsmen — fun addition or forced?",
    category: "modern_vs_traditional",
    options: ["Fun addition", "Forced"],
    poll_type: "binary",
  },
  {
    question: "Should the bride walk down an aisle or enter traditionally?",
    category: "modern_vs_traditional",
    options: ["Walk down an aisle", "Enter traditionally"],
    poll_type: "binary",
  },
  {
    question: "Is a sangeet necessary or can you combine it with cocktails?",
    category: "modern_vs_traditional",
    options: ["Sangeet is necessary", "Combine with cocktails"],
    poll_type: "binary",
  },
  {
    question: "Unity ceremony (candle, sand, etc.) — meaningful or performative?",
    category: "modern_vs_traditional",
    options: ["Meaningful", "Performative"],
    poll_type: "binary",
  },
  {
    question: "Should the couple have a sweetheart table or sit with family? (modern take)",
    category: "modern_vs_traditional",
    options: ["Sweetheart table", "Sit with family"],
    poll_type: "binary",
  },
  {
    question: "Father-daughter dance — sweet Western import or not for us?",
    category: "modern_vs_traditional",
    options: ["Sweet Western import", "Not for us"],
    poll_type: "binary",
  },
  {
    question: "Bouquet toss at an Indian wedding — yes or no?",
    category: "modern_vs_traditional",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is a rehearsal dinner necessary for Indian weddings?",
    category: "modern_vs_traditional",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Wedding party proposals (bridesmaid boxes, etc.) — cute or excessive?",
    category: "modern_vs_traditional",
    options: ["Cute", "Excessive"],
    poll_type: "binary",
  },
  {
    question: "Should the couple do speeches or let family handle it?",
    category: "modern_vs_traditional",
    options: ["Couple does speeches", "Let family handle it"],
    poll_type: "binary",
  },

  // ── Spicy Hot Takes (236–250) ───────────────────────────────────────────
  {
    question: "Is a ₹1 lakh lehenga a waste of money?",
    category: "spicy_hot_takes",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should guests who don't give shagun be judged?",
    category: "spicy_hot_takes",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is a 4-hour ceremony too long in 2026?",
    category: "spicy_hot_takes",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Are most wedding planners overpriced?",
    category: "spicy_hot_takes",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is the Indian wedding industry exploitative?",
    category: "spicy_hot_takes",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should vendors charge more for wedding events vs. regular events?",
    category: "spicy_hot_takes",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is a small wedding actually more stressful than a big one?",
    category: "spicy_hot_takes",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Are matching couple Instagram posts cringe?",
    category: "spicy_hot_takes",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is it okay to go into debt for a wedding?",
    category: "spicy_hot_takes",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should the groom cry at the wedding or keep it together?",
    category: "spicy_hot_takes",
    options: ["Cry it out", "Keep it together"],
    poll_type: "binary",
  },
  {
    question: "Are most sangeet performances actually good?",
    category: "spicy_hot_takes",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: 'Is "keeping it simple" code for "we ran out of budget"?',
    category: "spicy_hot_takes",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Should you tell guests what you spent?",
    category: "spicy_hot_takes",
    options: ["Yes", "No"],
    poll_type: "binary",
  },
  {
    question: "Is an after-party necessary or is 8 hours of wedding not enough?",
    category: "spicy_hot_takes",
    options: ["After-party is necessary", "8 hours is enough"],
    poll_type: "binary",
  },
  {
    question: "Are elaborate proposals (public, flash mob) romantic or performative?",
    category: "spicy_hot_takes",
    options: ["Romantic", "Performative"],
    poll_type: "binary",
  },

  // ── Would You Ever (251–270) ────────────────────────────────────────────
  {
    question: "Would you wear a black lehenga to your wedding?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you let your in-laws pick your wedding outfit?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you do a surprise choreography you didn't tell your partner about?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you get married on a weekday to save 40%?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you skip the baraat entirely?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you have a pet at your wedding?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you let guests vote on your reception entry song?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you do a joint sangeet performance with your partner?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you uninvite someone a week before the wedding?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you redo your wedding if you could?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you have a live painter instead of a photographer?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you do a no-phone ceremony?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you wear white to your own Indian wedding?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you have a cash bar?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you skip the reception and just do the ceremony + dinner?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you let AI plan your wedding?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you do a sunrise wedding?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you skip the cake/mithai cutting?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you marry at your parents' home?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },
  {
    question: "Would you have a themed wedding (like a specific Bollywood movie)?",
    category: "would_you_ever",
    options: ["Yes", "No"],
    poll_type: "would_you",
  },

  // ── This or That (271–300) ──────────────────────────────────────────────
  {
    question: "Roses or marigolds?",
    category: "this_or_that",
    options: ["Roses", "Marigolds"],
    poll_type: "binary",
  },
  {
    question: "Gold or silver jewelry?",
    category: "this_or_that",
    options: ["Gold", "Silver"],
    poll_type: "binary",
  },
  {
    question: "Upbeat baraat or elegant baraat?",
    category: "this_or_that",
    options: ["Upbeat baraat", "Elegant baraat"],
    poll_type: "binary",
  },
  {
    question: "Ceremony first or cocktails first?",
    category: "this_or_that",
    options: ["Ceremony first", "Cocktails first"],
    poll_type: "binary",
  },
  {
    question: "Getting ready photos or skip them?",
    category: "this_or_that",
    options: ["Getting ready photos", "Skip them"],
    poll_type: "binary",
  },
  {
    question: "Henna on both hands or one?",
    category: "this_or_that",
    options: ["Both hands", "One hand"],
    poll_type: "binary",
  },
  {
    question: "Sparklers or confetti?",
    category: "this_or_that",
    options: ["Sparklers", "Confetti"],
    poll_type: "binary",
  },
  {
    question: "Luxury tent or open air?",
    category: "this_or_that",
    options: ["Luxury tent", "Open air"],
    poll_type: "binary",
  },
  {
    question: "Band baaja or just the DJ?",
    category: "this_or_that",
    options: ["Band baaja", "Just the DJ"],
    poll_type: "binary",
  },
  {
    question: "Chai bar or cocktail bar?",
    category: "this_or_that",
    options: ["Chai bar", "Cocktail bar"],
    poll_type: "binary",
  },
  {
    question: "Traditional thaali or modern plating?",
    category: "this_or_that",
    options: ["Traditional thaali", "Modern plating"],
    poll_type: "binary",
  },
  {
    question: "Morning wedding or evening wedding?",
    category: "this_or_that",
    options: ["Morning wedding", "Evening wedding"],
    poll_type: "binary",
  },
  {
    question: "Hotel block or Airbnbs for guests?",
    category: "this_or_that",
    options: ["Hotel block", "Airbnbs"],
    poll_type: "binary",
  },
  {
    question: "Printed menu or digital menu?",
    category: "this_or_that",
    options: ["Printed menu", "Digital menu"],
    poll_type: "binary",
  },
  {
    question: "Silk saree or chiffon saree?",
    category: "this_or_that",
    options: ["Silk saree", "Chiffon saree"],
    poll_type: "binary",
  },
  {
    question: "Gold mandap or white mandap?",
    category: "this_or_that",
    options: ["Gold mandap", "White mandap"],
    poll_type: "binary",
  },
  {
    question: "Garland swap or ring exchange for engagement?",
    category: "this_or_that",
    options: ["Garland swap", "Ring exchange"],
    poll_type: "binary",
  },
  {
    question: "Live dhol or recorded?",
    category: "this_or_that",
    options: ["Live dhol", "Recorded"],
    poll_type: "binary",
  },
  {
    question: "Same makeup artist for all events or different for each?",
    category: "this_or_that",
    options: ["Same MUA for all events", "Different for each"],
    poll_type: "binary",
  },
  {
    question: "Flower shower or rose petal cannon?",
    category: "this_or_that",
    options: ["Flower shower", "Rose petal cannon"],
    poll_type: "binary",
  },
  {
    question: "Vintage car or decorated SUV?",
    category: "this_or_that",
    options: ["Vintage car", "Decorated SUV"],
    poll_type: "binary",
  },
  {
    question: "Handwritten vows or memorized?",
    category: "this_or_that",
    options: ["Handwritten vows", "Memorized"],
    poll_type: "binary",
  },
  {
    question: "Groom on horse or elephant?",
    category: "this_or_that",
    options: ["Horse", "Elephant"],
    poll_type: "binary",
  },
  {
    question: "Lavender or marigold yellow?",
    category: "this_or_that",
    options: ["Lavender", "Marigold yellow"],
    poll_type: "binary",
  },
  {
    question: "Long veil or no veil?",
    category: "this_or_that",
    options: ["Long veil", "No veil"],
    poll_type: "binary",
  },
  {
    question: "Jaimala on stage or ground level?",
    category: "this_or_that",
    options: ["On stage", "Ground level"],
    poll_type: "binary",
  },
  {
    question: "Pastel mandap or jewel tone mandap?",
    category: "this_or_that",
    options: ["Pastel mandap", "Jewel tone mandap"],
    poll_type: "binary",
  },
  {
    question: "In-laws matching — cute or forced?",
    category: "this_or_that",
    options: ["Cute", "Forced"],
    poll_type: "binary",
  },
  {
    question: "Exit with sparklers or exit with dhol?",
    category: "this_or_that",
    options: ["Sparklers", "Dhol"],
    poll_type: "binary",
  },
  {
    question: "Plan for 2 years or wing it in 6 months?",
    category: "this_or_that",
    options: ["Plan for 2 years", "Wing it in 6 months"],
    poll_type: "binary",
  },
];

if (POLL_SEEDS.length !== 300) {
  throw new Error(
    `POLL_SEEDS expected 300 entries, got ${POLL_SEEDS.length}. Re-check the seed file.`,
  );
}
