// ── Service & Flow helpers ─────────────────────────────────────────────────
// Industry-ratio warnings and Run-of-Show markdown. Pure functions so
// the component layer stays thin.

import type {
  MenuEvent,
  MenuMoment,
  Dish,
  RentalItem,
  ServiceStyle,
  SignatureCocktail,
  StaffSlot,
} from "@/types/catering";

export interface StaffingWarning {
  severity: "info" | "warn" | "risk";
  role: string;
  message: string;
}

// Industry ratios the Bloomberg-Terminal copy actually cares about.
// These are planner rules of thumb, not hard laws — they're warnings
// when the couple is below, not errors.
const SERVER_RATIO: Record<ServiceStyle, number> = {
  plated: 15,
  buffet: 25,
  stations: 30,
  family_style: 18,
  passed: 50,
  thali: 15,
};
const BARTENDER_RATIO = 75; // 1 bartender per 75 guests, minimum.

export function staffingWarnings(
  event: MenuEvent,
  slots: StaffSlot[],
): StaffingWarning[] {
  const warnings: StaffingWarning[] = [];
  const guests = event.guest_count;

  const serverCount = slots
    .filter((s) => s.role === "server")
    .reduce((n, s) => n + s.count, 0);
  const ratioTarget = SERVER_RATIO[event.service_style];
  const serversNeeded = Math.ceil(guests / ratioTarget);
  if (serverCount < serversNeeded) {
    warnings.push({
      severity: "risk",
      role: "server",
      message: `Only ${serverCount} servers for ${guests} guests at ${event.service_style} service. Industry rule: 1 per ${ratioTarget} (need ${serversNeeded}).`,
    });
  } else if (serverCount < Math.ceil(guests / (ratioTarget - 3))) {
    warnings.push({
      severity: "info",
      role: "server",
      message: `${serverCount} servers for ${guests} guests — meets the 1:${ratioTarget} bar, no comfort margin.`,
    });
  }

  const bartenderCount = slots
    .filter((s) => s.role === "bartender")
    .reduce((n, s) => n + s.count, 0);
  const bartendersNeeded = Math.ceil(guests / BARTENDER_RATIO);
  if (bartenderCount > 0 && bartenderCount < bartendersNeeded) {
    warnings.push({
      severity: "warn",
      role: "bartender",
      message: `${bartenderCount} bartenders for ${guests} guests — industry standard is 1:${BARTENDER_RATIO} (need ${bartendersNeeded}). Expect bar queues.`,
    });
  }

  const captainCount = slots
    .filter((s) => s.role === "captain")
    .reduce((n, s) => n + s.count, 0);
  if (guests >= 200 && captainCount < 3) {
    warnings.push({
      severity: "warn",
      role: "captain",
      message: `Only ${captainCount} captains for ${guests} guests. For weddings over 200, plan 1 captain per 100 guests.`,
    });
  }

  return warnings;
}

// Outdoor events need backup chafers per a planner rule of thumb.
export function rentalWarnings(event: MenuEvent, rentals: RentalItem[]): string[] {
  const warnings: string[] = [];
  const isOutdoor = /outdoor|garden|tent|backyard|lawn/i.test(
    `${event.venue ?? ""} ${event.vibe_tags.join(" ")}`,
  );
  if (isOutdoor) {
    const hasBackupChafer = rentals.some(
      (r) =>
        r.category === "service" && /backup|spare/i.test(r.notes ?? "") && /chafer/i.test(r.name),
    );
    const hasChafer = rentals.some(
      (r) => r.category === "service" && /chafer/i.test(r.name),
    );
    if (hasChafer && !hasBackupChafer) {
      warnings.push(
        "Outdoor event — plan 2 backup chafers. Wind kills service heat faster than planners expect.",
      );
    }
  }
  return warnings;
}

// ── Run-of-Show markdown export ──────────────────────────────────────────
// One-click export: minute-by-minute food and beverage run sheet per
// event. The kitchen and captain team each get a copy.

export function buildRunOfShow(
  events: MenuEvent[],
  moments: MenuMoment[],
  dishes: Dish[],
  staff: StaffSlot[],
  rentals: RentalItem[],
  cocktails: SignatureCocktail[],
): string {
  const lines: string[] = [];
  lines.push("# Run of Show — Catering");
  lines.push("");
  lines.push(
    "Generated by Ananya. Share with your caterer's captain and kitchen lead 72h before each event.",
  );

  for (const ev of events) {
    const evMoments = moments
      .filter((m) => m.event_id === ev.id)
      .sort((a, b) => a.order - b.order);
    const evRentals = rentals.filter((r) => r.event_id === ev.id);
    const evStaff = staff.filter((s) => s.event_id === ev.id);
    const evCocktails = cocktails.filter((c) => c.event_id === ev.id);

    lines.push("");
    lines.push(`## ${ev.label} — ${ev.date}`);
    lines.push(
      `${ev.guest_count} guests · ${ev.service_style.replace("_", " ")} service${ev.venue ? ` · ${ev.venue}` : ""}`,
    );

    lines.push("");
    lines.push("### Service timeline");
    if (evMoments.length === 0) {
      lines.push("_(no moments planned)_");
    } else {
      for (const m of evMoments) {
        lines.push(
          `- **${m.time_window ?? "time TBD"}** · ${m.name}`,
        );
        const ds = dishes
          .filter((d) => d.moment_id === m.id)
          .sort((a, b) => a.sort_order - b.sort_order);
        for (const d of ds) lines.push(`    - ${d.name} — ${d.description}`);
      }
    }

    if (evStaff.length > 0) {
      lines.push("");
      lines.push("### Staff on site");
      const roles = new Map<string, number>();
      for (const s of evStaff)
        roles.set(s.role, (roles.get(s.role) ?? 0) + s.count);
      roles.forEach((count, role) => {
        lines.push(`- ${role}: ${count}`);
      });
    }

    if (evRentals.length > 0) {
      lines.push("");
      lines.push("### Rentals needed");
      for (const r of evRentals) {
        lines.push(
          `- ${r.name} — ${r.quantity}${r.unit ? ` ${r.unit}` : ""}${r.covered_by ? ` (${r.covered_by})` : ""}${r.notes ? ` · ${r.notes}` : ""}`,
        );
      }
    }

    if (evCocktails.length > 0) {
      lines.push("");
      lines.push("### Bar program — signature cocktails");
      for (const c of evCocktails) {
        lines.push(`- **${c.name}**`);
        for (const i of c.ingredients) lines.push(`    - ${i}`);
        if (c.garnish) lines.push(`    - Garnish: ${c.garnish}`);
      }
    }
  }

  return lines.join("\n");
}
