import type {
  ApplicationAdminLog,
  CreatorApplication,
} from "@/types/creator-application";

const iso = (d: string) => new Date(d).toISOString();
const daysAgo = (n: number) =>
  new Date(Date.now() - n * 86_400_000).toISOString();
const daysFromNow = (n: number) =>
  new Date(Date.now() + n * 86_400_000).toISOString();

// ── Seed applications ─────────────────────────────────────────────────────
// Three approved (tied to existing creators), one fresh pending for the
// admin demo, one rejected w/ cooldown remaining.

export const SEED_APPLICATIONS: CreatorApplication[] = [
  {
    id: "app-priya-patel",
    userId: null,
    fullName: "Priya Patel",
    email: "priya@priyapatel.co",
    locationCity: "Mumbai",
    locationCountry: "India",
    avatarUrl: null,
    bio: "South Asian bridal stylist & fashion editor. Featured in Vogue India, Elle, and Bride Magazine.",
    primaryExpertise: "bridal_styling",
    secondaryExpertise: ["cultural_traditions"],
    yearsExperience: "10_plus",
    isIndustryProfessional: true,
    professionalRole: "Senior fashion editor, freelance bridal stylist",
    instagramHandle: "@priyapatel",
    youtubeChannel: null,
    tiktokHandle: null,
    blogUrl: "https://priyapatel.co",
    otherSocialLinks: null,
    combinedFollowingRange: "100k_500k",
    portfolioUrls: [],
    contentPlan:
      "Monthly lehenga edits, heirloom jewelry stories, and couture-forward bridal guides.",
    agreedToTerms: true,
    status: "approved",
    rejectionReasonCategory: null,
    rejectionReasonText: null,
    waitlistNote: null,
    moreInfoRequest: null,
    moreInfoResponse: null,
    adminInternalNotes: "Clear anchor profile. Start at Top Creator-equivalent visibility.",
    reviewedBy: "admin-ananya",
    reviewedAt: iso("2024-06-12T10:00:00Z"),
    reapplyEligibleAt: null,
    linkedCreatorId: "cr-priya-patel",
    createdAt: iso("2024-06-05T10:00:00Z"),
    updatedAt: iso("2024-06-12T10:00:00Z"),
  },
  {
    id: "app-meera-shah",
    userId: null,
    fullName: "Meera Shah",
    email: "hello@meerashah.in",
    locationCity: "Delhi",
    locationCountry: "India",
    avatarUrl: null,
    bio: "Luxury wedding planner & décor curator. Building weddings that feel like heirlooms.",
    primaryExpertise: "wedding_planning",
    secondaryExpertise: ["decor_design"],
    yearsExperience: "5_to_10",
    isIndustryProfessional: true,
    professionalRole: "Founder, Shah Atelier Weddings",
    instagramHandle: "@meera.shah",
    youtubeChannel: null,
    tiktokHandle: null,
    blogUrl: null,
    otherSocialLinks: null,
    combinedFollowingRange: "50k_100k",
    portfolioUrls: [],
    contentPlan:
      "Mandap design case studies, vendor-sourcing guides, and a weekly planner field journal.",
    agreedToTerms: true,
    status: "approved",
    rejectionReasonCategory: null,
    rejectionReasonText: null,
    waitlistNote: null,
    moreInfoRequest: null,
    moreInfoResponse: null,
    adminInternalNotes: null,
    reviewedBy: "admin-ananya",
    reviewedAt: iso("2024-11-03T10:00:00Z"),
    reapplyEligibleAt: null,
    linkedCreatorId: "cr-meera-shah",
    createdAt: iso("2024-10-25T10:00:00Z"),
    updatedAt: iso("2024-11-03T10:00:00Z"),
  },
  {
    id: "app-anika-desai",
    userId: null,
    fullName: "Anika Desai",
    email: "anika@anikaletters.com",
    locationCity: "Ahmedabad",
    locationCountry: "India",
    avatarUrl: null,
    bio: "Stationery designer & calligraphy artist. Hand-lettered invitations for slow, intentional weddings.",
    primaryExpertise: "stationery",
    secondaryExpertise: [],
    yearsExperience: "3_to_5",
    isIndustryProfessional: true,
    professionalRole: "Independent designer",
    instagramHandle: "@anika.letters",
    youtubeChannel: null,
    tiktokHandle: null,
    blogUrl: "https://anikaletters.com",
    otherSocialLinks: null,
    combinedFollowingRange: "10k_50k",
    portfolioUrls: [],
    contentPlan:
      "Invitation typography deep-dives, letterpress process films, and a curated stationery shop.",
    agreedToTerms: true,
    status: "approved",
    rejectionReasonCategory: null,
    rejectionReasonText: null,
    waitlistNote: null,
    moreInfoRequest: null,
    moreInfoResponse: null,
    adminInternalNotes: null,
    reviewedBy: "admin-ananya",
    reviewedAt: iso("2025-02-14T10:00:00Z"),
    reapplyEligibleAt: null,
    linkedCreatorId: "cr-anika-desai",
    createdAt: iso("2025-02-08T10:00:00Z"),
    updatedAt: iso("2025-02-14T10:00:00Z"),
  },
  {
    id: "app-riya-kapoor",
    userId: null,
    fullName: "Riya Kapoor",
    email: "riya.kapoor.mua@gmail.com",
    locationCity: "Bengaluru",
    locationCountry: "India",
    avatarUrl: null,
    bio: "Bridal makeup artist specializing in South Indian and fusion looks. Trained at Make-Up Atelier Paris.",
    primaryExpertise: "beauty_makeup",
    secondaryExpertise: ["bridal_styling"],
    yearsExperience: "3_to_5",
    isIndustryProfessional: true,
    professionalRole: "Freelance bridal MUA, 60+ brides/year",
    instagramHandle: "@riyakapoor.mua",
    youtubeChannel: "@riyakapoor",
    tiktokHandle: null,
    blogUrl: null,
    otherSocialLinks: "Pinterest: @riyakapoor.mua",
    combinedFollowingRange: "10k_50k",
    portfolioUrls: [],
    contentPlan:
      "Weekly bridal looks, SPF-forward tutorials for South Asian skin tones, and trial-to-wedding-day comparison reels.",
    agreedToTerms: true,
    status: "pending",
    rejectionReasonCategory: null,
    rejectionReasonText: null,
    waitlistNote: null,
    moreInfoRequest: null,
    moreInfoResponse: null,
    adminInternalNotes: null,
    reviewedBy: null,
    reviewedAt: null,
    reapplyEligibleAt: null,
    linkedCreatorId: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "app-fashion-hub-official",
    userId: null,
    fullName: "Fashion Hub Official",
    email: "team@fashionhub.example",
    locationCity: "Dubai",
    locationCountry: "UAE",
    avatarUrl: null,
    bio: "Daily fashion inspiration — the best looks from around the world, all in one place.",
    primaryExpertise: "bridal_styling",
    secondaryExpertise: [],
    yearsExperience: "1_to_3",
    isIndustryProfessional: false,
    professionalRole: null,
    instagramHandle: "@fashionhub.official",
    youtubeChannel: null,
    tiktokHandle: "@fashionhub",
    blogUrl: null,
    otherSocialLinks: null,
    combinedFollowingRange: "100k_500k",
    portfolioUrls: [],
    contentPlan:
      "Daily outfit inspiration reels, curated from top fashion creators.",
    agreedToTerms: true,
    status: "rejected",
    rejectionReasonCategory: "not_wedding_related",
    rejectionReasonText:
      "This is a repost aggregator with no original wedding content. Our creators must produce their own work and focus on wedding-adjacent domains.",
    waitlistNote: null,
    moreInfoRequest: null,
    moreInfoResponse: null,
    adminInternalNotes:
      "No original content, general fashion not wedding-focused. Soft reject — invite reapply once they build a dedicated wedding portfolio.",
    reviewedBy: "admin-ananya",
    reviewedAt: daysAgo(5),
    reapplyEligibleAt: daysFromNow(85),
    linkedCreatorId: null,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(5),
  },
];

export const SEED_APPLICATION_LOGS: ApplicationAdminLog[] = [
  {
    id: "log-priya-1",
    applicationId: "app-priya-patel",
    adminUserId: "admin-ananya",
    action: "status_change",
    oldStatus: "pending",
    newStatus: "approved",
    note: "Anchor creator — approved on intake.",
    createdAt: iso("2024-06-12T10:00:00Z"),
  },
  {
    id: "log-meera-1",
    applicationId: "app-meera-shah",
    adminUserId: "admin-ananya",
    action: "status_change",
    oldStatus: "pending",
    newStatus: "approved",
    note: null,
    createdAt: iso("2024-11-03T10:00:00Z"),
  },
  {
    id: "log-anika-1",
    applicationId: "app-anika-desai",
    adminUserId: "admin-ananya",
    action: "status_change",
    oldStatus: "pending",
    newStatus: "approved",
    note: null,
    createdAt: iso("2025-02-14T10:00:00Z"),
  },
  {
    id: "log-fashion-hub-1",
    applicationId: "app-fashion-hub-official",
    adminUserId: "admin-ananya",
    action: "status_change",
    oldStatus: "pending",
    newStatus: "rejected",
    note: "Not wedding-related; no original content.",
    createdAt: daysAgo(5),
  },
];
