// Social Media Content Generator — seed data for reel templates.
//
// These are written once into localStorage on first load via
// `seedReelTemplatesIfNeeded()` in data.ts. IDs here are stable (not UUIDs) so
// the same template ID keeps pointing at the same config across reseeds.

import type { ReelTemplate, SlideConfig } from "./types";

const SEED_TS = "2026-01-01T00:00:00.000Z";

function slide(s: SlideConfig): SlideConfig {
  return s;
}

// ── Templates ──────────────────────────────────────────────────────────────

const TEMPLATE_BEFORE_AFTER: ReelTemplate = {
  id: "tpl_before_after",
  name: "Before & After",
  description:
    "Reveal a transformation with a clean Before → After cut and a closing title card.",
  category: "showcase",
  thumbnail_url: "",
  vendor_types: [],
  is_premium: false,
  sort_order: 1,
  created_at: SEED_TS,
  template_config: {
    aspect_ratio: "9:16",
    duration_ms: 10000,
    fps: 30,
    music_mood: "upbeat_reveal",
    color_scheme: "auto_from_brand",
    watermark_position: "bottom_right",
    slides: [
      slide({
        id: "s1",
        type: "image",
        label: "Before",
        duration_ms: 3000,
        transition_in: "fade",
        transition_out: "slide_left",
        text_overlay: {
          content_key: "before_label",
          position: "top_center",
          style: "bold_impact",
          animation: "fade_in",
        },
      }),
      slide({
        id: "s2",
        type: "image",
        label: "After",
        duration_ms: 3000,
        transition_in: "slide_left",
        transition_out: "fade",
        text_overlay: {
          content_key: "after_label",
          position: "top_center",
          style: "bold_impact",
          animation: "fade_in",
        },
      }),
      slide({
        id: "s3",
        type: "text",
        label: "Title card",
        duration_ms: 4000,
        transition_in: "fade",
        transition_out: "fade",
        text_overlay: {
          content_key: "project_title",
          position: "center",
          style: "elegant_serif",
          animation: "fade_up",
        },
      }),
    ],
  },
};

const TEMPLATE_CINEMATIC: ReelTemplate = {
  id: "tpl_cinematic_showcase",
  name: "Cinematic Showcase",
  description:
    "Five slow Ken Burns photos with refined typography — made for hero wedding moments.",
  category: "showcase",
  thumbnail_url: "",
  vendor_types: ["photographer", "venue"],
  is_premium: false,
  sort_order: 2,
  created_at: SEED_TS,
  template_config: {
    aspect_ratio: "9:16",
    duration_ms: 15000,
    fps: 30,
    music_mood: "cinematic_swell",
    color_scheme: "auto_from_brand",
    watermark_position: "bottom_right",
    slides: [
      slide({
        id: "s1",
        type: "image",
        label: "Opening hero",
        duration_ms: 3000,
        transition_in: "fade",
        transition_out: "fade",
        ken_burns: { direction: "zoom_in", intensity: 0.1 },
        text_overlay: {
          content_key: "couple_names",
          position: "bottom_center",
          style: "elegant_serif",
          animation: "fade_up",
        },
      }),
      slide({
        id: "s2",
        type: "image",
        label: "Moment",
        duration_ms: 3000,
        transition_in: "fade",
        transition_out: "fade",
        ken_burns: { direction: "zoom_in", intensity: 0.1 },
      }),
      slide({
        id: "s3",
        type: "image",
        label: "Venue",
        duration_ms: 3000,
        transition_in: "fade",
        transition_out: "fade",
        ken_burns: { direction: "zoom_in", intensity: 0.1 },
        text_overlay: {
          content_key: "venue",
          position: "bottom_left",
          style: "minimal",
          animation: "fade_in",
        },
      }),
      slide({
        id: "s4",
        type: "image",
        label: "Detail",
        duration_ms: 3000,
        transition_in: "fade",
        transition_out: "fade",
        ken_burns: { direction: "zoom_in", intensity: 0.1 },
      }),
      slide({
        id: "s5",
        type: "image",
        label: "Closing",
        duration_ms: 3000,
        transition_in: "fade",
        transition_out: "fade",
        ken_burns: { direction: "zoom_in", intensity: 0.1 },
        text_overlay: {
          content_key: "vendor_name_date",
          position: "center",
          style: "elegant_serif",
          animation: "fade_up",
        },
      }),
    ],
  },
};

const TEMPLATE_CLIENT_LOVE: ReelTemplate = {
  id: "tpl_client_love",
  name: "Client Love",
  description:
    "Open with a handwritten client quote, then cut to couple and detail shots.",
  category: "testimonial",
  thumbnail_url: "",
  vendor_types: [],
  is_premium: false,
  sort_order: 3,
  created_at: SEED_TS,
  template_config: {
    aspect_ratio: "9:16",
    duration_ms: 12000,
    fps: 30,
    music_mood: "warm_acoustic",
    color_scheme: "auto_from_brand",
    watermark_position: "bottom_right",
    slides: [
      slide({
        id: "s1",
        type: "text",
        label: "Quote card",
        duration_ms: 4000,
        transition_in: "fade",
        transition_out: "fade",
        text_overlay: {
          content_key: "client_quote",
          position: "center",
          style: "handwritten",
          animation: "typewriter",
        },
      }),
      slide({
        id: "s2",
        type: "image",
        label: "Couple photo",
        duration_ms: 3000,
        transition_in: "fade",
        transition_out: "fade",
        ken_burns: { direction: "zoom_in", intensity: 0.08 },
      }),
      slide({
        id: "s3",
        type: "image",
        label: "Detail 1",
        duration_ms: 2500,
        transition_in: "dissolve",
        transition_out: "dissolve",
      }),
      slide({
        id: "s4",
        type: "image",
        label: "Detail 2",
        duration_ms: 2500,
        transition_in: "dissolve",
        transition_out: "fade",
        text_overlay: {
          content_key: "vendor_name",
          position: "bottom_center",
          style: "elegant_serif",
          animation: "fade_up",
        },
      }),
    ],
  },
};

const TEMPLATE_BEHIND_THE_LENS: ReelTemplate = {
  id: "tpl_behind_the_lens",
  name: "Behind the Lens",
  description:
    "Fast-paced montage of behind-the-scenes moments with a crisp follow CTA.",
  category: "behind_the_scenes",
  thumbnail_url: "",
  vendor_types: ["photographer", "videographer"],
  is_premium: false,
  sort_order: 4,
  created_at: SEED_TS,
  template_config: {
    aspect_ratio: "9:16",
    duration_ms: 10000,
    fps: 30,
    music_mood: "energetic_pulse",
    color_scheme: "auto_from_brand",
    watermark_position: "bottom_right",
    slides: [
      slide({
        id: "s1",
        type: "image",
        label: "Opening title",
        duration_ms: 1667,
        transition_in: "fade",
        transition_out: "slide_left",
        text_overlay: {
          content_key: "title",
          position: "center",
          style: "modern_sans",
          animation: "fade_up",
        },
      }),
      slide({
        id: "s2",
        type: "image",
        label: "BTS 1",
        duration_ms: 1667,
        transition_in: "slide_left",
        transition_out: "slide_left",
      }),
      slide({
        id: "s3",
        type: "image",
        label: "BTS 2",
        duration_ms: 1667,
        transition_in: "slide_left",
        transition_out: "slide_left",
      }),
      slide({
        id: "s4",
        type: "image",
        label: "BTS 3",
        duration_ms: 1667,
        transition_in: "slide_left",
        transition_out: "slide_left",
      }),
      slide({
        id: "s5",
        type: "image",
        label: "BTS 4",
        duration_ms: 1667,
        transition_in: "slide_left",
        transition_out: "slide_left",
      }),
      slide({
        id: "s6",
        type: "text",
        label: "Follow CTA",
        duration_ms: 1665,
        transition_in: "slide_left",
        transition_out: "fade",
        text_overlay: {
          content_key: "follow_cta",
          position: "center",
          style: "bold_impact",
          animation: "fade_up",
        },
      }),
    ],
  },
};

const TEMPLATE_HIGHLIGHT_REEL: ReelTemplate = {
  id: "tpl_highlight_reel",
  name: "The Highlight Reel",
  description:
    "Eight-photo story arc with alternating transitions and gentle motion.",
  category: "showcase",
  thumbnail_url: "",
  vendor_types: [],
  is_premium: false,
  sort_order: 5,
  created_at: SEED_TS,
  template_config: {
    aspect_ratio: "9:16",
    duration_ms: 20000,
    fps: 30,
    music_mood: "uplifting_strings",
    color_scheme: "auto_from_brand",
    watermark_position: "bottom_right",
    slides: [
      slide({
        id: "s1",
        type: "image",
        label: "Opening",
        duration_ms: 2500,
        transition_in: "dissolve",
        transition_out: "dissolve",
        ken_burns: { direction: "zoom_in", intensity: 0.1 },
        text_overlay: {
          content_key: "couple_names",
          position: "bottom_center",
          style: "elegant_serif",
          animation: "fade_up",
        },
      }),
      slide({
        id: "s2",
        type: "image",
        label: "Moment 2",
        duration_ms: 2500,
        transition_in: "slide_left",
        transition_out: "slide_left",
        ken_burns: { direction: "pan_left", intensity: 0.08 },
      }),
      slide({
        id: "s3",
        type: "image",
        label: "Moment 3",
        duration_ms: 2500,
        transition_in: "dissolve",
        transition_out: "dissolve",
        ken_burns: { direction: "zoom_in", intensity: 0.1 },
      }),
      slide({
        id: "s4",
        type: "image",
        label: "Moment 4",
        duration_ms: 2500,
        transition_in: "slide_left",
        transition_out: "slide_left",
        ken_burns: { direction: "pan_left", intensity: 0.08 },
      }),
      slide({
        id: "s5",
        type: "image",
        label: "Moment 5",
        duration_ms: 2500,
        transition_in: "dissolve",
        transition_out: "dissolve",
        ken_burns: { direction: "zoom_in", intensity: 0.1 },
      }),
      slide({
        id: "s6",
        type: "image",
        label: "Moment 6",
        duration_ms: 2500,
        transition_in: "slide_left",
        transition_out: "slide_left",
        ken_burns: { direction: "pan_left", intensity: 0.08 },
      }),
      slide({
        id: "s7",
        type: "image",
        label: "Moment 7",
        duration_ms: 2500,
        transition_in: "dissolve",
        transition_out: "dissolve",
        ken_burns: { direction: "zoom_in", intensity: 0.1 },
      }),
      slide({
        id: "s8",
        type: "image",
        label: "Closing",
        duration_ms: 2500,
        transition_in: "slide_left",
        transition_out: "fade",
        ken_burns: { direction: "pan_left", intensity: 0.08 },
        text_overlay: {
          content_key: "vendor_name",
          position: "bottom_center",
          style: "elegant_serif",
          animation: "fade_up",
        },
      }),
    ],
  },
};

const TEMPLATE_SAVE_THE_DATE: ReelTemplate = {
  id: "tpl_save_the_date",
  name: "Save the Date",
  description:
    "Three-beat announcement: couple photo, date & venue card, then a call to action.",
  category: "announcement",
  thumbnail_url: "",
  vendor_types: ["planner", "photographer"],
  is_premium: false,
  sort_order: 6,
  created_at: SEED_TS,
  template_config: {
    aspect_ratio: "9:16",
    duration_ms: 8000,
    fps: 30,
    music_mood: "dreamy_romance",
    color_scheme: "auto_from_brand",
    watermark_position: "bottom_right",
    slides: [
      slide({
        id: "s1",
        type: "image",
        label: "Couple photo",
        duration_ms: 3000,
        transition_in: "fade",
        transition_out: "fade",
        ken_burns: { direction: "zoom_in", intensity: 0.12 },
        text_overlay: {
          content_key: "couple_names",
          position: "bottom_center",
          style: "elegant_serif",
          animation: "fade_up",
        },
      }),
      slide({
        id: "s2",
        type: "text",
        label: "Date & venue",
        duration_ms: 3000,
        transition_in: "fade",
        transition_out: "fade",
        text_overlay: {
          content_key: "wedding_date_venue",
          position: "center",
          style: "elegant_serif",
          animation: "fade_up",
        },
      }),
      slide({
        id: "s3",
        type: "text",
        label: "CTA",
        duration_ms: 2000,
        transition_in: "fade",
        transition_out: "fade",
        text_overlay: {
          content_key: "cta_text",
          position: "center",
          style: "modern_sans",
          animation: "fade_in",
        },
      }),
    ],
  },
};

const TEMPLATE_MEET_THE_ARTIST: ReelTemplate = {
  id: "tpl_meet_the_artist",
  name: "Meet the Artist",
  description:
    "Warm intro reel: vendor portrait, three portfolio highlights, and a services card.",
  category: "intro",
  thumbnail_url: "",
  vendor_types: [],
  is_premium: false,
  sort_order: 7,
  created_at: SEED_TS,
  template_config: {
    aspect_ratio: "9:16",
    duration_ms: 15000,
    fps: 30,
    music_mood: "warm_inviting",
    color_scheme: "auto_from_brand",
    watermark_position: "bottom_right",
    slides: [
      slide({
        id: "s1",
        type: "image",
        label: "Vendor portrait",
        duration_ms: 3000,
        transition_in: "fade",
        transition_out: "fade",
        ken_burns: { direction: "zoom_in", intensity: 0.08 },
        text_overlay: {
          content_key: "vendor_name_tagline",
          position: "bottom_center",
          style: "elegant_serif",
          animation: "fade_up",
        },
      }),
      slide({
        id: "s2",
        type: "image",
        label: "Portfolio 1",
        duration_ms: 2500,
        transition_in: "dissolve",
        transition_out: "dissolve",
        ken_burns: { direction: "zoom_in", intensity: 0.08 },
      }),
      slide({
        id: "s3",
        type: "image",
        label: "Portfolio 2",
        duration_ms: 2500,
        transition_in: "dissolve",
        transition_out: "dissolve",
        ken_burns: { direction: "pan_right", intensity: 0.08 },
      }),
      slide({
        id: "s4",
        type: "image",
        label: "Portfolio 3",
        duration_ms: 2500,
        transition_in: "dissolve",
        transition_out: "dissolve",
        ken_burns: { direction: "zoom_in", intensity: 0.08 },
      }),
      slide({
        id: "s5",
        type: "text",
        label: "Services & contact",
        duration_ms: 4500,
        transition_in: "fade",
        transition_out: "fade",
        text_overlay: {
          content_key: "services_and_contact",
          position: "center",
          style: "modern_sans",
          animation: "fade_up",
        },
      }),
    ],
  },
};

const TEMPLATE_QUICK_TIPS: ReelTemplate = {
  id: "tpl_quick_tips",
  name: "Quick Tips",
  description:
    "Three bite-sized planning tips over dark-overlay backgrounds — high save rate.",
  category: "tips",
  thumbnail_url: "",
  vendor_types: ["planner", "decorator", "makeup_artist"],
  is_premium: false,
  sort_order: 8,
  created_at: SEED_TS,
  template_config: {
    aspect_ratio: "9:16",
    duration_ms: 12000,
    fps: 30,
    music_mood: "modern_minimal",
    color_scheme: "dark",
    watermark_position: "bottom_right",
    slides: [
      slide({
        id: "s1",
        type: "text",
        label: "Intro",
        duration_ms: 2000,
        transition_in: "fade",
        transition_out: "slide_left",
        text_overlay: {
          content_key: "title",
          position: "center",
          style: "bold_impact",
          animation: "fade_up",
        },
      }),
      slide({
        id: "s2",
        type: "image",
        label: "Tip 1",
        duration_ms: 3333,
        transition_in: "slide_left",
        transition_out: "slide_left",
        text_overlay: {
          content_key: "tip_1",
          position: "center",
          style: "modern_sans",
          animation: "slide_in_left",
        },
      }),
      slide({
        id: "s3",
        type: "image",
        label: "Tip 2",
        duration_ms: 3333,
        transition_in: "slide_left",
        transition_out: "slide_left",
        text_overlay: {
          content_key: "tip_2",
          position: "center",
          style: "modern_sans",
          animation: "slide_in_left",
        },
      }),
      slide({
        id: "s4",
        type: "image",
        label: "Tip 3",
        duration_ms: 3334,
        transition_in: "slide_left",
        transition_out: "fade",
        text_overlay: {
          content_key: "tip_3",
          position: "center",
          style: "modern_sans",
          animation: "slide_in_left",
        },
      }),
    ],
  },
};

export const DEFAULT_REEL_TEMPLATES: ReelTemplate[] = [
  TEMPLATE_BEFORE_AFTER,
  TEMPLATE_CINEMATIC,
  TEMPLATE_CLIENT_LOVE,
  TEMPLATE_BEHIND_THE_LENS,
  TEMPLATE_HIGHLIGHT_REEL,
  TEMPLATE_SAVE_THE_DATE,
  TEMPLATE_MEET_THE_ARTIST,
  TEMPLATE_QUICK_TIPS,
];
