import type {
  Exhibition,
  Exhibitor,
  ExhibitionItem,
} from "@/types/exhibition";

// Today (per project context) ≈ 2026-04-22.
// Live window: Apr 20 → Apr 26.  Upcoming: May 15 → May 21.  Past: Feb 10 → Feb 16.

const iso = (d: string) => new Date(d).toISOString();

export const SEED_EXHIBITIONS: Exhibition[] = [
  {
    id: "ex-bridal-asia-spring-2026",
    title: "Bridal Asia Virtual · Spring 2026",
    slug: "bridal-asia-spring-2026",
    subtitle: "India's most luxurious wedding exhibition, now online",
    description:
      "For the first time, Bridal Asia brings its legendary exhibition experience online. Browse exclusive collections from India's finest bridal designers, jewelers, and wedding specialists — all from the comfort of your home. Exhibition-exclusive pricing on select items. Virtual styling appointments available.",
    cover_image_url: "",
    cover_gradient:
      "linear-gradient(135deg, #B8860B 0%, #D4A843 40%, #F0E4C8 70%, #C97B63 100%)",
    theme_color: "#B8860B",
    starts_at: iso("2026-04-20T00:00:00+05:30"),
    ends_at: iso("2026-04-26T23:59:59+05:30"),
    timezone: "Asia/Kolkata",
    exhibition_type: "general",
    is_free: true,
    requires_rsvp: false,
    status: "live",
    exhibitor_count: 5,
    visitor_count: 14_820,
    presented_by: "Sabyasachi",
    partners: ["Vogue India", "WeddingSutra"],
    created_at: iso("2026-03-01T10:00:00Z"),
  },
  {
    id: "ex-delhi-designer-trunk",
    title: "Delhi Designer Trunk Show",
    slug: "delhi-designer-trunk",
    subtitle: "A curated trunk show of emerging couturiers",
    description:
      "Twelve of India's most exciting new designers — from Delhi to Bengaluru — share their Spring collections in an intimate virtual setting. Appointments available with every exhibitor.",
    cover_image_url: "",
    cover_gradient:
      "linear-gradient(135deg, #5B8E8A 0%, #85AEAB 40%, #DCE9E7 100%)",
    theme_color: "#5B8E8A",
    starts_at: iso("2026-05-15T00:00:00+05:30"),
    ends_at: iso("2026-05-21T23:59:59+05:30"),
    timezone: "Asia/Kolkata",
    exhibition_type: "fashion",
    is_free: true,
    requires_rsvp: true,
    status: "upcoming",
    exhibitor_count: 3,
    visitor_count: 0,
    partners: ["Elle India"],
    created_at: iso("2026-03-15T10:00:00Z"),
  },
  {
    id: "ex-jewelry-week-2026",
    title: "Jewelry Week Virtual",
    slug: "jewelry-week-virtual-2026",
    subtitle: "Heirloom kundan, polki, and diamond houses — in one place",
    description:
      "A week-long virtual showcase from India's most respected jewelry houses. Browse bridal sets, solitaires, and heritage pieces with house-specific exhibition pricing.",
    cover_image_url: "",
    cover_gradient:
      "linear-gradient(135deg, #9CAF88 0%, #B8C9A8 50%, #E8F0E0 100%)",
    theme_color: "#9CAF88",
    starts_at: iso("2026-02-10T00:00:00+05:30"),
    ends_at: iso("2026-02-16T23:59:59+05:30"),
    timezone: "Asia/Kolkata",
    exhibition_type: "jewelry",
    is_free: true,
    requires_rsvp: false,
    status: "ended",
    exhibitor_count: 2,
    visitor_count: 28_440,
    partners: ["Vogue India"],
    created_at: iso("2026-01-10T10:00:00Z"),
  },
];

// ── Exhibitors ─────────────────────────────────────────────────────────────

export const SEED_EXHIBITORS: Exhibitor[] = [
  // ── Bridal Asia (live) ──────────────────────────────────────────────
  {
    id: "booth-sabyasachi",
    exhibition_id: "ex-bridal-asia-spring-2026",
    external_name: "Sabyasachi",
    external_website: "https://sabyasachi.com",
    external_instagram: "sabyasachiofficial",
    booth_name: "Sabyasachi Heritage Bridal",
    booth_tagline: "Where tradition meets timeless craft",
    booth_description:
      "For Spring 2026, we return to the poetry of Benarasi weaving — each piece a conversation between the loom and the bride. This exhibition-exclusive collection features twelve never-before-seen lehengas.",
    booth_cover_image_url: "",
    booth_gradient:
      "linear-gradient(135deg, #7A0E1F 0%, #B8860B 60%, #F0E4C8 100%)",
    booth_category: "bridal_wear",
    booth_tags: ["bridal-lehenga", "benarasi", "heritage", "luxury"],
    has_exclusive_pricing: true,
    has_new_collection: true,
    has_limited_edition: true,
    offers_virtual_appointment: true,
    cta_label: "Book Appointment",
    whatsapp_number: "+91 98100 00001",
    is_featured: true,
    sort_order: 1,
    view_count: 3_240,
    inquiry_count: 58,
    wishlist_count: 412,
  },
  {
    id: "booth-tarun-tahiliani",
    exhibition_id: "ex-bridal-asia-spring-2026",
    external_name: "Tarun Tahiliani",
    external_website: "https://taruntahiliani.com",
    external_instagram: "taruntahilianiofficial",
    booth_name: "Tarun Tahiliani · Bridal Couture",
    booth_tagline: "Indo-western couture for the modern bride",
    booth_description:
      "Our Spring 2026 line reinterprets the classical drape through hand-structured silhouettes. Every piece is made-to-measure, finished in our Mumbai atelier.",
    booth_cover_image_url: "",
    booth_gradient:
      "linear-gradient(135deg, #2E2E2E 0%, #6B6B6B 50%, #D4A843 100%)",
    booth_category: "bridal_wear",
    booth_tags: ["indo-western", "drape", "couture", "made-to-measure"],
    has_exclusive_pricing: true,
    has_new_collection: true,
    has_limited_edition: false,
    offers_virtual_appointment: true,
    cta_label: "Inquire",
    whatsapp_number: "+91 98100 00002",
    is_featured: true,
    sort_order: 2,
    view_count: 2_150,
    inquiry_count: 34,
    wishlist_count: 287,
  },
  {
    id: "booth-anita-dongre",
    exhibition_id: "ex-bridal-asia-spring-2026",
    external_name: "Anita Dongre",
    external_website: "https://anitadongre.com",
    external_instagram: "anitadongre",
    booth_name: "Anita Dongre · Jaipur Archives",
    booth_tagline: "Block-printed bridal for the free-spirited",
    booth_description:
      "An archival drop of hand-block-printed lehengas and sarees from our Jaipur atelier. Soft, breathable, and weightless — made for outdoor and daytime weddings.",
    booth_cover_image_url: "",
    booth_gradient:
      "linear-gradient(135deg, #F5E0D6 0%, #DDA08A 60%, #C97B63 100%)",
    booth_category: "bridal_wear",
    booth_tags: ["block-print", "jaipur", "pastel", "daywear"],
    has_exclusive_pricing: false,
    has_new_collection: true,
    has_limited_edition: false,
    offers_virtual_appointment: true,
    cta_label: "Book Appointment",
    whatsapp_number: "+91 98100 00003",
    is_featured: true,
    sort_order: 3,
    view_count: 1_420,
    inquiry_count: 22,
    wishlist_count: 198,
  },
  {
    id: "booth-tanishq",
    exhibition_id: "ex-bridal-asia-spring-2026",
    external_name: "Tanishq",
    external_website: "https://tanishq.co.in",
    external_instagram: "tanishqjewellery",
    booth_name: "Tanishq · Rivaah Bridal",
    booth_tagline: "Every region's bridal set, in one booth",
    booth_description:
      "The Rivaah collection brings together bridal jewelry traditions from Bengal, Maharashtra, Tamil Nadu, Punjab, and beyond. Exhibition-exclusive 12% making-charge waiver on select sets.",
    booth_cover_image_url: "",
    booth_gradient:
      "linear-gradient(135deg, #B8860B 0%, #D4A843 50%, #F0E4C8 100%)",
    booth_category: "jewelry",
    booth_tags: ["kundan", "polki", "regional", "bridal-set"],
    has_exclusive_pricing: true,
    has_new_collection: false,
    has_limited_edition: false,
    offers_virtual_appointment: true,
    cta_label: "Book Appointment",
    whatsapp_number: "+91 98100 00004",
    is_featured: true,
    sort_order: 4,
    view_count: 1_880,
    inquiry_count: 41,
    wishlist_count: 316,
  },
  {
    id: "booth-manish-malhotra",
    exhibition_id: "ex-bridal-asia-spring-2026",
    external_name: "Manish Malhotra",
    external_website: "https://manishmalhotra.in",
    external_instagram: "manishmalhotraworld",
    booth_name: "Manish Malhotra · The Groom Edit",
    booth_tagline: "Sherwanis, bandhgalas, and wedding suits",
    booth_description:
      "A dedicated groom-wear edit featuring hand-embroidered sherwanis, tailored bandhgalas, and occasion suits. Every piece is available in made-to-measure.",
    booth_cover_image_url: "",
    booth_gradient:
      "linear-gradient(135deg, #1A1A1A 0%, #2E2E2E 60%, #B8860B 100%)",
    booth_category: "groom_wear",
    booth_tags: ["sherwani", "bandhgala", "groom", "made-to-measure"],
    has_exclusive_pricing: false,
    has_new_collection: true,
    has_limited_edition: true,
    offers_virtual_appointment: true,
    cta_label: "Book Appointment",
    whatsapp_number: "+91 98100 00005",
    is_featured: false,
    sort_order: 5,
    view_count: 960,
    inquiry_count: 17,
    wishlist_count: 134,
  },

  // ── Delhi Designer Trunk (upcoming) ─────────────────────────────────
  {
    id: "booth-rahul-mishra",
    exhibition_id: "ex-delhi-designer-trunk",
    external_name: "Rahul Mishra",
    external_instagram: "rahulmishra_7",
    booth_name: "Rahul Mishra · Botanica",
    booth_tagline: "Hand-embroidered florals, Paris-couture craft",
    booth_description:
      "A preview of our Spring 2026 Botanica line — three-dimensional floral embroidery on silk organza. Each piece takes 2,500+ hours to complete.",
    booth_cover_image_url: "",
    booth_gradient:
      "linear-gradient(135deg, #E8F0E0 0%, #9CAF88 60%, #5B8E8A 100%)",
    booth_category: "bridal_wear",
    booth_tags: ["couture", "floral", "organza", "paris"],
    has_exclusive_pricing: false,
    has_new_collection: true,
    has_limited_edition: true,
    offers_virtual_appointment: true,
    cta_label: "Remind Me",
    is_featured: true,
    sort_order: 1,
    view_count: 0,
    inquiry_count: 0,
    wishlist_count: 0,
  },
  {
    id: "booth-gaurav-gupta",
    exhibition_id: "ex-delhi-designer-trunk",
    external_name: "Gaurav Gupta",
    external_instagram: "gauravguptaofficial",
    booth_name: "Gaurav Gupta Couture",
    booth_tagline: "Sculptural drape, cosmic line",
    booth_description:
      "An exclusive preview of the Nebula collection — structural sarees and gowns that push Indian silhouettes into the future.",
    booth_cover_image_url: "",
    booth_gradient:
      "linear-gradient(135deg, #2E2E2E 0%, #5B8E8A 50%, #B8C9A8 100%)",
    booth_category: "bridal_wear",
    booth_tags: ["couture", "sculpture", "indo-western", "gown"],
    has_exclusive_pricing: false,
    has_new_collection: true,
    has_limited_edition: false,
    offers_virtual_appointment: true,
    cta_label: "Remind Me",
    is_featured: true,
    sort_order: 2,
    view_count: 0,
    inquiry_count: 0,
    wishlist_count: 0,
  },
  {
    id: "booth-punit-balana",
    exhibition_id: "ex-delhi-designer-trunk",
    external_name: "Punit Balana",
    external_instagram: "punitbalana",
    booth_name: "Punit Balana",
    booth_tagline: "Jaipur prints, contemporary silhouettes",
    booth_description:
      "A quieter, printed-lehenga edit — a lighter alternative for intimate weddings and daytime ceremonies.",
    booth_cover_image_url: "",
    booth_gradient:
      "linear-gradient(135deg, #F5E6C8 0%, #D4A24C 60%, #B8860B 100%)",
    booth_category: "bridal_wear",
    booth_tags: ["jaipur", "print", "daywear", "intimate"],
    has_exclusive_pricing: false,
    has_new_collection: true,
    has_limited_edition: false,
    offers_virtual_appointment: false,
    cta_label: "Remind Me",
    is_featured: false,
    sort_order: 3,
    view_count: 0,
    inquiry_count: 0,
    wishlist_count: 0,
  },

  // ── Jewelry Week (ended) ────────────────────────────────────────────
  {
    id: "booth-amrapali",
    exhibition_id: "ex-jewelry-week-2026",
    external_name: "Amrapali Jaipur",
    external_website: "https://amrapalijaipur.com",
    external_instagram: "amrapalijewels",
    booth_name: "Amrapali Jaipur Archive",
    booth_tagline: "Temple jewelry, tribal craft, living heritage",
    booth_description:
      "A rare archival drop — pieces inspired by temple sculptures, regional bridal traditions, and the Amrapali museum collection.",
    booth_cover_image_url: "",
    booth_gradient:
      "linear-gradient(135deg, #B8860B 0%, #D4A843 50%, #F5E6C8 100%)",
    booth_category: "jewelry",
    booth_tags: ["temple", "tribal", "archive", "silver"],
    has_exclusive_pricing: true,
    has_new_collection: false,
    has_limited_edition: true,
    offers_virtual_appointment: true,
    cta_label: "Inquire",
    is_featured: true,
    sort_order: 1,
    view_count: 4_120,
    inquiry_count: 92,
    wishlist_count: 608,
  },
  {
    id: "booth-sunita-shekhawat",
    exhibition_id: "ex-jewelry-week-2026",
    external_name: "Sunita Shekhawat",
    external_website: "https://sunitashekhawat.com",
    external_instagram: "sunitashekhawatjaipur",
    booth_name: "Sunita Shekhawat · Meenakari",
    booth_tagline: "Jaipur meenakari, in its most refined form",
    booth_description:
      "The most delicate hand-enameled bridal jewelry from the Jaipur atelier. Each piece is made over 90+ days by a single craftsman.",
    booth_cover_image_url: "",
    booth_gradient:
      "linear-gradient(135deg, #C97B63 0%, #DDA08A 50%, #F5E0D6 100%)",
    booth_category: "jewelry",
    booth_tags: ["meenakari", "jaipur", "bridal", "polki"],
    has_exclusive_pricing: false,
    has_new_collection: false,
    has_limited_edition: true,
    offers_virtual_appointment: true,
    cta_label: "Inquire",
    is_featured: true,
    sort_order: 2,
    view_count: 2_850,
    inquiry_count: 48,
    wishlist_count: 331,
  },
];

// ── Items ──────────────────────────────────────────────────────────────────

const gradient = (a: string, b: string, c: string) =>
  `linear-gradient(135deg, ${a} 0%, ${b} 50%, ${c} 100%)`;

export const SEED_ITEMS: ExhibitionItem[] = [
  // Sabyasachi
  {
    id: "item-sabya-maharani",
    exhibitor_id: "booth-sabyasachi",
    name: "The Maharani Lehenga",
    description:
      "Hand-embroidered zardozi on raw silk in our signature Bengal red. Each lehenga takes 1,800 hours to craft. Includes matching dupatta and unstitched blouse fabric.",
    images: [],
    image_gradient: gradient("#7A0E1F", "#B8860B", "#F0E4C8"),
    price_display: "₹2,85,000",
    exhibition_price_cents: 28_500_000,
    is_price_on_request: false,
    item_type: "product",
    tags: ["bridal", "lehenga", "red", "zardozi", "heavy-work", "bengal-silk"],
    is_exhibition_exclusive: true,
    is_limited_edition: true,
    is_new_launch: false,
    quantity_available: 3,
    sort_order: 1,
    is_featured: true,
    view_count: 1_840,
    wishlist_count: 212,
    inquiry_count: 27,
  },
  {
    id: "item-sabya-kanjivaram",
    exhibitor_id: "booth-sabyasachi",
    name: "The Heritage Kanjivaram",
    description:
      "A nine-yard silk kanjivaram in aubergine with a pure-zari border. Woven over four months in Kanchipuram.",
    images: [],
    image_gradient: gradient("#4A1942", "#7A0E1F", "#D4A843"),
    price_display: "₹1,45,000",
    exhibition_price_cents: 14_500_000,
    is_price_on_request: false,
    item_type: "product",
    tags: ["bridal", "kanjivaram", "silk", "zari", "south-indian"],
    is_exhibition_exclusive: false,
    is_limited_edition: false,
    is_new_launch: true,
    sort_order: 2,
    is_featured: false,
    view_count: 820,
    wishlist_count: 94,
    inquiry_count: 12,
  },
  {
    id: "item-sabya-jewel",
    exhibitor_id: "booth-sabyasachi",
    name: "Bengal Heritage Choker",
    description:
      "Uncut-diamond polki choker with south-sea pearl drops. Set in 22-carat gold.",
    images: [],
    image_gradient: gradient("#B8860B", "#D4A843", "#FFFFFF"),
    is_price_on_request: true,
    price_display: "Price on request",
    item_type: "product",
    tags: ["jewelry", "polki", "pearl", "choker"],
    is_exhibition_exclusive: true,
    is_limited_edition: true,
    is_new_launch: false,
    quantity_available: 1,
    sort_order: 3,
    is_featured: false,
    view_count: 612,
    wishlist_count: 78,
    inquiry_count: 15,
  },

  // Tarun Tahiliani
  {
    id: "item-tarun-drape",
    exhibitor_id: "booth-tarun-tahiliani",
    name: "The Pre-Stitched Drape",
    description:
      "A structured pre-draped saree in champagne tulle with crystal work. Zip closure, blouse included.",
    images: [],
    image_gradient: gradient("#2E2E2E", "#A3A3A3", "#F5E6C8"),
    price_display: "₹1,95,000",
    exhibition_price_cents: 19_500_000,
    is_price_on_request: false,
    item_type: "product",
    tags: ["indo-western", "drape", "saree", "crystal"],
    is_exhibition_exclusive: true,
    is_limited_edition: false,
    is_new_launch: true,
    sort_order: 1,
    is_featured: true,
    view_count: 740,
    wishlist_count: 88,
    inquiry_count: 11,
  },
  {
    id: "item-tarun-cape",
    exhibitor_id: "booth-tarun-tahiliani",
    name: "The Sangeet Cape-Lehenga",
    description:
      "A hand-embroidered cape paired with a sculpted lehenga. Silver sequin work on ivory net.",
    images: [],
    image_gradient: gradient("#6B6B6B", "#D4A843", "#FBF9F4"),
    price_display: "₹2,40,000",
    exhibition_price_cents: 24_000_000,
    is_price_on_request: false,
    item_type: "product",
    tags: ["lehenga", "cape", "sangeet", "silver"],
    is_exhibition_exclusive: false,
    is_limited_edition: false,
    is_new_launch: true,
    sort_order: 2,
    is_featured: false,
    view_count: 520,
    wishlist_count: 64,
    inquiry_count: 8,
  },
  {
    id: "item-tarun-appt",
    exhibitor_id: "booth-tarun-tahiliani",
    name: "60-min Virtual Styling Session",
    description:
      "One-on-one virtual consultation with a senior stylist from the Tarun Tahiliani atelier. Complimentary during the exhibition.",
    images: [],
    image_gradient: gradient("#2E2E2E", "#6B6B6B", "#D4A843"),
    price_display: "Complimentary · exhibition only",
    is_price_on_request: false,
    item_type: "experience",
    tags: ["appointment", "styling", "virtual"],
    is_exhibition_exclusive: true,
    is_limited_edition: false,
    is_new_launch: false,
    sort_order: 3,
    is_featured: false,
    view_count: 340,
    wishlist_count: 41,
    inquiry_count: 22,
  },

  // Anita Dongre
  {
    id: "item-dongre-jaya",
    exhibitor_id: "booth-anita-dongre",
    name: "The Jaya Lehenga",
    description:
      "Hand-block-printed cotton-silk lehenga in dusty pink with gota-patti borders.",
    images: [],
    image_gradient: gradient("#F5E0D6", "#DDA08A", "#C97B63"),
    price_display: "₹85,000",
    exhibition_price_cents: 8_500_000,
    is_price_on_request: false,
    item_type: "product",
    tags: ["lehenga", "block-print", "daywear", "pastel"],
    is_exhibition_exclusive: false,
    is_limited_edition: false,
    is_new_launch: true,
    sort_order: 1,
    is_featured: true,
    view_count: 620,
    wishlist_count: 74,
    inquiry_count: 9,
  },
  {
    id: "item-dongre-saree",
    exhibitor_id: "booth-anita-dongre",
    name: "Chanderi Silk Saree",
    description:
      "A pure chanderi saree in seafoam with gold zari stripes. Ideal for mehndi and haldi ceremonies.",
    images: [],
    image_gradient: gradient("#E8F0E0", "#9CAF88", "#D4A843"),
    price_display: "₹45,000",
    exhibition_price_cents: 4_500_000,
    is_price_on_request: false,
    item_type: "product",
    tags: ["saree", "chanderi", "zari", "daywear"],
    is_exhibition_exclusive: false,
    is_limited_edition: false,
    is_new_launch: false,
    sort_order: 2,
    is_featured: false,
    view_count: 380,
    wishlist_count: 45,
    inquiry_count: 6,
  },

  // Tanishq
  {
    id: "item-tanishq-polki",
    exhibitor_id: "booth-tanishq",
    name: "Rivaah Bengal Polki Set",
    description:
      "A complete Bengali bridal set — choker, long haar, earrings, tikka, and nath. Uncut polki diamonds set in 22k gold.",
    images: [],
    image_gradient: gradient("#B8860B", "#D4A843", "#F0E4C8"),
    price_display: "₹12,40,000",
    original_price_cents: 132_000_000,
    exhibition_price_cents: 124_000_000,
    is_price_on_request: false,
    item_type: "product",
    tags: ["jewelry", "polki", "bengal", "bridal-set"],
    is_exhibition_exclusive: true,
    is_limited_edition: false,
    is_new_launch: false,
    sort_order: 1,
    is_featured: true,
    view_count: 910,
    wishlist_count: 128,
    inquiry_count: 19,
  },
  {
    id: "item-tanishq-kundan",
    exhibitor_id: "booth-tanishq",
    name: "Rivaah Punjabi Kundan Set",
    description:
      "Tikka-jhumar-choker-haar-kalire combination for Punjabi and Sikh bridal ceremonies.",
    images: [],
    image_gradient: gradient("#D4A843", "#F5E6C8", "#FFFFFF"),
    price_display: "₹8,20,000",
    exhibition_price_cents: 82_000_000,
    is_price_on_request: false,
    item_type: "product",
    tags: ["jewelry", "kundan", "punjabi", "bridal-set"],
    is_exhibition_exclusive: true,
    is_limited_edition: false,
    is_new_launch: false,
    sort_order: 2,
    is_featured: false,
    view_count: 640,
    wishlist_count: 89,
    inquiry_count: 14,
  },

  // Manish Malhotra
  {
    id: "item-mm-sherwani",
    exhibitor_id: "booth-manish-malhotra",
    name: "The Zardozi Sherwani",
    description:
      "Ivory raw-silk sherwani with gold zardozi on the placket and cuffs. Includes matching churidar and dupatta.",
    images: [],
    image_gradient: gradient("#FBF9F4", "#F5E6C8", "#B8860B"),
    price_display: "₹1,95,000",
    exhibition_price_cents: 19_500_000,
    is_price_on_request: false,
    item_type: "product",
    tags: ["sherwani", "zardozi", "groom", "ivory"],
    is_exhibition_exclusive: false,
    is_limited_edition: true,
    is_new_launch: true,
    sort_order: 1,
    is_featured: true,
    view_count: 420,
    wishlist_count: 58,
    inquiry_count: 7,
  },
  {
    id: "item-mm-bandhgala",
    exhibitor_id: "booth-manish-malhotra",
    name: "Midnight Bandhgala",
    description:
      "A deep-navy wool-blend bandhgala with hand-stitched button work. For reception and cocktail wear.",
    images: [],
    image_gradient: gradient("#1A1A1A", "#2E2E2E", "#5B8E8A"),
    price_display: "₹1,25,000",
    exhibition_price_cents: 12_500_000,
    is_price_on_request: false,
    item_type: "product",
    tags: ["bandhgala", "groom", "reception", "wool"],
    is_exhibition_exclusive: false,
    is_limited_edition: false,
    is_new_launch: true,
    sort_order: 2,
    is_featured: false,
    view_count: 260,
    wishlist_count: 34,
    inquiry_count: 4,
  },

  // Rahul Mishra (upcoming)
  {
    id: "item-rm-teaser",
    exhibitor_id: "booth-rahul-mishra",
    name: "Botanica Spring 2026 — collection preview",
    description:
      "A preview lookbook of the Botanica collection. Full pieces unlocked when the exhibition opens on May 15.",
    images: [],
    image_gradient: gradient("#9CAF88", "#B8C9A8", "#E8F0E0"),
    is_price_on_request: true,
    price_display: "Unlocks May 15",
    item_type: "collection",
    tags: ["preview", "couture", "floral"],
    is_exhibition_exclusive: false,
    is_limited_edition: false,
    is_new_launch: true,
    sort_order: 1,
    is_featured: true,
    view_count: 0,
    wishlist_count: 0,
    inquiry_count: 0,
  },

  // Amrapali (ended)
  {
    id: "item-amra-temple",
    exhibitor_id: "booth-amrapali",
    name: "Temple Silver Bridal Set",
    description:
      "Hand-cast silver bridal set inspired by a 9th-century Pallava temple idol. Includes haar, earrings, and armband.",
    images: [],
    image_gradient: gradient("#A3A3A3", "#D4A843", "#F5E6C8"),
    price_display: "₹3,20,000",
    exhibition_price_cents: 32_000_000,
    is_price_on_request: false,
    item_type: "product",
    tags: ["temple", "silver", "bridal-set", "archival"],
    is_exhibition_exclusive: false,
    is_limited_edition: true,
    is_new_launch: false,
    sort_order: 1,
    is_featured: true,
    view_count: 1_240,
    wishlist_count: 182,
    inquiry_count: 36,
  },
  {
    id: "item-sunita-meena",
    exhibitor_id: "booth-sunita-shekhawat",
    name: "The Peacock Meenakari Choker",
    description:
      "A signature piece — peacock-motif meenakari choker in emerald, ruby, and white enamel. Hand-painted on 22k gold base.",
    images: [],
    image_gradient: gradient("#5B8E8A", "#9CAF88", "#F5E6C8"),
    is_price_on_request: true,
    price_display: "Price on request",
    item_type: "product",
    tags: ["meenakari", "peacock", "archival", "choker"],
    is_exhibition_exclusive: false,
    is_limited_edition: true,
    is_new_launch: false,
    quantity_available: 1,
    sort_order: 1,
    is_featured: true,
    view_count: 980,
    wishlist_count: 142,
    inquiry_count: 24,
  },
];
