// ──────────────────────────────────────────────────────────────────────────
// Tools Hub catalog — the canonical list rendered by /tools.
//
// 8 flagship "headliner" tools (large carousel cards) +
// 50+ mini tools (compact grid cards) grouped into 7 browsable categories.
//
// Mini tool pages don't exist yet — their slugs link to /tools/[slug]
// placeholders. Status drives the badge: "live" tools render and work,
// "coming-soon" tools show a muted badge and route to a stub page.
// ──────────────────────────────────────────────────────────────────────────

export type ToolCategory =
  | 'planning'
  | 'money'
  | 'astrology'
  | 'style'
  | 'family'
  | 'fun'
  | 'day-of';

export type ToolStatus = 'live' | 'coming-soon';

export interface CatalogTool {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  description: string;
  category: ToolCategory;
  isFeatured: boolean;
  status: ToolStatus;
  estimatedTime: string;
  featurePills: string[];
  ctaText: string;
  gradientFrom: string;
  gradientTo: string;
  icon?: string;
}

export const CATEGORY_LABELS: Record<ToolCategory, string> = {
  planning: 'Planning & Logistics',
  money: 'Money & Budget',
  astrology: 'Astrology & Dates',
  style: 'Style & Vibes',
  family: 'Family & Guests',
  fun: 'Fun & Shareable',
  'day-of': 'Day-Of',
};

export const CATEGORY_DOTS: Record<ToolCategory, string> = {
  planning: '#A8B5A0',
  money: '#D4943A',
  astrology: '#3D3580',
  style: '#E8B4B8',
  family: '#C9A96E',
  fun: '#E07A5F',
  'day-of': '#7A1F3E',
};

export const FLAGSHIP_ORDER: string[] = [
  'budget',
  'kundli',
  'guests',
  'dates',
  'visualizer',
  'ready',
  'wedding-stars',
  'shagun',
];

export const TOOLS_CATALOG: CatalogTool[] = [
  // ── 8 FLAGSHIP TOOLS ─────────────────────────────────────────────────
  {
    id: 'budget',
    slug: 'budget',
    name: 'Shaadi Budget',
    tagline: 'the budget tool that actually gets Indian weddings',
    description:
      'Mehndi to vidaai. Real DFW vendor pricing across all events — no generic spreadsheet templates.',
    category: 'money',
    isFeatured: true,
    status: 'live',
    estimatedTime: '5 min',
    featurePills: ['REAL VENDOR PRICING', 'ALL EVENTS'],
    ctaText: 'BUILD YOUR BUDGET →',
    gradientFrom: '#E8F0E0',
    gradientTo: '#F0E4C8',
    icon: '₹',
  },
  {
    id: 'kundli',
    slug: 'kundli',
    name: 'Kundli Match',
    tagline: 'do your stars actually align — or is that just a saying',
    description:
      'Enter both birth details. Get the full 36-point Ashtakoota compatibility report — translated for parents AND partners.',
    category: 'astrology',
    isFeatured: true,
    status: 'live',
    estimatedTime: '5 min',
    featurePills: ['36 GUNA MILAN', 'DOSHA ANALYSIS'],
    ctaText: 'MATCH YOUR KUNDLI →',
    gradientFrom: '#3D3580',
    gradientTo: '#1F1A4A',
    icon: '✦',
  },
  {
    id: 'guests',
    slug: 'guests',
    name: 'Guest Count Estimator',
    tagline: "your parents say 400. your fiancé says 150. find the real number.",
    description:
      'Side-by-side family guest builder with per-event attendance modeling. The number everyone can argue about — with data.',
    category: 'family',
    isFeatured: true,
    status: 'live',
    estimatedTime: '5 min',
    featurePills: ['BOTH-SIDES BREAKDOWN', 'PER-EVENT'],
    ctaText: 'ESTIMATE YOUR COUNT →',
    gradientFrom: '#FFD8B8',
    gradientTo: '#F0E4C8',
    icon: '👥',
  },
  {
    id: 'dates',
    slug: 'dates',
    name: 'Auspicious Date Finder',
    tagline: 'when the stars say yes and so does your venue',
    description:
      'Multi-tradition calendar with muhurat dates, weather, and venue pricing for 2026 and 2027.',
    category: 'astrology',
    isFeatured: true,
    status: 'live',
    estimatedTime: '5 min',
    featurePills: ['MULTI-TRADITION', 'VENUE SEASONS'],
    ctaText: 'FIND YOUR DATE →',
    gradientFrom: '#D4943A',
    gradientTo: '#F5E6C8',
    icon: '✦',
  },
  {
    id: 'visualizer',
    slug: 'visualizer',
    name: 'Wedding Weekend Visualizer',
    tagline: 'see your whole wedding weekend before you plan a thing',
    description:
      'Multi-event timeline generator. Hour-by-hour, outfit change by outfit change.',
    category: 'planning',
    isFeatured: true,
    status: 'live',
    estimatedTime: '5 min',
    featurePills: ['MULTI-EVENT', 'CULTURALLY AWARE'],
    ctaText: 'VISUALIZE YOUR WEEKEND →',
    gradientFrom: '#E0D0F0',
    gradientTo: '#FBEAF0',
    icon: '📅',
  },
  {
    id: 'ready',
    slug: 'ready',
    name: 'Am I Ready?',
    tagline: 'how behind are you, really — and what to do about it',
    description:
      'Interactive readiness assessment with a personalized priority list. 18 months out or 18 weeks — we tell you what to lock down this week.',
    category: 'planning',
    isFeatured: true,
    status: 'live',
    estimatedTime: '2 min',
    featurePills: ['8 QUESTIONS', 'SOUTH ASIAN CALIBRATED'],
    ctaText: 'CHECK YOUR READINESS →',
    gradientFrom: '#E07A5F',
    gradientTo: '#FFD8B8',
    icon: '✓',
  },
  {
    id: 'wedding-stars',
    slug: 'wedding-stars',
    name: 'Wedding Stars',
    tagline: 'your cosmic calendar for every big decision',
    description:
      'Personalized planetary transit timeline mapping the next 12 months — when to book, when to pause, when the stars are practically begging you to dress shop.',
    category: 'astrology',
    isFeatured: true,
    status: 'live',
    estimatedTime: '5 min',
    featurePills: ['VEDIC TRANSITS', 'PERSONALIZED'],
    ctaText: 'READ YOUR STARS →',
    gradientFrom: '#1F1A4A',
    gradientTo: '#3D3580',
    icon: '✦',
  },
  {
    id: 'shagun',
    slug: 'shagun',
    name: 'Shagun Calculator',
    tagline: 'how much do you actually give — and no, $100 is not the answer',
    description:
      'Culturally-calibrated shagun amount calculator. Your relationship, their wedding, your tradition — we give you the real number.',
    category: 'money',
    isFeatured: true,
    status: 'live',
    estimatedTime: '2 min',
    featurePills: ['USD CALIBRATED', 'EVERY TIER'],
    ctaText: 'CALCULATE SHAGUN →',
    gradientFrom: '#D4A853',
    gradientTo: '#C9A96E',
    icon: '₹',
  },

  // ── PLANNING & LOGISTICS (mini) ──────────────────────────────────────
  {
    id: 'timeline-builder',
    slug: 'timeline-builder',
    name: 'Indian Wedding Timeline Builder',
    tagline: 'which events, which days, what order?',
    description:
      'Drag your events across Day 1, 2, and 3. We hand back a day-of skeleton for every event — the kind of thing your planner would charge you for.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '2 min',
    featurePills: ['DRAG & DROP', 'PRINTABLE'],
    ctaText: 'BUILD YOUR TIMELINE →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'vendor-checklist',
    slug: 'vendor-checklist',
    name: 'Vendor Checklist',
    tagline: 'who do you actually need to hire?',
    description:
      'Pick your events. We sort 18 vendor categories into required, recommended, and optional — with booking windows and 3 questions to ask each one.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['18 CATEGORIES', 'BOOKING WINDOWS'],
    ctaText: 'GET YOUR LIST →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'wedding-weekend-lite',
    slug: 'wedding-weekend-lite',
    name: 'Wedding Weekend Planner Lite',
    tagline: 'how many days does your wedding actually need?',
    description: 'Input your event count, get a suggested day structure.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['INSTANT'],
    ctaText: 'PLAN IT →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'vendor-booking-timeline',
    slug: 'vendor-booking-timeline',
    name: 'Vendor Booking Timeline',
    tagline: 'when should you book each vendor?',
    description: 'Input your wedding date, get a reverse-timeline checklist.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['REVERSE TIMELINE'],
    ctaText: 'GENERATE →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'mehendi-time',
    slug: 'mehendi-time',
    name: 'Mehendi Time Calculator',
    tagline: 'how long will mehendi night actually take?',
    description: 'Guest count + number of artists = total hours.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['QUICK MATH'],
    ctaText: 'CALCULATE →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'baraat-duration',
    slug: 'baraat-duration',
    name: 'Baraat Duration Estimator',
    tagline: 'how long is the baraat, really?',
    description: 'Distance + dancing guests + horse or car = realistic time.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['REALISTIC'],
    ctaText: 'ESTIMATE →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'ceremony-duration',
    slug: 'ceremony-duration',
    name: 'Ceremony Duration Estimator',
    tagline: 'how long will the pheras take?',
    description: 'Select ceremony type, get a realistic time range.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['ALL TRADITIONS'],
    ctaText: 'CHECK →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'plate-count',
    slug: 'plate-count',
    name: 'Plate Count Calculator',
    tagline: 'how many plates does your caterer need?',
    description: 'Guest count × events × meal type = total covers.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['MULTI-EVENT'],
    ctaText: 'CALCULATE →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'invitation-timeline',
    slug: 'invitation-timeline',
    name: 'Invitation Timeline Calculator',
    tagline: 'when should you send what?',
    description: 'Input wedding date, get save-the-date, invitation, and RSVP deadline dates.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['ALL DATES'],
    ctaText: 'GENERATE →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'parking-shuttle',
    slug: 'parking-shuttle',
    name: 'Parking & Shuttle Calculator',
    tagline: 'do you need a shuttle?',
    description: 'Guest count + venue parking capacity = shuttle need assessment.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['LOGISTICS'],
    ctaText: 'CHECK →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'hotel-room-block',
    slug: 'hotel-room-block',
    name: 'Hotel Room Block Estimator',
    tagline: 'how many hotel rooms do you need?',
    description: 'Out-of-town guests ÷ average room occupancy = block size.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['BLOCK SIZE'],
    ctaText: 'ESTIMATE →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'day-of-timeline-lite',
    slug: 'day-of-timeline-lite',
    name: 'Day-Of Timeline Builder',
    tagline: 'what time does everything happen?',
    description: 'Select your events, get a minute-by-minute day-of skeleton.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '2 min',
    featurePills: ['MINUTE-BY-MINUTE'],
    ctaText: 'BUILD IT →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'vendor-question-generator',
    slug: 'vendor-question-generator',
    name: 'Vendor Question Generator',
    tagline: 'what to ask before you book',
    description: 'Select vendor type, get the 10 questions you should be asking.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['BY VENDOR'],
    ctaText: 'GENERATE →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },
  {
    id: 'wedding-website-checklist',
    slug: 'wedding-website-checklist',
    name: 'Wedding Website Checklist',
    tagline: 'everything your wedding website needs',
    description: 'Select your events, get a content checklist for your website.',
    category: 'planning',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['CONTENT GUIDE'],
    ctaText: 'GENERATE →',
    gradientFrom: '#A8B5A0',
    gradientTo: '#E8F0E0',
  },

  // ── MONEY & BUDGET (mini) ────────────────────────────────────────────
  {
    id: 'per-guest-cost',
    slug: 'per-guest-cost',
    name: 'Per-Guest Cost Calculator',
    tagline: 'what does each guest actually cost you?',
    description: 'Total budget ÷ guest count, broken down by category.',
    category: 'money',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['BY CATEGORY'],
    ctaText: 'CALCULATE →',
    gradientFrom: '#D4943A',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'vendor-tip',
    slug: 'vendor-tip',
    name: 'Vendor Tip Calculator',
    tagline: 'how much do you tip wedding vendors?',
    description: 'Select vendor type, get US tipping norms + suggested amounts.',
    category: 'money',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['US NORMS'],
    ctaText: 'CALCULATE →',
    gradientFrom: '#D4943A',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'india-shopping-budget',
    slug: 'india-shopping-budget',
    name: 'India Shopping Budget Converter',
    tagline: 'what will ₹2,50,000 cost you in USD?',
    description: 'INR to USD with customs duty, shipping, and alteration buffer.',
    category: 'money',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['CUSTOMS INCLUDED'],
    ctaText: 'CONVERT →',
    gradientFrom: '#D4943A',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'wedding-roi',
    slug: 'wedding-roi',
    name: 'Wedding ROI Calculator',
    tagline: 'shagun in vs. wedding cost',
    description: 'Estimated shagun received vs. total spend. Tongue-in-cheek, mostly.',
    category: 'money',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['JUST FOR FUN'],
    ctaText: 'CALCULATE →',
    gradientFrom: '#D4943A',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'open-vs-cash-bar',
    slug: 'open-vs-cash-bar',
    name: 'Open Bar vs. Cash Bar Calculator',
    tagline: "what's cheaper for your guest count?",
    description: 'Guest count + hours + drink preference = cost comparison.',
    category: 'money',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['SIDE BY SIDE'],
    ctaText: 'COMPARE →',
    gradientFrom: '#D4943A',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'overtime-cost',
    slug: 'overtime-cost',
    name: 'Overtime Cost Estimator',
    tagline: 'what happens if your reception runs late?',
    description: 'Venue + DJ + photographer overtime rates × hours.',
    category: 'money',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['ALL VENDORS'],
    ctaText: 'ESTIMATE →',
    gradientFrom: '#D4943A',
    gradientTo: '#F5E6C8',
  },

  // ── ASTROLOGY & DATES (mini) ─────────────────────────────────────────
  {
    id: 'moon-sign',
    slug: 'moon-sign',
    name: "What's My Moon Sign?",
    tagline: 'find your Chandra Rashi instantly',
    description: 'Enter birth details, get Moon sign + Nakshatra.',
    category: 'astrology',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['INSTANT'],
    ctaText: 'FIND OUT →',
    gradientFrom: '#3D3580',
    gradientTo: '#E0D0F0',
  },
  {
    id: 'name-to-nakshatra',
    slug: 'name-to-nakshatra',
    name: 'Name to Nakshatra',
    tagline: 'what Nakshatra does your name belong to?',
    description: 'Enter your first name, get your birth star from syllable mapping.',
    category: 'astrology',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['SYLLABLE BASED'],
    ctaText: 'CHECK →',
    gradientFrom: '#3D3580',
    gradientTo: '#E0D0F0',
  },
  {
    id: 'mercury-retrograde',
    slug: 'mercury-retrograde',
    name: 'Mercury Retrograde Checker',
    tagline: 'is Mercury in retrograde right now?',
    description: 'Instant yes/no + next retrograde dates for 2026.',
    category: 'astrology',
    isFeatured: false,
    status: 'live',
    estimatedTime: '10 sec',
    featurePills: ['LIVE DATES'],
    ctaText: 'CHECK →',
    gradientFrom: '#3D3580',
    gradientTo: '#E0D0F0',
  },
  {
    id: 'wedding-season',
    slug: 'wedding-season',
    name: 'Wedding Season or Off-Season?',
    tagline: 'is your date peak, shoulder, or off?',
    description: 'Enter a date, get season classification + pricing impact.',
    category: 'astrology',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['PRICING IMPACT'],
    ctaText: 'CHECK →',
    gradientFrom: '#3D3580',
    gradientTo: '#E0D0F0',
  },
  {
    id: 'muhurat-window',
    slug: 'muhurat-window',
    name: 'Muhurat Window Finder',
    tagline: 'what time should your ceremony start?',
    description: 'Enter date + ceremony type, get the auspicious time window.',
    category: 'astrology',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['BY TRADITION'],
    ctaText: 'FIND IT →',
    gradientFrom: '#3D3580',
    gradientTo: '#E0D0F0',
  },
  {
    id: 'rashi-quick-match',
    slug: 'rashi-quick-match',
    name: 'Rashi Compatibility Quick Check',
    tagline: 'quick compatibility by Moon sign',
    description: 'Enter two Moon signs, get an instant one-paragraph summary.',
    category: 'astrology',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['LIGHTER VERSION'],
    ctaText: 'CHECK →',
    gradientFrom: '#3D3580',
    gradientTo: '#E0D0F0',
  },
  {
    id: 'planetary-transit-alert',
    slug: 'planetary-transit-alert',
    name: 'Planetary Transit Alert',
    tagline: 'which planets are moving this month?',
    description: 'Instant snapshot of current planetary positions and what they mean.',
    category: 'astrology',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['LIVE TRANSITS'],
    ctaText: 'CHECK →',
    gradientFrom: '#3D3580',
    gradientTo: '#E0D0F0',
  },
  {
    id: 'auspicious-color',
    slug: 'auspicious-color',
    name: 'Auspicious Color Finder',
    tagline: 'what color should you wear today?',
    description: "Enter your Rashi, get today's auspicious color.",
    category: 'astrology',
    isFeatured: false,
    status: 'live',
    estimatedTime: '10 sec',
    featurePills: ['DAILY'],
    ctaText: 'CHECK →',
    gradientFrom: '#3D3580',
    gradientTo: '#E0D0F0',
  },
  {
    id: 'manglik-quick-check',
    slug: 'manglik-quick-check',
    name: 'Manglik Quick Check',
    tagline: 'are you Manglik?',
    description: 'Enter birth details, get a preliminary Mangal Dosha assessment.',
    category: 'astrology',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['MANGAL DOSHA'],
    ctaText: 'CHECK →',
    gradientFrom: '#3D3580',
    gradientTo: '#E0D0F0',
  },

  // ── STYLE & VIBES (mini) ─────────────────────────────────────────────
  {
    id: 'outfit-calculator',
    slug: 'outfit-calculator',
    name: 'Outfit Count Calculator',
    tagline: 'how many looks do you actually need?',
    description:
      'Bride or groom, every event you picked, with notes per look. Plus the alteration timeline you have been ignoring and a budget reality check if your math is tight.',
    category: 'style',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['BRIDE OR GROOM', 'ALTERATION TIMELINE'],
    ctaText: 'COUNT YOUR LOOKS →',
    gradientFrom: '#E8B4B8',
    gradientTo: '#FBEAF0',
  },
  {
    id: 'wedding-aesthetic-quiz',
    slug: 'wedding-aesthetic-quiz',
    name: "What's Your Wedding Aesthetic?",
    tagline: 'minimalist queen or maximalist maharani?',
    description: 'A 5-question quiz that names your aesthetic and describes the mood.',
    category: 'style',
    isFeatured: false,
    status: 'live',
    estimatedTime: '2 min',
    featurePills: ['5 QUESTIONS'],
    ctaText: 'TAKE THE QUIZ →',
    gradientFrom: '#E8B4B8',
    gradientTo: '#FBEAF0',
  },
  {
    id: 'color-palette',
    slug: 'color-palette',
    name: 'Color Palette Generator',
    tagline: 'find your wedding colors',
    description: 'Select your vibe, season, and tradition — get a curated palette with hex codes.',
    category: 'style',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['HEX CODES'],
    ctaText: 'GENERATE →',
    gradientFrom: '#E8B4B8',
    gradientTo: '#FBEAF0',
  },
  {
    id: 'lehenga-carryon',
    slug: 'lehenga-carryon',
    name: 'Lehenga Carry-On Calculator',
    tagline: 'will it fit?',
    description: 'Weight + dimensions + airline = packing feasibility.',
    category: 'style',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['ALL AIRLINES'],
    ctaText: 'CHECK →',
    gradientFrom: '#E8B4B8',
    gradientTo: '#FBEAF0',
  },
  {
    id: 'outfit-changes',
    slug: 'outfit-changes',
    name: 'How Many Outfit Changes?',
    tagline: 'based on your events, how many looks do you need?',
    description: 'Event count → outfit map with timing.',
    category: 'style',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['OUTFIT MAP'],
    ctaText: 'PLAN IT →',
    gradientFrom: '#E8B4B8',
    gradientTo: '#FBEAF0',
  },
  {
    id: 'wedding-hashtag',
    slug: 'wedding-hashtag',
    name: 'Wedding Hashtag Generator',
    tagline: 'cute, clever, or cringe?',
    description: 'Enter both names, get culturally-aware hashtag suggestions.',
    category: 'style',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['NO CRINGE'],
    ctaText: 'GENERATE →',
    gradientFrom: '#E8B4B8',
    gradientTo: '#FBEAF0',
  },
  {
    id: 'bridal-entry-song',
    slug: 'bridal-entry-song',
    name: 'Bridal Entry Song Picker',
    tagline: "what's your walk-in vibe?",
    description: 'Select mood, tempo, and tradition — get song suggestions by ceremony type.',
    category: 'style',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['BY CEREMONY'],
    ctaText: 'PICK IT →',
    gradientFrom: '#E8B4B8',
    gradientTo: '#FBEAF0',
  },

  // ── FAMILY & GUESTS (mini) ───────────────────────────────────────────
  {
    id: 'invite-estimator',
    slug: 'invite-estimator',
    name: 'Invite List Estimator',
    tagline: 'how many people is this actually?',
    description:
      'A 30-second sanity check before you build the real list. Both sides, every tier — with a believable headcount range, table count, and hotel-room math.',
    category: 'family',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['BOTH SIDES', 'HEADCOUNT RANGE'],
    ctaText: 'ESTIMATE →',
    gradientFrom: '#C9A96E',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'aunty-approval',
    slug: 'aunty-approval',
    name: 'The Aunty Approval Score',
    tagline: 'how traditional is your wedding, really?',
    description: 'Tongue-in-cheek quiz that scores your wedding on the tradition spectrum.',
    category: 'family',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['SHAREABLE'],
    ctaText: 'TAKE THE QUIZ →',
    gradientFrom: '#C9A96E',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'plus-one-policy',
    slug: 'plus-one-policy',
    name: 'Plus-One Policy Decider',
    tagline: 'who gets a plus-one?',
    description: 'Input guest tiers + relationship status rules → policy framework.',
    category: 'family',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['POLICY FRAMEWORK'],
    ctaText: 'DECIDE →',
    gradientFrom: '#C9A96E',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'family-drama',
    slug: 'family-drama',
    name: 'Family Drama Predictor',
    tagline: 'which planning decision will cause the most debate?',
    description: 'Funny quiz based on family dynamics. Mostly for screenshots.',
    category: 'family',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['SCREENSHOT BAIT'],
    ctaText: 'PREDICT →',
    gradientFrom: '#C9A96E',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'kids-or-no-kids',
    slug: 'kids-or-no-kids',
    name: 'Kids or No Kids Calculator',
    tagline: 'how many kids are on your list — and what does that cost?',
    description: 'Kid guest count × extra considerations.',
    category: 'family',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['COST INCLUDED'],
    ctaText: 'CALCULATE →',
    gradientFrom: '#C9A96E',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'who-pays',
    slug: 'who-pays',
    name: 'Who Pays for What?',
    tagline: 'traditional breakdown vs. modern split',
    description: 'See who traditionally covers what, with notes on modern adaptations.',
    category: 'family',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['TRADITION + MODERN'],
    ctaText: 'CHECK →',
    gradientFrom: '#C9A96E',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'wedding-party-size',
    slug: 'wedding-party-size',
    name: 'Wedding Party Size Guide',
    tagline: 'how many bridesmaids is too many?',
    description: 'Event count + logistics → suggested party size.',
    category: 'family',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['LOGISTICS AWARE'],
    ctaText: 'CALCULATE →',
    gradientFrom: '#C9A96E',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'rsvp-followup',
    slug: 'rsvp-followup',
    name: 'RSVP Follow-Up Timer',
    tagline: 'when to chase RSVPs without being annoying',
    description: 'Input RSVP deadline → follow-up schedule.',
    category: 'family',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['POLITE NUDGE'],
    ctaText: 'PLAN IT →',
    gradientFrom: '#C9A96E',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'seating-complexity',
    slug: 'seating-complexity',
    name: 'Seating Chart Difficulty Score',
    tagline: 'how hard is your seating chart going to be?',
    description: 'Input family dynamics → difficulty rating.',
    category: 'family',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['DIFFICULTY RATING'],
    ctaText: 'SCORE IT →',
    gradientFrom: '#C9A96E',
    gradientTo: '#F5E6C8',
  },
  {
    id: 'who-walks-when',
    slug: 'who-walks-when',
    name: 'Who Walks When?',
    tagline: 'ceremony processional order',
    description: 'Select ceremony type → who enters when and in what order.',
    category: 'family',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['BY CEREMONY'],
    ctaText: 'CHECK →',
    gradientFrom: '#C9A96E',
    gradientTo: '#F5E6C8',
  },

  // ── FUN & SHAREABLE (mini) ───────────────────────────────────────────
  {
    id: 'shoe-game',
    slug: 'shoe-game',
    name: 'Shoe Game Question Generator',
    tagline: 'the reception game that ends up in everyone’s group chat',
    description:
      'Pick a length and a vibe. We’ll write the set, MC instructions and all — plus 3 questions custom-built for the two of you.',
    category: 'fun',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['PRINTABLE', 'AI-CUSTOMIZED'],
    ctaText: 'GENERATE THE SET →',
    gradientFrom: '#E07A5F',
    gradientTo: '#FFD8B8',
  },
  {
    id: 'vow-mad-libs',
    slug: 'vow-mad-libs',
    name: 'Wedding Vow Mad Libs',
    tagline: 'fill in the blanks, get a vow',
    description:
      'Eight questions, one delightfully unhinged draft — funny, heartfelt, and built entirely for the group chat.',
    category: 'fun',
    isFeatured: false,
    status: 'live',
    estimatedTime: '2 min',
    featurePills: ['AI-WRITTEN', 'SHAREABLE'],
    ctaText: 'WRITE MY VOW →',
    gradientFrom: '#E07A5F',
    gradientTo: '#FFD8B8',
  },
  {
    id: 'wedding-personality',
    slug: 'wedding-personality',
    name: "What's Your Wedding Personality?",
    tagline: 'micromanager or mystery bride?',
    description:
      'Seven questions, one slightly judgmental archetype, fully shareable — calibrated on every desi WhatsApp group ever.',
    category: 'fun',
    isFeatured: false,
    status: 'live',
    estimatedTime: '2 min',
    featurePills: ['SHAREABLE', '4 ARCHETYPES'],
    ctaText: 'FIND MY ARCHETYPE →',
    gradientFrom: '#E07A5F',
    gradientTo: '#FFD8B8',
  },
  {
    id: 'compatibility',
    slug: 'compatibility',
    name: 'Couple Compatibility Score',
    tagline: 'answer separately. compare. survive.',
    description:
      'Both partners answer 10 questions on the same device or via a shared link. We tally the score and surface the one thing worth a conversation.',
    category: 'fun',
    isFeatured: false,
    status: 'live',
    estimatedTime: '2 min',
    featurePills: ['SHAREABLE LINK', 'SCORED'],
    ctaText: 'PLAY THE QUIZ →',
    gradientFrom: '#E07A5F',
    gradientTo: '#FFD8B8',
  },
  {
    id: 'sangeet-songs',
    slug: 'sangeet-songs',
    name: 'Sangeet Song Suggester',
    tagline: 'Bollywood night or something unexpected?',
    description:
      'Five questions in, six DJ-ready sections out — entry to finale, real songs, real artists, ready for your first DJ meeting.',
    category: 'fun',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['DJ BRIEF', 'PRINT-READY'],
    ctaText: 'BUILD MY BRIEF →',
    gradientFrom: '#E07A5F',
    gradientTo: '#FFD8B8',
  },
  {
    id: 'how-extra',
    slug: 'how-extra',
    name: 'How Extra Is Your Wedding?',
    tagline: 'rate your wedding on the extravagance scale',
    description: 'Fun quiz comparing your plans to averages.',
    category: 'fun',
    isFeatured: false,
    status: 'live',
    estimatedTime: '2 min',
    featurePills: ['SHAREABLE'],
    ctaText: 'RATE IT →',
    gradientFrom: '#E07A5F',
    gradientTo: '#FFD8B8',
  },
  {
    id: 'wedding-bingo',
    slug: 'wedding-bingo',
    name: 'Wedding Bingo Generator',
    tagline: 'custom bingo cards for your reception',
    description: 'Select culturally-specific moments → printable cards.',
    category: 'fun',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['PRINTABLE'],
    ctaText: 'GENERATE →',
    gradientFrom: '#E07A5F',
    gradientTo: '#FFD8B8',
  },
  {
    id: 'shaadi-countdown',
    slug: 'shaadi-countdown',
    name: 'Shaadi Countdown',
    tagline: 'how many days until your wedding?',
    description: 'Enter your date → beautiful countdown with milestones.',
    category: 'fun',
    isFeatured: false,
    status: 'live',
    estimatedTime: '10 sec',
    featurePills: ['LIVE TICKER'],
    ctaText: 'START COUNTDOWN →',
    gradientFrom: '#E07A5F',
    gradientTo: '#FFD8B8',
  },
  {
    id: 'bollywood-wedding',
    slug: 'bollywood-wedding',
    name: 'What Bollywood Wedding Are You?',
    tagline: 'DDLJ or Yeh Jawaani Hai Deewani?',
    description: 'Fun personality quiz with Bollywood references.',
    category: 'fun',
    isFeatured: false,
    status: 'live',
    estimatedTime: '2 min',
    featurePills: ['MOVIE MATCH'],
    ctaText: 'TAKE THE QUIZ →',
    gradientFrom: '#E07A5F',
    gradientTo: '#FFD8B8',
  },
  {
    id: 'couple-nickname',
    slug: 'couple-nickname',
    name: 'Couple Name Generator',
    tagline: 'your celebrity couple name',
    description: 'Enter both names → blended nickname options.',
    category: 'fun',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['BRANGELINA STYLE'],
    ctaText: 'GENERATE →',
    gradientFrom: '#E07A5F',
    gradientTo: '#FFD8B8',
  },
  {
    id: 'sangeet-theme',
    slug: 'sangeet-theme',
    name: 'Sangeet Theme Generator',
    tagline: 'Bollywood night or something unexpected?',
    description: 'Quick quiz → theme idea with decor + music direction.',
    category: 'fun',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['THEME + DECOR'],
    ctaText: 'GENERATE →',
    gradientFrom: '#E07A5F',
    gradientTo: '#FFD8B8',
  },

  // ── DAY-OF (mini) ────────────────────────────────────────────────────
  {
    id: 'emergency-kit',
    slug: 'emergency-kit',
    name: 'Emergency Kit Checklist',
    tagline: 'what goes in the bridal emergency kit?',
    description: 'Select your ceremony type → customized checklist.',
    category: 'day-of',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['BY CEREMONY'],
    ctaText: 'GENERATE →',
    gradientFrom: '#7A1F3E',
    gradientTo: '#E8B4B8',
  },
  {
    id: 'getting-ready-timeline',
    slug: 'getting-ready-timeline',
    name: 'Getting-Ready Timeline',
    tagline: 'what time does the bride wake up?',
    description: 'Input ceremony time → reverse-engineer the morning schedule.',
    category: 'day-of',
    isFeatured: false,
    status: 'live',
    estimatedTime: '1 min',
    featurePills: ['REVERSE TIMELINE'],
    ctaText: 'BUILD IT →',
    gradientFrom: '#7A1F3E',
    gradientTo: '#E8B4B8',
  },
  {
    id: 'photo-shot-list',
    slug: 'photo-shot-list',
    name: 'Photo Shot List Builder',
    tagline: "don't forget these shots",
    description: 'Select events + family structure → customized photo checklist.',
    category: 'day-of',
    isFeatured: false,
    status: 'live',
    estimatedTime: '2 min',
    featurePills: ['PRINTABLE'],
    ctaText: 'BUILD IT →',
    gradientFrom: '#7A1F3E',
    gradientTo: '#E8B4B8',
  },
  {
    id: 'vendor-contact-sheet',
    slug: 'vendor-contact-sheet',
    name: 'Vendor Contact Sheet Generator',
    tagline: "one page with every vendor's phone number",
    description: 'Input vendor names + phones → formatted contact sheet.',
    category: 'day-of',
    isFeatured: false,
    status: 'live',
    estimatedTime: '2 min',
    featurePills: ['ONE-PAGER'],
    ctaText: 'GENERATE →',
    gradientFrom: '#7A1F3E',
    gradientTo: '#E8B4B8',
  },
  {
    id: 'weather-backup',
    slug: 'weather-backup',
    name: 'Weather Backup Plan Checker',
    tagline: "what's the weather forecast for your wedding date?",
    description: 'Location + date → forecast + indoor backup reminder.',
    category: 'day-of',
    isFeatured: false,
    status: 'live',
    estimatedTime: '30 sec',
    featurePills: ['LIVE FORECAST'],
    ctaText: 'CHECK →',
    gradientFrom: '#7A1F3E',
    gradientTo: '#E8B4B8',
  },
];

export function getFlagshipTools(): CatalogTool[] {
  const map = new Map(TOOLS_CATALOG.map((t) => [t.slug, t]));
  return FLAGSHIP_ORDER.map((slug) => map.get(slug)).filter(
    (t): t is CatalogTool => Boolean(t),
  );
}

export function getCategoryCounts(): Record<ToolCategory | 'all', number> {
  const counts: Record<string, number> = { all: TOOLS_CATALOG.length };
  for (const tool of TOOLS_CATALOG) {
    counts[tool.category] = (counts[tool.category] ?? 0) + 1;
  }
  return counts as Record<ToolCategory | 'all', number>;
}
